### ISSUE TITLE
Class files in an app's root dir should not be available to webstart at runtime

### ISSUE THREAD

**Issue by AndreasEhret** [AdoptOpenJDK/IcedTea-Web#108]
This issue was imported from bugzilla with bugzilla2github
# Bugzilla Bug Referenze: [1017](https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=1017)
Date: 2012-05-28 18:23:00 +0000
From: Danesh Dadachanji &lt;<ddadacha>&gt;
To:   Omair Majid &lt;<omajid>&gt;
CC:   ddadacha, unassigned

Last updated: 2012-06-07 21:17:01 +0000

## Comment 4870
Date: 2012-05-28 18:23:29 +0000
From: Danesh Dadachanji &lt;<ddadacha>&gt;

Setup an app running from 'javaws http://example.com/scratch/app.jnlp' and have the main class call
                some.pkged.Helper.doSomething(). This class should _not_ be in any of the JNLP's resources. Instead, it
                should be found at http://example.com/scratch/some/pkged/Helper.class.

                The app should not be able to find some.pkged.Helper since it isn't in any of the JNLP's resources.
                However, it runs fine on HEAD.

                If the helper class runs code that needs more permissions, the following exception is thrown:

                Error: No security instance for http://example.com/scratch/. The application may have trouble continuing
                java.lang.RuntimeException: Code source security was null
                at net.sourceforge.jnlp.runtime.JNLPClassLoader.getPermissions(JNLPClassLoader.java:923)
                at net.sourceforge.jnlp.runtime.JNLPPolicy.getPermissions(JNLPPolicy.java:86)
                at net.sourceforge.jnlp.runtime.JNLPPolicy.implies(JNLPPolicy.java:182)
                at java.security.ProtectionDomain.implies(ProtectionDomain.java:272)
                at java.security.AccessControlContext.checkPermission(AccessControlContext.java:344)
                at java.security.AccessController.checkPermission(AccessController.java:555)
                at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
                at net.sourceforge.jnlp.runtime.JNLPSecurityManager.checkPermission(JNLPSecurityManager.java:284)
                at java.lang.System.getenv(System.java:933)
                at some.pkged.Helper.doSomething(Helper.java:5)
                at MyApp.init(MyApp.java:12)
                at sun.applet.AppletPanel.run(AppletPanel.java:435)
                at java.lang.Thread.run(Thread.java:722)

**Comment by douph1** [comment]
You mean that you want remote class loading on demand ?
