### ISSUE TITLE
App runs with icedtea-web 1.7.1 but fails on 1.8

### ISSUE THREAD

**Issue by k-d-96** [AdoptOpenJDK/icedtea-web#184]
App launches properly with icedtea-web 1.7.1 and mostly works except for some JavaFX stuff, which was apparently fixed in 1.8, so I wanted to try and launch the app with the latest version.
This fails, as the console shows a localized error message that after translating says something like:
`net.sourceforge.jnlp.LaunchException: Fatal: Startup error: Could not start the JNLP file. Application was not initalized.`
Tested with several free Java distributions, yielding the same result.

**Comment by judovana** [comment]
If this would be true, then ITW would be swarmed by bugs. There must be something wrong in your config. Please share  what ITW are yo using (msi, distribution, zip) and what jdk are you using (8, 11, 12, open, oracle).  Waht ITW 1.7 you were using? Win, linux? Do you mind to attach verbose log? Do you mind to share jnlp files which were not working so we may try?

**Comment by k-d-96** [comment]
ITW 1.7.1: icedtea-web-1.7.1.win.bin.zip
ITW 1.8: icedtea-web-1.8.win.bin.zip, also tried icedtea-web-1.8.portable.bin.zip
In the javaws.bat file I defined paths for Java by adding at the beginning:
`set "INST_ITW_HOME=C:\icedtea-web-image"
set "INST_JAVA_HOME=C:\Zulu\zulu8.36.0.1-ca-fx-jdk8.0.202-win_x64\jre"
set "JAVA_HOME=C:\Zulu\zulu8.36.0.1-ca-fx-jdk8.0.202-win_x64\jre"`
For Java, I tried ZuluFX, AdoptOpenJDK and Amazon Corretto.
I'm on Windows 7 x64.
The .jnlp file is licensed/proprietary and I'd rather not share it. Are there any test .jnlp files that I could try and run? Maybe one of them would have the same issue.
Feeling the same about the full log, do you mind if I share you the log via PM? Not sure if the log would be of same use if I cut out any data that I don't want to go public.

**Comment by douph1** [comment]
Hi,
>Are there any test .jnlp files that I could try and run?

https://docs.oracle.com/javase/tutorial/uiswing/examples/misc/index.html

**Comment by k-d-96** [comment]
> https://docs.oracle.com/javase/tutorial/uiswing/examples/misc/index.html

Thank you. I tested a random app (picked ShapedWindowDemo) and it results in the same error.
Log below. Since the system account's name is my real name, I replaced it with "John Doe", "John%20Doe" or "JOHNDO~1", depending on how it was written. Hopefully it's not an issue.

https://gist.github.com/k-d-96/13a7ceb68cdb2e310e77b03cd7dade1e

**Comment by douph1** [comment]
Maybe this ? :
java.net.URISyntaxException: Illegal character in path at index 21: file://C:/Users/John Doe/.config/icedtea-web/security/java.policy     at java.net.URI$Parser.fail(URI.java:2848)     at java.net.URI$Parser.checkChars(URI.java:3021)     at java.net.URI$Parser.parseHierarchical(URI.java:3105)     at java.net.URI$Parser.parse(URI.java:3053)     at java.net.URI.<init>(URI.java:588)     at net.sourceforge.jnlp.runtime.JNLPPolicy.getPolicyFromUrl(JNLPPolicy.java:188)     at net.sourceforge.jnlp.runtime.JNLPPolicy.<init>(JNLPPolicy.java:64)     at net.sourceforge.jnlp.runtime.JNLPRuntime.initialize(JNLPRuntime.java:260)     at net.sourceforge.jnlp.runtime.Boot.init(Boot.java:349)     at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:58)     at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:270)     at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)     at java.security.AccessController.doPrivileged(Native Method)     at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:210)

**Comment by the-suspect2** [comment]
If I were to put the real name back into "file://C:/Users/John Doe/.config/icedtea-web/security/java.policy" and count the characters starting from 0, it would point to " " (space). Problem with spaces in usernames?
I can try creating an account with no spaces and see if that fixes it, but since the PC is connected to the domain, I'd love to see it fixed.

**Comment by douph1** [comment]
Yes, space are not allowed in java.net.URI so this is the bug (to use path as URI).. but already present in 1.7.2.
Can you confirm that you have changed username when switching from 1.7.2 to 1.8.

I have tested and both 1.7 and 1.8 don't work when username contain space.
Can you confirm please ?
If confirmed, this is not a regression in 1.8

**Comment by the-suspect2** [comment]
No, I haven't changed my username when coming to 1.8 - it also had a space when I was using 1.7.1, which worked.

**Comment by douph1** [comment]
@the-suspect2  you are right, I have missed my test yesterday.
I confirm the bug is not present un 1.7.1 and 1.7.2.
The "java.net.URISyntaxException: Illegal character in path at index" is already present in 1.7.1 and 1.7.2 but it is a non-blocking exception and jnlp start well.
I have added a new bug for this : https://github.com/AdoptOpenJDK/icedtea-web/issues/197

For you bug, it is maybe a classpath problem wich dont handle space well because jar are downloaded into cache folder wich is by default in user home : C:\Users\<username>\.cache\icedtea-web\cache

I have tried a workaroud ( setting a folder without space for cache folder)  but without success .. new bug filled : https://github.com/AdoptOpenJDK/icedtea-web/issues/198

**Comment by the-suspect2** [comment]
I was just about to post a log of me launching a .jnlp app on 1.7.1 successfully :)
Thank you for the help with researching this.

**Comment by the-suspect2** [comment]
After changing the cache path, a different error is shown:
```[John Doe][ITW-JAVAWS][WARNING_ALL][Wed Apr 24 11:41:15 CEST 2019][net.sourceforge.jnlp.util.logging.FileLog.getHeadlineHeader(FileLog.java:53)] NETX Thread# 60589886, name Output controller consumer daemon writer-based impl.
java.net.URISyntaxException: Illegal character in path at index 21: file://C:/Users/John Doe/.config/icedtea-web/security/java.policy
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at net.sourceforge.jnlp.runtime.JNLPPolicy.getPolicyFromUrl(JNLPPolicy.java:188)
	at net.sourceforge.jnlp.runtime.JNLPPolicy.<init>(JNLPPolicy.java:64)
	at net.sourceforge.jnlp.runtime.JNLPRuntime.initialize(JNLPRuntime.java:260)
	at net.sourceforge.jnlp.runtime.Boot.init(Boot.java:349)
	at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:58)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:270)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:210)
netx: Błąd odczytu: Nie można odczytać lub przeprowadzić analizy składni pliku JNLP. (java.io.FileNotFoundException: D:\ictw_cache\37\https\docs.oracle.com\javase\tutorialJWS\samples\uiswing\ShapedWindowDemoProject\ShapedWindowDemo.jnlp (Nie można odnaleźć określonego pliku) (D:\ictw_cache\37\https\docs.oracle.com\javase\tutorialJWS\samples\uiswing\ShapedWindowDemoProject\ShapedWindowDemo.jnlp (Nie można odnaleźć określonego pliku)))
```
In that directory, the only file present is "ShapedWindowDemo.jnlp.info.temp", which is 0 B in size.

**Comment by douph1** [comment]
@the-suspect2  as filled here : https://github.com/AdoptOpenJDK/icedtea-web/issues/197
this is not a blocking issue

be carefull with the acl/right in the new cache folder ( rw ) needed

**Comment by the-suspect2** [comment]
I granted full access to the cache folder for the group "Everyone" and I still experience the error.

**Comment by douph1** [comment]
and no previous message before this one ? :

netx: Błąd odczytu: Nie można odczytać lub przeprowadzić analizy składni pliku JNLP. (java.io.FileNotFoundException: D:\ictw_cache\37\https\docs.oracle.com\javase\tutorialJWS\samples\uiswing\ShapedWindowDemoProject\ShapedWindowDemo.jnlp (Nie można odnaleźć określonego pliku) (D:\ictw_cache\37\https\docs.oracle.com\javase\tutorialJWS\samples\uiswing\ShapedWindowDemoProject\ShapedWindowDemo.jnlp (Nie można odnaleźć określonego pliku)))

**Comment by the-suspect2** [comment]
The error message I posted above is what I've taken from the log that was in .config\log. That was its full content.
There's also this, taken from the "Error" window shown by ICW when trying to launch something:
```
net.sourceforge.jnlp.LaunchException: Fatalny: Błąd odczytu: Nie można odczytać lub przeprowadzić analizy składni pliku JNLP. Możesz spróbować ręcznie pobrać ten plik i wysłać go razem ze zgłoszeniem błędu do zespołu IcedTea-Web.
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)
	at net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)
	at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:270)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:210)
Caused by: java.io.IOException: java.io.FileNotFoundException: D:\ictw_cache\64\https\docs.oracle.com\javase\tutorialJWS\samples\uiswing\ShapedWindowDemoProject\ShapedWindowDemo.jnlp (Nie można odnaleźć określonego pliku)
	at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:318)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:240)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:453)
	... 6 more
Caused by: java.io.FileNotFoundException: D:\ictw_cache\64\https\docs.oracle.com\javase\tutorialJWS\samples\uiswing\ShapedWindowDemoProject\ShapedWindowDemo.jnlp (Nie można odnaleźć określonego pliku)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:316)
	... 11 more
```
The Java console shows up when I'm launching an app, but when the "Error" window spawns, I cannot copy its contents (I cannot activate the window, it's blocked), and clicking "OK" closes the console as well.

**Comment by jaysk1** [comment]
I am able to launch most of the .jnlps on ITW1.8 without issues. I ran my own SVT tests and also tested on ShapedWindowDemo.jnlp,  both from local system as well as from web directly and still couldn’t recreate the Error above.
 All I see after the jnlp is launched is :
Denying permission: (“java.awt.AWTPermission” “accessClipboard”) which is nothing harmful. 
Note: My caches all are named without spaces. I used Adopopenjdk builds

How have you been trying to launch the jnlp?  javaws.exe {location}.jnlp ?

**Comment by the-suspect2** [comment]
Yes, either by the command you said, or drag and dropping the jnlp file
onto javaws.

czw., 2 maj 2019, 10:41 użytkownik Jayashree S Kumar <
notifications@github.com> napisał:

**Comment by douph1** [comment]
I reproduce actually a bug when settings the cache path to a folder != from the default one.
This is the workaround I have proposed to @the-suspect2 because of bug for handling username with space.

But now each time I try to set a cache folder I have the same kind of error : FileNotFoundException

**Comment by douph1** [comment]
like if
`if (JNLPRuntime.isWindows()) {`
is false and we go into 
`else {
            // remove all permissions`

**Comment by douph1** [comment]
or setAcl don't work ..

**Comment by douph1** [comment]
ok, it works if I add myself (the user) full access to the cache folder
but not if I have full access to the cache folder by a group I belong to.

And it so I understand this is linked to UAC.

https://superuser.com/questions/1006655/file-permissions-administrators-full-control-why-isnt-it-always-sufficient

@judovana maybe what is intended to do in createRestrictedFile is to duplicate acl for the owner ?
// filter ACL's leaving only root and owner

I think it doesn't work for account who are in administrators group

I will try with a non-administrator user to see

**Comment by douph1** [comment]
> I granted full access to the cache folder for the group "Everyone" and I still experience the error.

You must give full access to the user ( not a group )
I have the same behaviour with an admin or a standard user ( giving full access to a group belonging to is doesn't work )

@judovana  do you think it is a expected behaviour ?

**Comment by the-suspect2** [comment]
Thank you @douph1 , adding permissions for the exact user worked.
Hopefully that's not expected behaviour, that would mean repeating the procedure of adding permissions to the cache folder every time a new user starts using the computer.

**Comment by VanDecker** [comment]
STR:

0. Download jnlp to disk:
 ShapedWindowDemo [Launch] https://docs.oracle.com/javase/tutorialJWS/samples/uiswing/ShapedWindowDemoProject/ShapedWindowDemo.jnlp

1. And" run it" using ~\icedteaweb\bin\javaws through windows context menu on jnlp: 

Result:

net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file. You can try to download this file manually and send it as bug report to IcedTea-Web team.
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)
	at net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)
	at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:270)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:210)
Caused by: java.io.IOException: java.lang.NullPointerException: name can't be null
	at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:318)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:240)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:453)
	... 6 more
Caused by: java.lang.NullPointerException: name can't be null
	at java.io.FilePermission.init(FilePermission.java:191)
	at java.io.FilePermission.<init>(FilePermission.java:277)
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
	at java.io.FileInputStream.<init>(FileInputStream.java:127)
	at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:316)
	... 11 more


Java console stalls out at:

[cdecker][ITW-APPLET][MESSAGE_DEBUG][Tue Jul 16 10:19:58 PDT 2019][net.sourceforge.jnlp.config.DeploymentConfiguration.<init>(DeploymentConfiguration.java:310)] NETX Thread# 2d98a335, name main: Ico provider registered correctly.
[cdecker][ITW-APPLET][MESSAGE_DEBUG][Tue Jul 16 10:19:58 PDT 2019][net.sourceforge.jnlp.config.DeploymentConfiguration.move14AndOlderFilesTo15Structure(DeploymentConfiguration.java:880)] NETX Thread# 2d98a335, name main: cache: C:\Users\cdecker\.cache\icedtea-web file exists:true
[cdecker][ITW-APPLET][MESSAGE_DEBUG][Tue Jul 16 10:19:58 PDT 2019][net.sourceforge.jnlp.config.DeploymentConfiguration.move14AndOlderFilesTo15Structure(DeploymentConfiguration.java:875)] NETX Thread# 2d98a335, name main: config: C:\Users\cdecker\.config\icedtea-web file exists: true
[cdecker][ITW-APPLET][MESSAGE_DEBUG][Tue Jul 16 10:19:58 PDT 2019][net.sourceforge.jnlp.config.DeploymentConfiguration.move14AndOlderFilesTo15Structure(DeploymentConfiguration.java:873)] NETX Thread# 2d98a335, name main: System is already following XDG .cache and .config specifications

**Comment by douph1** [comment]
Hi @VanDecker,  why do you think you previous comment is linked to the same bug ?
You show us : java.lang.NullPointerException: name can't be null
wich was never mentionned in this bug report.
If it is a mistake, please confirm, and if necessary open a new bug please

**Comment by Jamila891** [comment]
hey @the-suspect2, what is the current state of this issue?

**Comment by the-suspect2** [comment]
Current state is highlighted in my previous comment:
https://github.com/AdoptOpenJDK/IcedTea-Web/issues/184#issuecomment-495090229

Works when the specific user is given full rights to the cache directory,
but setting permissions like this in a domain environment sounds like a
pain. IMO that's an issue to fix.

Unless that may have changed, please give me time until the end of this
week and I'll test this again on the newest version of ITW

pon., 21 wrz 2020, 13:53 użytkownik Jamila891 <notifications@github.com>
napisał:

**Comment by sclassen** [comment]
The `createRestrictedFile()` has not changed.
So most likely this still persists
