### ISSUE TITLE
Path URI for with space throw java.net.URISyntaxException

### ISSUE THREAD

**Issue by douph1** [AdoptOpenJDK/IcedTea-Web#197]
Seen in 1.7.1 1.7.2 1.8
When Windows username contain  a space there is a exception when building URI

This is a non-blocking exception but prevent loading java.policy

java.net.URISyntaxException: Illegal character in path at index 24: file://C:/Users/philippe doussot/.config/icedtea-web/security/java.policy
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.checkChars(URI.java:3021)
        at java.net.URI$Parser.parseHierarchical(URI.java:3105)
        at java.net.URI$Parser.parse(URI.java:3053)
        at java.net.URI.<init>(URI.java:588)
        at net.sourceforge.jnlp.runtime.JNLPPolicy.getPolicyFromUrl(JNLPPolicy.java:188)
        at net.sourceforge.jnlp.runtime.JNLPPolicy.<init>(JNLPPolicy.java:64)
        at net.sourceforge.jnlp.runtime.JNLPRuntime.initialize(JNLPRuntime.java:259)
        at net.sourceforge.jnlp.runtime.Boot.init(Boot.java:337)
        at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:58)
        at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:258)
        at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:62)
        at java.security.AccessController.doPrivileged(Native Method)
        at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:198)

**Comment by karianna** [comment]
Adding 1.8.x to this as we're unlikely to patch 1.7

**Comment by akashche** [comment]
Hi, I think I fixed the same issue for ojdkbuild builds - [change](https://github.com/ojdkbuild/lookaside_icedtea-web/commit/2bdab79a9d6dd3d5286c834365716c47876f1a17). Besides `JNLPPolicy`, actual problem was with class loading. The change may be too conservative and some general cleanup to URL/URI handling may be preferred instead.

**Comment by sclassen** [comment]
@Budlee This might be a good issue to start working on icedtea-web

**Comment by Budlee** [comment]
Hey,
I'd be keen to take this one on. 👍

**Comment by karianna** [comment]
I've invited you to the team so we can assign this to you - but please go ahead.

**Comment by Budlee** [comment]
Thanks @karianna, Joined the group

**Comment by Budlee** [comment]
Sorry for the delay on this. Should submit this soon

**Comment by Budlee** [comment]
Added a PR for this issue
https://github.com/AdoptOpenJDK/IcedTea-Web/pull/290
