### ISSUE TITLE
Many java.net.URISyntaxException for favicon.ico

### ISSUE THREAD

**Issue by douph1** [AdoptOpenJDK/IcedTea-Web#199]
ITW 1.8 ( Windows )

I have many ( non bloking ) exception because URL is not well normalised backslash instead of slash

```
You are trying to get resource https://apoweb-preprod-integration.phmd.net/favicon.ico but it is not in cache and could not be downloaded. Attempting to continue, but you may expect failure
Connecting https://apoweb-preprod-integration.phmd.net/favicon.ico
java.net.URISyntaxException: Illegal character in authority at index 8: https://apoweb-preprod-integration.phmd.net\favicon.ico
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.parseAuthority(URI.java:3186)
        at java.net.URI$Parser.parseHierarchical(URI.java:3097)
        at java.net.URI$Parser.parse(URI.java:3053)
        at java.net.URI.<init>(URI.java:673)
        at net.sourceforge.jnlp.util.UrlUtils.normalizeUrl(UrlUtils.java:135)
        at net.sourceforge.jnlp.util.UrlUtils.normalizeUrl(UrlUtils.java:145)
        at net.sourceforge.jnlp.util.UrlUtils.urlEquals(UrlUtils.java:317)
        at net.sourceforge.jnlp.cache.Resource.equals(Resource.java:457)
        at java.util.AbstractList.indexOf(AbstractList.java:185)
        at net.sourceforge.jnlp.cache.Resource.getResource(Resource.java:129)
        at net.sourceforge.jnlp.cache.ResourceTracker.addResource(ResourceTracker.java:151)
        at net.sourceforge.jnlp.cache.CacheUtil.getCachedResourceFile(CacheUtil.java:113)
        at net.sourceforge.jnlp.cache.CacheUtil.getCachedResourceURL(CacheUtil.java:90)
        at net.sourceforge.jnlp.util.XDesktopEntry.getFavIconUrl(XDesktopEntry.java:540)
        at net.sourceforge.jnlp.util.XDesktopEntry.getFavIcon(XDesktopEntry.java:488)
        at net.sourceforge.jnlp.util.WindowsDesktopEntry.getFavIcon(WindowsDesktopEntry.java:134)
        at net.sourceforge.jnlp.util.WindowsDesktopEntry.createWindowsMenu(WindowsDesktopEntry.java:84)
        at net.sourceforge.jnlp.runtime.ApplicationInstance.addMenuAndDesktopEntries(ApplicationInstance.java:200)
        at net.sourceforge.jnlp.runtime.ApplicationInstance.initialize(ApplicationInstance.java:148)
        at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:532)
        at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:945)
```

**Comment by douph1** [comment]
Other sample slightly different exception for same cause:

`java.io.IOException: Server returned HTTP response code: 400 for URL: https://apoweb-preprod-integration.phmd.net/preprod_integration%5Cfavicon.ico     at sun.reflect.GeneratedConstructorAccessor18.newInstance(Unknown Source)     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)     at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)     at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)     at java.security.AccessController.doPrivileged(Native Method)     at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)     at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)     at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)     at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1484)     at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1482)     at java.security.AccessController.doPrivileged(Native Method)     at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)     at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1481)     at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)     at net.sourceforge.jnlp.cache.ResourceDownloader.downloadFile(ResourceDownloader.java:416)     at net.sourceforge.jnlp.cache.ResourceDownloader.downloadResource(ResourceDownloader.java:364)     at net.sourceforge.jnlp.cache.ResourceDownloader.run(ResourceDownloader.java:118)     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)     at java.lang.Thread.run(Thread.java:748) Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://apoweb-preprod-integration.phmd.net/preprod_integration%5Cfavicon.ico     at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)     at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)     at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1484)     at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1482)     at java.security.AccessController.doPrivileged(Native Method)     at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)     at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1481)     at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3051)     at java.net.URLConnection.getContentEncoding(URLConnection.java:523)     at sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentEncoding(HttpsURLConnectionImpl.java:419)     at net.sourceforge.jnlp.cache.ResourceDownloader.downloadResource(ResourceDownloader.java:346)     ... 4 more`

**Comment by douph1** [comment]
Other sample slightly different exception for same cause:

```
Connecting https://apoweb-preprod-integration.phmd.net\favicon.ico
java.lang.IllegalArgumentException: Invalid characters in hostname     at java.net.HostPortrange.toLowerCase(HostPortrange.java:189)     at java.net.HostPortrange.<init>(HostPortrange.java:150)     at java.net.URLPermission$Authority.<init>(URLPermission.java:486)     at java.net.URLPermission.parseURI(URLPermission.java:454)     at java.net.URLPermission.init(URLPermission.java:170)     at java.net.URLPermission.<init>(URLPermission.java:166)     at sun.net.www.protocol.http.HttpURLConnection.URLtoSocketPermission(HttpURLConnection.java:1084)     at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1477)     at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3087)     at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:489)     at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)     at net.sourceforge.jnlp.cache.ResourceDownloader.getUrlResponseCodeWithRedirectonResult(ResourceDownloader.java:78)     at net.sourceforge.jnlp.cache.ResourceDownloader.findBestUrl(ResourceDownloader.java:293)     at net.sourceforge.jnlp.cache.ResourceDownloader.initializeOnlineResource(ResourceDownloader.java:132)     at net.sourceforge.jnlp.cache.ResourceDownloader.initializeResource(ResourceDownloader.java:124)     at net.sourceforge.jnlp.cache.ResourceDownloader.run(ResourceDownloader.java:113)     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)     at java.lang.Thread.run(Thread.java:748)
```

**Comment by karianna** [comment]
@douph1 Is this a blocker for 1.8.1 do you think?

**Comment by douph1** [comment]
No, all the exception above are non blocking.
It obfuscate for finding real error and must be patch but there is any requirement for 1.8.1.
I suppose there is a feature with favicon.ico .. but dont know who are using favicon with jnlp simply because JNLP spec provide a way to configur a ICON:  https://docs.oracle.com/javase/7/docs/technotes/guides/javaws/developersguide/syntax.html
A URL pointing to the icon file, may be in one of the following formats: gif, jpg, png, ico.

**Comment by fleminra** [comment]
This still happens in OpenWebStart 1.9.1, at least in the situation where the application has no declared icon (didn't test what happens when one is declared). I get this 82 times (on Linux) and 81 times (on Windows) from the stderr of javaws:
```
java.net.URISyntaxException: Illegal character in authority at index 7: http://example.com\favicon.ico
      at java.base/java.net.URI$Parser.fail(URI.java:2913)
      at java.base/java.net.URI$Parser.parseAuthority(URI.java:3247)
      at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3158)
      at java.base/java.net.URI$Parser.parse(URI.java:3114)
      at java.base/java.net.URI.<init>(URI.java:685)
      at net.sourceforge.jnlp.util.UrlUtils.normalizeUrl(UrlUtils.java:157)
      at net.sourceforge.jnlp.util.UrlUtils.normalizeUrl(UrlUtils.java:165)
      at net.sourceforge.jnlp.util.UrlUtils.urlEquals(UrlUtils.java:331)
      at net.adoptopenjdk.icedteaweb.resources.Resource.equals(Resource.java:270)
      at java.base/java.util.AbstractList.indexOf(AbstractList.java:192)
      at net.adoptopenjdk.icedteaweb.resources.Resource.createOrGetResource(Resource.java:128)
      at net.adoptopenjdk.icedteaweb.resources.ResourceTracker.addResource(ResourceTracker.java:159)
      at net.adoptopenjdk.icedteaweb.resources.ResourceTracker.addResource(ResourceTracker.java:137)
      at net.sourceforge.jnlp.cache.CacheUtil.downloadAndGetCacheFile(CacheUtil.java:79)
      at com.openwebstart.os.linux.FavIcon.download(FavIcon.java:44)
      at com.openwebstart.os.linux.LinuxEntryFactory.getIconLocation(LinuxEntryFactory.java:186)
      at com.openwebstart.os.linux.LinuxEntryFactory.createMenuEntry(LinuxEntryFactory.java:75)
      at com.openwebstart.os.linux.LinuxEntryFactory.updateMenuEntry(LinuxEntryFactory.java:43)
      at com.openwebstart.os.MenuAndDesktopEntryHandler.lambda$updateEntries$1(MenuAndDesktopEntryHandler.java:74)
      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
      at java.base/java.lang.Thread.run(Thread.java:829)

```
Relevant code is here: https://github.com/AdoptOpenJDK/IcedTea-Web/blob/1be00cff3993d6b74b9d99df2a49149f52b48ae3/core/src/main/java/net/sourceforge/jnlp/util/XDesktopEntry.java#L486

Commit that added it: https://github.com/AdoptOpenJDK/IcedTea-Web/commit/5a5a6eb8366db61bbd27f7838e89b85dbb756bdf#diff-a51468134d75a21d097fb81b01056ded57a485b517485469fc91ea8d031b3234

The 81 or 82 seems to correspond to the number of `<jar/>` and `<nativelib/>` entities in the `.jnlp` file.

I wonder what this `"\\"` code path is for. Is it meant for running Web Start applications from local `file:` URLs on Windows or something? Surely in that case `/` works in `java.net.URL`...?
