### ISSUE TITLE
IcedTea wants to load non-existing classes and apps not working correctly without console option enabled

### ISSUE THREAD

**Issue by ghost** [AdoptOpenJDK/IcedTea-Web#246]
Hello.
I'm experiencing strange issue with IcedTea-Web during launching our apps using it.
Using Oracle Web Start everything is fine, but on IcedTea-Web application failing when trying to get resources from classpath. According to log in the console, for some reason IcedTea is cleaning the classpath property in manifest. That's why our apps not working correctly any more :(

Sample jnlp:
```
<?xml version="1.0" encoding="utf-8"?>
<jnlp spec="6.0+" codebase="http://website/App-2.2.681/" href="jnlp.jnlp">
  <information>
    <title>Title</title>
    <vendor>Vendor</vendor>
    <homepage href="http://www.homepage.com/" />
    <description></description>
  </information>
  <security>
     <all-permissions/>
  </security>
  <resources>
    <j2se version="1.6+"/>
    <jar href="App-2.2.681.jar" main="true"/>
    <jar href="Framework-2.2.674.jar"/>
    <jar href="WebServices-2.2.62.jar"/>
    <jar href="axis-1.4.jar"/>
    <jar href="axis-jaxrpc-1.4.jar"/>
    <jar href="log4j-1.2.14.jar"/>
    <jar href="spring-2.5.5.jar"/>
    <jar href="commons-net-2.0.jar"/>
    <jar href="nanoxml-2.2.3.jar"/>
    <jar href="jtds-1.2.2.jar"/>
    <jar href="commons-discovery-0.4.jar"/>
    <jar href="wsdl4j-1.6.2.jar"/>
    <jar href="rxtx-2.1.7.jar"/>
    <jar href="jamod-1.2.jar"/>
    <jar href="json-lib-2.4-jdk15.jar"/>
    <jar href="commons-beanutils-1.8.0.jar"/>
    <jar href="commons-collections-3.2.1.jar"/>
    <jar href="commons-lang-2.5.jar"/>
    <jar href="ezmorph-1.0.6.jar"/>
    <jar href="commons-httpclient-3.1.jar"/>
    <jar href="commons-codec-1.2.jar"/>
    <jar href="httpclient-4.0.3.jar"/>
    <jar href="jsch-0.1.45.jar"/>
    <jar href="core-3.2.0.jar"/>
    <jar href="javase-3.2.0.jar"/>
    <jar href="controlsfx-8.40.14.jar"/>
    <jar href="jssc-2.8.0.jar"/>
    <jar href="htmlunit-2.33.jar"/>
    <jar href="slf4j-api-1.7.25.jar"/>
    <jar href="slf4j-jdk14-1.7.25.jar"/>
    <jar href="zt-zip-1.13.jar"/>
  </resources>
  <application-desc main-class="com.company.App">
    <argument>-wctStation</argument> <argument>App</argument> <argument>-noProdOrder</argument> <argument>-productFile</argument> <argument>product.properties</argument> <argument>-propertyFile</argument> <argument>app_country.properties</argument> <argument>-disableCommandCheckboxes</argument> <argument>-createModule</argument> <argument>-comConnection</argument>
  </application-desc>
</jnlp>
```

Class-Path:
```
Class-Path: Framework-2.2.671.jar WebServices-2.2.62.jar axis-1.4.jar 
 axis-jaxrpc-1.4.jar log4j-1.2.14.jar spring-2.5.5.jar commons-logging
 -1.1.1.jar commons-net-2.0.jar nanoxml-2.2.3.jar jtds-1.2.2.jar commo
 ns-discovery-0.4.jar wsdl4j-1.6.2.jar rxtx-2.1.7.jar jamod-1.2.jar js
 on-lib-2.4-jdk15.jar commons-beanutils-1.8.0.jar commons-collections-
 3.2.1.jar commons-lang-2.5.jar ezmorph-1.0.6.jar commons-httpclient-3
 .1.jar commons-codec-1.2.jar httpclient-4.0.3.jar jsch-0.1.45.jar cor
 e-3.2.0.jar javase-3.2.0.jar controlsfx-8.40.14.jar jssc-2.8.0.jar ht
 mlunit-2.33.jar slf4j-api-1.7.25.jar slf4j-jdk14-1.7.25.jar zt-zip-1.
 13.jar
```

Sample stacktrace (packages were renamed a bit):

```
java.lang.ClassNotFoundException: com.company.app.CheckAppleMFiChipBeanInfo     
at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClassExt(JNLPClassLoader.java:1798)     
at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClass(JNLPClassLoader.java:1598)     
at java.lang.Class.forName0(Native Method)     
at java.lang.Class.forName(Class.java:348)     
at com.sun.beans.finder.ClassFinder.findClass(ClassFinder.java:67)     
at com.sun.beans.finder.ClassFinder.findClass(ClassFinder.java:110)     
at com.sun.beans.finder.InstanceFinder.instantiate(InstanceFinder.java:93)     
at com.sun.beans.finder.InstanceFinder.find(InstanceFinder.java:66)     
at java.beans.Introspector.findExplicitBeanInfo(Introspector.java:448)     
at java.beans.Introspector.<init>(Introspector.java:398)     
at java.beans.Introspector.getBeanInfo(Introspector.java:173)     
at org.springframework.beans.CachedIntrospectionResults.<init>(CachedIntrospectionResults.java:279)     
at org.springframework.beans.CachedIntrospectionResults.forClass(CachedIntrospectionResults.java:189)     
at org.springframework.beans.BeanWrapperImpl.getCachedIntrospectionResults(BeanWrapperImpl.java:173)     
at org.springframework.beans.BeanWrapperImpl.getLocalPropertyHandler(BeanWrapperImpl.java:226)     
at org.springframework.beans.BeanWrapperImpl.getLocalPropertyHandler(BeanWrapperImpl.java:63)     
at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyHandler(AbstractNestablePropertyAccessor.java:737)     
at org.springframework.beans.AbstractNestablePropertyAccessor.isWritableProperty(AbstractNestablePropertyAccessor.java:569)     
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1535)     
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1280)     
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)     
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)     
at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)     
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)     
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)     
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:756)
at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
at com.company.framework.FrameworkSequenceFactory.getCommandSequenceNamesFromClassPath(FrameworkSequenceFactory.java:66)
at com.company.application.CommandConfigurationProvider.loadCommandSequenceNames(CommandConfigurationProvider.java:287)
at com.company.application.gui.CommandConfigurationController.loadCommands(CommandConfigurationController.java:161)
at com.company.application.gui.CommandConfigurationController.reportProviderEvent(CommandConfigurationController.java:256)
at com.company.application.CommandConfigurationProvider.lambda$null$0(CommandConfigurationProvider.java:343)
at java.lang.Thread.run(Thread.java:748)
```

It happens because we are using Spring ApplicationContext and loading xml file using classpath.
If classpath is broken - problem with loading. 

Sample location of .xml file: app.jar!/commands/test/applicationContext.xml
Following method is used to get xml file:
```
public static String[] getCommandSequenceNamesFromClassPath(String configFileName) {
    ApplicationContext context = new ClassPathXmlApplicationContext(configFileName);
    return context.getBeanNamesForType(CommandSequence.class);
}
```
Interesting thing, that if IcedTea-Web console is enabled, I see this kind of errors but everything is still working. If I disable console, I receive an exception that ApplicationContext file could not be found because it's not exist.

Is this expected? Is there any way to disable classpath cleaning?

**Comment by ExtaX** [comment]
https://stackoverflow.com/questions/55551937/icedtea-web-start-wants-to-load-non-existing-classes-ending-with-beaninfo-or
Same problem from Stackoverflow

**Comment by karianna** [comment]
version of ITW?

**Comment by ExtaX** [comment]
1.8

**Comment by sclassen** [comment]
Just to be sure:
the `Class-Path: Framework-2.2.671.jar WebServices-2.2.62.jar ...` in you question is from a MANIFEST.FM file? In which jar is this manifest? `App-2.2.681.jar`

What I see just by reading the ticket is that the versions in the Manifest are different to the versions in the jnlp (for example `Framework-2.2.674.jar` vs `Framework-2.2.671.jar`)

**Comment by ExtaX** [comment]
@sclassen 
Sorry for confusion. I took the class-path part from another application version jar.
Regards the manifest - you are totally right!
So, it's not related to versions mismatch.

Once again, sorry.

**Comment by Jamila891** [comment]
Hi @ExtaX, can we close this issue?
