### ISSUE TITLE
SLF4J library conflict between ITW and JNLP application

### ISSUE THREAD

**Issue by bourgesl** [AdoptOpenJDK/IcedTea-Web#264]
Since ITW embeds slf4j+simple log libraries in the boot classpath, it causes a classloader issue: slf4j factory initializes the SimpleLogger.
In my JNLP application, it embeds slf4j+logback with custom configuration files. 
As slf4j is used by ITW, LoggerFactory is started early and my application fails at startup since slf4j Logger are not logback's Logger instances.

Maybe ITW slf4j libs should use an alternate java package, to have 2 separate slf4j libs running within the JVM: 
- 1 in boot class loader  under org.itw... 
- and 1 in application class loader

**Comment by bourgesl** [comment]
Mvn shade plugin allows dependency / package relocation into another package:
https://maven.apache.org/plugins/maven-shade-plugin/examples/class-relocation.html
I will try making an itw-deps.jar containing all mvn dependencies relocated in org.icedteaweb umbrella (base package).

**Comment by bourgesl** [comment]
Related to #129

**Comment by bourgesl** [comment]
Here is the exception happening at application startup:

```
[Aspro 2] INFO net.sourceforge.jnlp.Launcher - Starting application [fr.jmmc.aspro.Aspro2] ...
[Aspro 2] INFO net.sourceforge.jnlp.Launcher - Invoking main() with args: []
[Aspro 2] ERROR net.sourceforge.jnlp.Launcher - ERROR
java.lang.ExceptionInInitializerError
at fr.jmmc.jmcs.App.<clinit>(App.java:67)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:582)
at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:951)
Caused by: java.lang.ClassCastException: org.slf4j.impl.SimpleLogger cannot be cast to ch.qos.logback.classic.Logger
at fr.jmmc.jmcs.logging.LoggingService.getJmmcLogger(LoggingService.java:88)
at fr.jmmc.jmcs.Bootstrapper.<clinit>(Bootstrapper.java:80)
... 7 more
Exception in thread "Aspro 2" java.lang.RuntimeException: java.lang.ExceptionInInitializerError
at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:974)
Caused by: java.lang.ExceptionInInitializerError
at fr.jmmc.jmcs.App.<clinit>(App.java:67)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:582)
at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:951)
Caused by: java.lang.ClassCastException: org.slf4j.impl.SimpleLogger cannot be cast to ch.qos.logback.classic.Logger
at fr.jmmc.jmcs.logging.LoggingService.getJmmcLogger(LoggingService.java:88)
at fr.jmmc.jmcs.Bootstrapper.<clinit>(Bootstrapper.java:80)
... 7 more
```

**Comment by hendrikebbers** [comment]
I ask myself if starting the JNLP application in the same Java process as ITW is a good idea. At least with Java 11 and JLink this will become were hard to handle.

In general I think that ITW should start a new process for each application (by calling the java executable internally).

**Comment by bourgesl** [comment]
Interesting. 
However JNLP application may need some JNLP services and/or run in a sandbox (permissions) so some jnlp bootstrapping will remain necessary to ensure proper isolation and security dialogs I think.

**Comment by sclassen** [comment]
Yes you are absolutely right. ITW will always be on the classpath and we need to make sure that no library hell gets created by that fact

**Comment by hendrikebbers** [comment]
Discussed that with @sclassen 
As a fast fix we will copy the SLF4J interface to ITW (same methods, different package / name).
Later we will introduce a better Classloader mechanism that splits ITW relevant code and application code.

**Comment by bourgesl** [comment]
Hi I tested latest code and it almost works:
You added itw logging API but left slf4j libs in the classpath (shell and rust launchers).

I hacked javaws.sh to get rid of them and ITW works well with my ASPRO2 app !

I suppose such launcher cleanup is planned soon
