### ISSUE TITLE
Problem with --nosecurity parameter

### ISSUE THREAD

**Issue by daddyaddy** [AdoptOpenJDK/IcedTea-Web#315]
When we execute this command:
`javaws --nosecurity file.jnlp`
our application is properly started.

We want to execute the same javaws command **without --nosecurity parameter** and we get the following error:

```
Bartłomiej Brodawka, [08.07.19 13:52]
C:\Program Files\OpenWebStart>
[bartlomiej.brodawka][ITW-APPLET][MESSAGE_DEBUG][Mon Jul 08 13:43:39 CEST 2019][net.sourceforge.jnlp.runtime.JNLPRuntime] NETX Thread# 3fb4f649, name main Forcing of offline set to: false
[bartlomiej.brodawka][ITW-APPLET][MESSAGE_ALL][Mon Jul 08 13:43:40 CEST 2019][net.sourceforge.jnlp.config.DeploymentConfiguration] NETX Thread# 3fb4f649, name main Ico provider registered correctly.
[bartlomiej.brodawka][ITW-APPLET][MESSAGE_ALL][Mon Jul 08 13:43:40 CEST 2019][net.sourceforge.jnlp.config.DeploymentConfiguration] NETX Thread# 3fb4f649, name main Loading USER level properties from: file:/C:/Users/bartlomiej.brodawka/.config/icedtea-web/deployment.properties
[bartlomiej.brodawka][ITW-JAVAWS][MESSAGE_DEBUG][Mon Jul 08 13:43:40 CEST 2019][net.sourceforge.jnlp.util.logging.FileLog] NETX Thread# ce11f13, name Output controller consumer daemon Attempting to log into: C:\Users\bartlomiej.brodawka\.config\icedtea-web\log\itw-javantx-2019-07-08_13_43_40.56.log
Exception in thread "main" java.lang.StackOverflowError
        at net.sourceforge.jnlp.runtime.JNLPPolicy.implies(JNLPPolicy.java:237)
        at java.security.ProtectionDomain.implies(Unknown Source)
        at java.security.AccessControlContext.checkPermission(Unknown Source)
        at java.security.AccessController.checkPermission(Unknown Source)
        at java.lang.SecurityManager.checkPermission(Unknown Source)
        at net.sourceforge.jnlp.runtime.JNLPSecurityManager.checkPermission(JNLPSecurityManager.java:292)
        at java.lang.ClassLoader.checkClassLoaderPermission(Unknown Source)
        at java.lang.ClassLoader.getParent(Unknown Source)
        at net.sourceforge.jnlp.runtime.JNLPSecurityManager.getApplication(JNLPSecurityManager.java:206)
        at net.sourceforge.jnlp.runtime.JNLPSecurityManager.getApplication(JNLPSecurityManager.java:170)
        at net.sourceforge.jnlp.runtime.JNLPRuntime.getApplication(JNLPRuntime.java:621)
        at net.sourceforge.jnlp.runtime.JNLPPolicy.getPermissions(JNLPPolicy.java:109)
        at net.sourceforge.jnlp.runtime.JNLPPolicy.implies(JNLPPolicy.java:237)
        at java.security.ProtectionDomain.implies(Unknown Source)
        at java.security.AccessControlContext.checkPermission(Unknown Source)
        at java.security.AccessController.checkPermission(Unknown Source)
        at java.lang.SecurityManager.checkPermission(Unknown Source)
        at net.sourceforge.jnlp.runtime.JNLPSecurityManager.checkPermission(JNLPSecurityManager.java:292)
        at java.lang.ClassLoader.checkClassLoaderPermission(Unknown Source)
        at java.lang.ClassLoader.getParent(Unknown Source)
        at net.sourceforge.jnlp.runtime.JNLPSecurityManager.getApplication(JNLPSecurityManager.java:206)
        at net.sourceforge.jnlp.runtime.JNLPSecurityManager.getApplication(JNLPSecurityManager.java:170)
        at net.sourceforge.jnlp.runtime.JNLPRuntime.getApplication(JNLPRuntime.java:621)
        at net.sourceforge.jnlp.runtime.JNLPPolicy.getPermissions(JNLPPolicy.java:109)
        at net.sourceforge.jnlp.runtime.JNLPPolicy.implies(JNLPPolicy.java:237)
        at java.security.ProtectionDomain.implies(Unknown Source)
        at java.security.AccessControlContext.checkPermission(Unknown Source)
        at java.security.AccessController.checkPermission(Unknown Source)
        at java.lang.SecurityManager.checkPermission(Unknown Source)
        at net.sourceforge.jnlp.runtime.JNLPSecurityManager.checkPermission(JNLPSecurityManager.java:292)
        at java.lang.ClassLoader.checkClassLoaderPermission(Unknown Source)
        at java.lang.ClassLoader.getParent(Unknown Source)
        at net.sourceforge.jnlp.runtime.JNLPSecurityManager.getApplication(JNLPSecurityManager.java:206)
        at net.sourceforge.jnlp.runtime.JNLPSecurityManager.getApplication(JNLPSecurityManager.java:170)
        at net.sourceforge.jnlp.runtime.JNLPRuntime.getApplication(JNLPRuntime.java:621)
        at net.sourceforge.jnlp.runtime.JNLPPolicy.getPermissions(JNLPPolicy.java:109)

Bartłomiej Brodawka, [08.07.19 13:52]
at net.sourceforge.jnlp.runtime.JNLPPolicy.implies(JNLPPolicy.java:237)
        at java.security.ProtectionDomain.implies(Unknown Source)
        at java.security.AccessControlContext.checkPermission(Unknown Source)
        at java.security.AccessController.checkPermission(Unknown Source)
        at java.lang.SecurityManager.checkPermission(Unknown Source)
        at net.sourceforge.jnlp.runtime.JNLPSecurityManager.checkPermission(JNLPSecurityManager.java:292)
        at java.lang.ClassLoader.checkClassLoaderPermission(Unknown Source)
        at java.lang.ClassLoader.getParent(Unknown Source)
        at net.sourceforge.jnlp.runtime.JNLPSecurityManager.getApplication(JNLPSecurityManager.java:206)
        at net.sourceforge.jnlp.runtime.JNLPSecurityManager.getApplication(JNLPSecurityManager.java:170)
        at net.sourceforge.jnlp.runtime.JNLPRuntime.getApplication(JNLPRuntime.java:621)
        at net.sourceforge.jnlp.runtime.JNLPPolicy.getPermissions(JNLPPolicy.java:109)
        at net.sourceforge.jnlp.runtime.JNLPPolicy.implies(JNLPPolicy.java:237)
        at java.security.ProtectionDomain.implies(Unknown Source)
        at java.security.AccessControlContext.checkPermission(Unknown Source)
        at java.security.AccessController.checkPermission(Unknown Source)
        at java.lang.SecurityManager.checkPermission(Unknown Source)
        at net.sourceforge.jnlp.runtime.JNLPSecurityManager.checkPermission(JNLPSecurityManager.java:292)
        at java.lang.ClassLoader.checkClassLoaderPermission(Unknown Source)
        at java.lang.ClassLoader.getParent(Unknown Source)
        at net.sourceforge.jnlp.runtime.JNLPSecurityManager.getApplication(JNLPSecurityManager.java:206)
        at net.sourceforge.jnlp.runtime.JNLPSecurityManager.getApplication(JNLPSecurityManager.java:170)
        at net.sourceforge.jnlp.runtime.JNLPRuntime.getApplication(JNLPRuntime.java:621)
        at net.sourceforge.jnlp.runtime.JNLPPolicy.getPermissions(JNLPPolicy.java:109)
        at net.sourceforge.jnlp.runtime.JNLPPolicy.implies(JNLPPolicy.java:237)
        at java.security.ProtectionDomain.implies(Unknown Source)
        at java.security.AccessControlContext.checkPermission(Unknown Source)
        at java.security.AccessController.checkPermission(Unknown Source)
        at java.lang.SecurityManager.checkPermission(Unknown Source)
        at net.sourceforge.jnlp.runtime.JNLPSecurityManager.checkPermission(JNLPSecurityManager.java:292)
        at java.lang.ClassLoader.checkClassLoaderPermission(Unknown Source)
        at java.lang.ClassLoader.getParent(Unknown Source)
```

**Comment by hendrikebbers** [comment]
We are currently working on the StackOverflow and plan to have a fix in near future. Until than --nosecurity must be added as a parameter.

**Comment by daddyaddy** [comment]
How to pass `--nosecurity` parameter automatically from browser?

**Comment by Jamila891** [comment]
Hi @daddyaddy, does this error still happens after the last release?
