### ISSUE TITLE
Unknown problem with javaws command

### ISSUE THREAD

**Issue by daddyaddy** [AdoptOpenJDK/IcedTea-Web#317]
When we trying run this command:
`javaws -nosecurity -Xnofork https://localhost/clininet-applethost/simpleApplets/launch.jnlp?instanceId=t1562677903464_r93^&codeBase=https://localhost/clininet-applethost/simpleApplets -console`

We get this message in console:
```
Bartłomiej Brodawka, [09.07.19 15:35]
[bartlomiej.brodawka][ITW-JAVAWS][MESSAGE_DEBUG][Tue Jul 09 15:22:10 CEST 2019][net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialog] NETX Thread# 4ec6a292, name AWT-EventQueue-0 Setting value: null
[bartlomiej.brodawka][ITW-JAVAWS][MESSAGE_DEBUG][Tue Jul 09 15:22:27 CEST 2019][net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialog] NETX Thread# 4ec6a292, name AWT-EventQueue-0 Setting value: YES
[bartlomiej.brodawka][ITW-JAVAWS][MESSAGE_DEBUG][Tue Jul 09 15:22:27 CEST 2019][net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialog] NETX Thread# 4ec6a292, name AWT-EventQueue-0 Returning value: YES
[bartlomiej.brodawka][ITW-JAVAWS][MESSAGE_DEBUG][Tue Jul 09 15:22:27 CEST 2019][net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialog] NETX Thread# 4ec6a292, name AWT-EventQueue-0 Returning value: YES
[bartlomiej.brodawka][ITW-JAVAWS][MESSAGE_DEBUG][Tue Jul 09 15:22:27 CEST 2019][net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialog] NETX Thread# 4ec6a292, name AWT-EventQueue-0 Returning value: YES
[bartlomiej.brodawka][ITW-JAVAWS][MESSAGE_DEBUG][Tue Jul 09 15:22:27 CEST 2019][net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialog] NETX Thread# 4ec6a292, name AWT-EventQueue-0 Returning value: YES
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.appletextendedsecurity.UnsignedAppletTrustConfirmation.updateAppletAction(UnsignedAppletTrustConfirmation.java:156)[bartlomiej.brodawka][ITW-JAVAWS][MESSAGE_DEBUG][Tue
Jul 09 15:22:27 CEST 2019][net.sourceforge.jnlp.util.logging.FileLog] NETX Thread# 4dddc8b3, name Output controller consumer daemon Attempting to log into: C:\Users\bartlomiej.brodawka\.config\icedtea-web\log\itw-clienta-2019-07-09_15_22
_27.117.log

        at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.remember.RememberDialog.setOrUpdateRememberedState(RememberDialog.java:70)
        at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.remember.RememberDialog.setOrUpdateRememberedState(RememberDialog.java:59)
        at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogMessageHandler$1.actionPerformed(SecurityDialogMessageHandler.java:168)
        at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.ViwableDialog.notifySelectionMade(ViwableDialog.java:144)
        at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.ViwableDialog.dispose(ViwableDialog.java:128)
        at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SetValueHandler.actionPerformed(SetValueHandler.java:75)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
        at java.awt.Component.processMouseEvent(Component.java:6539)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6304)
        at java.awt.Container.processEvent(Container.java:2239)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
        at java.awt.Container.dispatchEventImpl(Container.java:2283)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)

Bartłomiej Brodawka, [09.07.19 15:35]
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
        at java.awt.EventQueue$4.run(EventQueue.java:733)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

![photo_2019-07-09_15-24-57](https://user-images.githubusercontent.com/44926230/60892717-e4755b80-a25f-11e9-82bf-ec731954e110.jpg)

`Application "..." from "..." there is a lack of attribute "permissions". Appliications without this attribute should not be trusted. Can you allow to run this application?`

**Comment by Brodzio** [comment]
After debiting, it turned out that after the above message appeared and clicked on YES,
in the `UnsignedAppletTrustConfirmation` class in the line:

` documentbase = UrlUtils.normalizeUrlAndStripParams (file.getSourceLocation (), true / * encode local files * /);`

`file.getSourceLocation ()` is null

And what follows documentbase also equals null.
What results in NPE in the line:

`documentbaseRegex = UrlRegEx.quote (documentbase.toExternalForm ()); // Match only this applet`

Why is SourceLocation null?
Is the JNLP file affected?

**Comment by judovana** [comment]
Maybe it is  duplicate of https://github.com/AdoptOpenJDK/IcedTea-Web/issues/372 ? Can you try with release very old release of http://icedtea.wildebeest.org/download/icedtea-web-binaries/1.8/ please?

**Comment by Jamila891** [comment]
@daddyaddy Can we close this issue?
