### ISSUE TITLE
ITWebstart fails with SAP PI Tools

### ISSUE THREAD

**Issue by tdrebens** [AdoptOpenJDK/IcedTea-Web#318]
Hi,

we tried to run PI Tools (directory. and repository) with Adoptopenjdk 1.8.0_212 and Iced tea Web 1.8.1 on a Windows 10 and Server 2016 (x64). 

Seems that the Jar Files are not downloaded (0 Byte). Downloading within browser from the same Maschine works.
Other jnlps are working fine.

isCurrent: http://sapwd00bob.enbw.net:8100/dir/directory/w3c_http.jar = true
isCurrent:lastModified cache:1523617950000 actual:1523617950000
java.util.zip.ZipException: zip file is empty     at java.util.zip.ZipFile.open(Native Method)     at java.util.zip.ZipFile.<init>(ZipFile.java:225)     at java.util.zip.ZipFile.<init>(ZipFile.java:155)     at java.util.jar.JarFile.<init>(JarFile.java:166)     at java.util.jar.JarFile.<init>(JarFile.java:117)     at net.sourceforge.jnlp.util.JarFile.<init>(JarFile.java:60)     at net.sourceforge.jnlp.tools.JarCertVerifier.verifyJar(JarCertVerifier.java:275)     at net.sourceforge.jnlp.tools.JarCertVerifier.verifyJars(JarCertVerifier.java:245)     at net.sourceforge.jnlp.tools.JarCertVerifier.add(JarCertVerifier.java:211)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:732)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.<init>(JNLPClassLoader.java:338)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:421)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:495)     at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:468)     at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:814)     at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:531)     at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:945) 
isCurrent:isCached true
isCached: remote:-1 cached:0

regards
TD

**Comment by mEkdal** [comment]
We had the same problems with 1.8.2. 
All jar files in the cache is empty. Both with 1.8.1 and 1.8.2. Works fins with 1.8.0.

**Comment by tdrebens** [comment]
The portable Version of 1.8 is also not working but this one : http://icedtea.wildebeest.org/download/icedtea-web-binaries/1.8/windows/
Thx for your response.

**Comment by judovana** [comment]
@gdams  hi Gorge. How are itw releases built and tested?

**Comment by judovana** [comment]
@tdrebens  how 1.8.2? How self built ITW?

**Comment by gdams** [comment]
@judovana they are built at https://ci.adoptopenjdk.net/view/IcedTea-Web/

**Comment by mEkdal** [comment]
Same problem in 1.8.3. The SAP PI Tools are not broke since 1.8.1.
1.8.0 is still working though, using AdoptOpenJDK JDK64 1.8.0_222.

**Comment by septpadm** [comment]
icedtea-web-1.8.4 isn't working either :-( 

The icedtea-web-1.8.0 version is working fine, newer versions are not.

**Comment by hendrikebbers** [comment]
Is a JNLP app available online to check the behaviour?

**Comment by septpadm** [comment]
Yes, I can run it from my company PC.

**Comment by septpadm** [comment]
Well, not online but I can share my screen in a meeting.

**Comment by hendrikebbers** [comment]
Can you check the [2.0.0-alpha14](https://github.com/AdoptOpenJDK/IcedTea-Web/releases/tag/icedtea-web-2.0.0-alpha14) tag?

**Comment by septpadm** [comment]
No, couldn’t make it work.

I’m not familiar with ./configure, make and that stuff but I tried to make it work in bash started from my Win10 but never got longer than ./configure missing ☹.
I imported into my Eclipse and most of the .java files compiled.

But the file structure wasn’t at all like 1.8.4 and the rest. A lot of files and folders were missing.
Usually I download a zip file intended for Windows, extract it and it works (1.8.0) or not (newer versions).

BR
Michael Ekdal

**Comment by hendrikebbers** [comment]
the master branch (and all 2.x releases) are based on maven as build tool. are you familiar with maven?

**Comment by septpadm** [comment]
Nope

**Comment by hendrikebbers** [comment]
Ok, maybe you can test https://github.com/karakun/OpenWebStart ? It depends on the new IcedTeaWeb version. By testing with OWS we know if the issue is still present.

**Comment by septpadm** [comment]
https://github.com/karakun/OpenWebStart<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkarakun%2FOpenWebStart&data=02%7C01%7Cmichael.ekdal%40perstorp.com%7Cf4fea9e4772145d6ccdf08d82fa64f1f%7Cff093d1f75de49f6b91b8bf6945505af%7C0%7C0%7C637311738635097843&sdata=wK%2FFFOqXUrhgsy6bGGc5ivhooTT3VPeWD%2FHgDZuHJAY%3D&reserved=0> seems to work better but not completely.

The app downloaded and almost started.
I have tried a couple of times and gets the same result.

I found a icedtea-web folder in C:\Users\septpadm\.cache and C:\Users\septpadm\.config which I deleted between the tries.

I have not found the logs yet, though.

Lunch now and then I work a couple of hours more before I’m of to my vacation.

[cid:image001.png@01D661B8.78CD8560]

**Comment by sclassen** [comment]
See https://github.com/karakun/OpenWebStart/blob/master/documentation/guide/OWSGuide.adoc#logging for how to enable logging

**Comment by septpadm** [comment]
Here are the logs.

**Comment by hendrikebbers** [comment]
@septpadm can you please add the message directly in GitHub. You attachment is not added to the message

**Comment by Jamila891** [comment]
@tdrebens Is this problem still here? If yes, please provide us with the log files.

**Comment by septpadm** [comment]
@Jamila891 The problem remains in Perstorp and I uploaded my logs to @hendrikebbers when I did some testing earlier this sommer. I will try upload the logs again now.
[itw-javantx-2020-07-24_13_29_32.904.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/5255336/itw-javantx-2020-07-24_13_29_32.904.log)
[itw-clienta-2020-07-24_13_29_38.459.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/5255337/itw-clienta-2020-07-24_13_29_38.459.log)

**Comment by sclassen** [comment]
From your logs:
```
About to launch external with commands: '[C:\Users\septpadm\.cache\icedtea-web\jvm-cache\azul_11.0.7\bin\java.exe,
```
and

```
Caused by: java.lang.ClassNotFoundException: javax.rmi.CORBA.Stub
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.lambda$loadClass$9(JNLPClassLoader.java:1432)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.loadClass(JNLPClassLoader.java:1432)
	... 47 more
```

Corba has been removed from Java 11. So you would need to specify a Java/j2se version of `1.8.*` in the JNLP to make sure that a java 1.8 is used
