### ISSUE TITLE
Launch Error: Could not launch JNLP file - access denied

### ISSUE THREAD

**Issue by feysal07** [AdoptOpenJDK/IcedTea-Web#324]
Hi,

I've installed Redhat OpenJDK 8 with Iced-tea webstart and trying to launch my app through browser and I'm getting the following errors:

Starting Netx, command: ["C:/Tools/openjdk8redhat/jre/webstart/../bin/java.exe" -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:+UseSerialGC -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -splash:"C:/Tools/openjdk8redhat/jre/webstart/javaws_splash.png" -Xbootclasspath/a:"C:/Tools/openjdk8redhat/jre/webstart/javaws.jar" -classpath "C:/Tools/openjdk8redhat/jre/webstart/../jre/lib/rt.jar" -Ditw.userdata="C:/Users/fay/AppData/Local/RedHat/java-1.8.0-openjdk-1.8.0.212-3.b04.redhat.windows.x86_64/webstart/" -Dicedtea-web.bin.name=javaws.exe -Dicedtea-web.bin.location="C:/Tools/openjdk8redhat/jre/webstart/javaws.exe" net.sourceforge.jnlp.runtime.Boot -Xnofork -helpurl="https://access.redhat.com/documentation/en-us/openjdk/8/html/openjdk_8_for_windows_getting_started_guide/webstart" jnlp:http://ipension-int-ch.elca-services.com/webstart/ipension-rfm.jnlp]
Warning - your JRE - 1.8.0_212-3-redhat - does not match requested JRE - 1.8
Warning - your JRE - 1.8.0_212-3-redhat - does not match requested JRE - 1.8
The application is a local file. Codebase validation is disabled. See: http://docs.oracle.com/javase/7/docs/technotes/guides/jweb/security/no_redeploy.html for details.
The application is a local file. Codebase validation is disabled. See: http://docs.oracle.com/javase/7/docs/technotes/guides/jweb/security/no_redeploy.html for details.
Starting application [xxxx] ...
netx: Launch Error: Could not launch JNLP file. ( (access denied ("java.lang.RuntimePermission" "getClassLoader")))
net.sourceforge.jnlp.LaunchException: Fatal: Launch Error: Could not launch JNLP file. The application has not been initialized, for more information execute javaws/browser from the command line and send a bug report.
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:582)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:945)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:576)
	... 1 more
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "getClassLoader")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at net.sourceforge.jnlp.runtime.JNLPSecurityManager.checkPermission(JNLPSecurityManager.java:292)
	at java.lang.ClassLoader.checkClassLoaderPermission(ClassLoader.java:1528)
	at java.lang.Thread.getContextClassLoader(Thread.java:1443)

Please have a look. 
Thanks

**Comment by karianna** [comment]
Which version of ITW are you using?

**Comment by feysal07** [comment]
Version 1.8

**Comment by karianna** [comment]
have you tried 1.8.2 from AdoptOpenJDK?

**Comment by feysal07** [comment]
Not yet, will try it and let you know.
Thanks

**Comment by feysal07** [comment]
Worked well with v1.8.2, thanks

**Comment by mauromol** [comment]
Had the same problem with the 1.8 version bundled in Ubuntu 20.04. Fixed by downloading 1.8.4 version from AdoptOpenJDK.
I opened a launchpad bug requesting the update of the Ubuntu package: https://bugs.launchpad.net/ubuntu/+source/icedtea-web/+bug/1917593
