### ISSUE TITLE
Log4j attempts (and fails) to load missing classes when running under IcedTea-Web

### ISSUE THREAD

**Issue by ibbibby** [AdoptOpenJDK/IcedTea-Web#348]
My company has a web start application that uses Log4j to do its logging, which we are trying to migrate to OpenJDK and IcedTea-Web/OpenWebStart. I have gotten it to work under OpenJDK. However, when I attempt to run it through IcedTea-Web, I get strange ClassNotFoundExceptions in lines that try to instantiate loggers.

For example, there in a class called DirectoryManager, I have the following line, which works fine when running the application through OpenJDK 8:

`public final static Logger logger = LogManager.getLogger(DirectoryManager.class);`

But when when run through IcedTea-Web, the following happens:
```
java.lang.ClassNotFoundException: javax.servlet.Servlet
        at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClassExt(JNLPClassLoader.java:1710)
        at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClass(JNLPClassLoader.java:1510)
        at org.apache.logging.log4j.util.LoaderUtil.loadClass(LoaderUtil.java:163)
        at org.apache.logging.log4j.util.Constants.isClassAvailable(Constants.java:79)
        at org.apache.logging.log4j.util.Constants.<clinit>(Constants.java:30)
        at org.apache.logging.log4j.spi.AbstractLogger.createClassForProperty(AbstractLogger.java:198)
        at org.apache.logging.log4j.spi.AbstractLogger.<clinit>(AbstractLogger.java:88)
        at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:60)
        at com.caci.highview.imaging.client.integrated.util.DirectoryManager.<clinit>(DirectoryManager.java:33)
        at com.caci.highview.imaging.client.integrated.RedactionTool.<clinit>(RedactionTool.java:94)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:455)
        at net.sourceforge.jnlp.Launcher.access$400(Launcher.java:70)
        at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:784)
```
and:
```
java.lang.ClassNotFoundException: com.fasterxml.jackson.dataformat.yaml.YAMLFactory
        at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClassExt(JNLPClassLoader.java:1710)
        at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClass(JNLPClassLoader.java:1510)
        at org.apache.logging.log4j.util.LoaderUtil.loadClass(LoaderUtil.java:163)
        at org.apache.logging.log4j.util.LoaderUtil.isClassAvailable(LoaderUtil.java:139)
        at org.apache.logging.log4j.core.util.Loader.isClassAvailable(Loader.java:310)
        at org.apache.logging.log4j.core.config.yaml.YamlConfigurationFactory.<init>(YamlConfigurationFactory.java:47)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.logging.log4j.core.util.ReflectionUtil.instantiate(ReflectionUtil.java:188)
        at org.apache.logging.log4j.core.config.ConfigurationFactory.addFactory(ConfigurationFactory.java:185)
        at org.apache.logging.log4j.core.config.ConfigurationFactory.getInstance(ConfigurationFactory.java:159)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:613)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:581)
        at com.caci.highview.imaging.client.integrated.util.DirectoryManager.<clinit>(DirectoryManager.java:33)
        at com.caci.highview.imaging.client.integrated.RedactionTool.<clinit>(RedactionTool.java:94)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:455)
        at net.sourceforge.jnlp.Launcher.access$400(Launcher.java:70)
        at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:784)
```
From what I can tell, javax.servlet.Servlet and com.fasterxml.jackson.dataformat.yaml.YAMLFactory are indeed missing, but this is normally not a problem, since Log4j doesn't usually try to load these classes. Something about IcedTea-Web's loading process appears to be causing it to behave strangely.

**Comment by hendrikebbers** [comment]
@ibbibby we did several changes in the related area. Does this problem still exists?

**Comment by ericbfeliu** [comment]
@hendrikebbers  What commit do you believe addresses this problem?

**Comment by ibbibby** [comment]
@hendrikebbers Unfortunately I can't say as my project has shifted to installing the app and launching via custom URL protocols instead of Web Start.

**Comment by agkrishna101** [comment]
Hi All , i am getting below error while runnig an applet program using open web starat and jar are signed with Jar signer pugin. the jar containing org/apache/logging/log4j/util/Constants.class is signed with .p12 certificate and jar was verified

Caused by: java.lang.RuntimeException: Error in verify jar C:\Users\john\.cache\icedtea-web\cache\0\3\external-lib.jar
	at net.sourceforge.jnlp.tools.JarCertVerifier.verifyJar(JarCertVerifier.java:320)
	at net.sourceforge.jnlp.tools.JarCertVerifier.verifyJars(JarCertVerifier.java:262)
	at net.sourceforge.jnlp.tools.JarCertVerifier.add(JarCertVerifier.java:236)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.initializeResources(JNLPClassLoader.java:712)
Caused by: Caused by: java.lang.SecurityException: SHA-384 digest error for org/apache/logging/log4j/util/Constants.class
	at java.base/sun.security.util.ManifestEntryVerifier.verify(ManifestEntryVerifier.java:254)
	at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:248)
	at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:235)
	at java.base/java.util.jar.JarVerifier$VerifierStream.read(JarVerifier.java:453)
	at net.sourceforge.jnlp.tools.JarCertVerifier.verifyJar(JarCertVerifier.java:295)
	... 11 more
