### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException

### ISSUE THREAD

**Issue by matand72** [AdoptOpenJDK/IcedTea-Web#356]
Got the following NPE when press ok (or cancel in the security warning dialog). Using 2.0-snapshot. No further progress after this NPE

![image](https://user-images.githubusercontent.com/53760809/62461364-e3631b80-b784-11e9-9710-55508935be94.png)

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.appletextendedsecurity.UnsignedAppletTrustConfirmation.updateAppletAction(UnsignedAppletTrustConfirmation.java:156)
	at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.remember.RememberDialog.setOrUpdateRememberedState(RememberDialog.java:70)
	at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.remember.RememberDialog.setOrUpdateRememberedState(RememberDialog.java:59)
	at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogMessageHandler$1.actionPerformed(SecurityDialogMessageHandler.java:168)
	at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.ViwableDialog.notifySelectionMade(ViwableDialog.java:144)
	at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.ViwableDialog.dispose(ViwableDialog.java:128)
	at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialog$2.windowClosed(SecurityDialog.java:260)
	at java.awt.AWTEventMulticaster.windowClosed(AWTEventMulticaster.java:360)
	at java.awt.Window.processWindowEvent(Window.java:2057)
	at javax.swing.JDialog.processWindowEvent(JDialog.java:683)
	at java.awt.Window.processEvent(Window.java:2013)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by judovana** [comment]
I I'm encountering this too. It is solid regression against 1.8. HArd to say when  it appeared. I will run biscet on it.

**Comment by Jamila891** [comment]
@matand72 does this still happen or can we close this issue?

**Comment by matand72** [comment]
I haven't used that version since I got the error so I can't tell if it still happens.
