### ISSUE TITLE
Icedtea-Web error with percent Width and/or Height value

### ISSUE THREAD

**Issue by Sam1970** [AdoptOpenJDK/IcedTea-Web#368]
Hi,

Icedtea-Web has problem, if Width or/and Height has percent Value in JNLP File.
For example => width="100%" height="1024"

Error detail:

[net.sourceforge.jnlp.AbstractLaunchHandler.printMessage(AbstractLaunchHandler.java:68)] NETX Thread# 1496d9f, name main: net.sourceforge.jnlp.LaunchException: Fatal: Read error: Could not read the JNLP file or parse the syntax. The file may be downloaded manually and sent as an error report to the IcedTea Web Team.
at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)     
at net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)     
at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)     
at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:270)     
at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)     
at java.security.AccessController.doPrivileged(Native Method)     
at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:210) Caused by: net.sourceforge.jnlp.ParseException: MALFORMED MALFORMED; Invalid applet width.     
at net.sourceforge.jnlp.Parser.getApplet(Parser.java:758)     
at net.sourceforge.jnlp.Parser.getLauncher(Parser.java:718)     
at net.sourceforge.jnlp.JNLPFile.parse(JNLPFile.java:878)     
at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:233)     
at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)     
at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)     
at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)     
at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:453)

Best regars

**Comment by judovana** [comment]
cool bug :) Should beeasy to fix. TY!

**Comment by judovana** [comment]
@Sam1970 are wse speaking about the height/width of applet-desc, of image or generic?

**Comment by Sam1970** [comment]
@judovana,

about applet-desc.
