### ISSUE TITLE
Regression finding found more than bargained for

### ISSUE THREAD

**Issue by jandrlik** [AdoptOpenJDK/IcedTea-Web#388]
Hi,
been working on a script for you to find regressions with. With specific system configuration, I was able to find exact commit, which made explicit codebase declaring necessary. Sadly lost the configured VM and now am not able to launch the sample application even with the explicit codebase on a fresh new VM with latest commits. This I consider a regression and therefore am reporting it.
Script along with sample application is attached to this report.

Regression commit hash: `d9cdb76c3db67ad0506c2546466c298d1e6c2d0e`

Steps to reproduce:
1. Start a fresh Rhel8 VM
2. download script, download tar.gz with sample application and untar it
3. launch a simple http server in untarred directory (I personally used `python2 -SimpleHTTPServer`)
4. install java (used 1.8.0), maven and download slf4j libraries and store them somewhere in your system, script should be able to find them
5. run `mvn clean install` at least once, since it has to download dependecies, so script can find them
6. set up a relative path to your IcedTea-Web repo dir within a script (relative to a script)
7. run a script with 3 arguments two commits between which the regression is expected and a url to application so I used:
 `ad37dfdd69449aff96dff6ad48a7111339de4c93 a6a9faa35b25a8aa9107d4c9bbd92a8745ec47ec http://localhost:8000/HelloWorld.jnlp`

on all the new commits up to the one mentioned above, results in following output:

```ERROR
java.lang.NoSuchMethodException: javax.swing.JPanel.getText()
    at java.lang.Class.getMethod(Class.java:1786)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogPanel.getGetText(SecurityDialogPanel.java:177)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogPanel.traverse(SecurityDialogPanel.java:152)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogPanel.traverse(SecurityDialogPanel.java:132)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogPanel.getText(SecurityDialogPanel.java:113)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialog.getText(SecurityDialog.java:397)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogMessageHandler.processMessageInHeadless(SecurityDialogMessageHandler.java:184)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogMessageHandler.handleMessage(SecurityDialogMessageHandler.java:137)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogMessageHandler.run(SecurityDialogMessageHandler.java:95)
    at java.lang.Thread.run(Thread.java:748)

Wed Aug 28 16:38:27 UTC 2019 [ERROR  ] net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogPanel:
ERROR
java.lang.NoSuchMethodException: javax.swing.JPanel.getText()
    at java.lang.Class.getMethod(Class.java:1786)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogPanel.getGetText(SecurityDialogPanel.java:177)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogPanel.traverse(SecurityDialogPanel.java:152)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogPanel.traverse(SecurityDialogPanel.java:132)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogPanel.getText(SecurityDialogPanel.java:113)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialog.getText(SecurityDialog.java:397)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogMessageHandler.processMessageInHeadless(SecurityDialogMessageHandler.java:184)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogMessageHandler.handleMessage(SecurityDialogMessageHandler.java:137)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogMessageHandler.run(SecurityDialogMessageHandler.java:95)
    at java.lang.Thread.run(Thread.java:748)

Wed Aug 28 16:38:27 UTC 2019 [ERROR  ] net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogPanel:
ERROR
java.lang.NoSuchMethodException: javax.swing.JPanel.getText()
    at java.lang.Class.getMethod(Class.java:1786)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogPanel.getGetText(SecurityDialogPanel.java:177)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogPanel.traverse(SecurityDialogPanel.java:152)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogPanel.traverse(SecurityDialogPanel.java:132)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogPanel.getText(SecurityDialogPanel.java:113)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialog.getText(SecurityDialog.java:397)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogMessageHandler.processMessageInHeadless(SecurityDialogMessageHandler.java:184)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogMessageHandler.handleMessage(SecurityDialogMessageHandler.java:137)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogMessageHandler.run(SecurityDialogMessageHandler.java:95)
    at java.lang.Thread.run(Thread.java:748)

Wed Aug 28 16:38:27 UTC 2019 [ERROR  ] net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogPanel:
ERROR
java.lang.NoSuchMethodException: javax.swing.JPanel.getText()
    at java.lang.Class.getMethod(Class.java:1786)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogPanel.getGetText(SecurityDialogPanel.java:177)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogPanel.traverse(SecurityDialogPanel.java:152)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogPanel.traverse(SecurityDialogPanel.java:132)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogPanel.getText(SecurityDialogPanel.java:113)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialog.getText(SecurityDialog.java:397)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogMessageHandler.processMessageInHeadless(SecurityDialogMessageHandler.java:184)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogMessageHandler.handleMessage(SecurityDialogMessageHandler.java:137)
    at net.adoptopenjdk.icedteaweb.client.parts.dialogs.security.SecurityDialogMessageHandler.run(SecurityDialogMessageHandler.java:95)
    at java.lang.Thread.run(Thread.java:748)
```
note - I know that my script is operating a bit unconventionally. That's because I aimed to find a way for launching all the commits the same way.
[HelloWorld.tar.gz](https://github.com/AdoptOpenJDK/IcedTea-Web/files/3554572/HelloWorld.tar.gz)
[myreproducer.sh.tar.gz](https://github.com/AdoptOpenJDK/IcedTea-Web/files/3554587/myreproducer.sh.tar.gz)

**Comment by jandrlik** [comment]
Ok, I just realized that I'm being a little chaotic, sorry for the spam. I will revisit the problem on more OSes and maybe open it later with more specific and clear conclusions.
