### ISSUE TITLE
Application cannot be started with JDK 13 - AWTSecurityManager was removed

### ISSUE THREAD

**Issue by schelldorfer** [AdoptOpenJDK/IcedTea-Web#437]
Application cannot be started with JDK 13.

It throws exception:
```
Exception in thread "main" java.lang.NoClassDefFoundError: sun/awt/AWTSecurityManager
    at net.sourceforge.jnlp.runtime.JNLPRuntime.initialize(JNLPRuntime.java:268)
    at net.sourceforge.jnlp.runtime.Boot.init(Boot.java:376)
    at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:292)
    at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:76)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
    at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:233)
    at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:118)
```

**AWTSecurityManager was removed in 13, but is used in JNLPSecurityManager.**

_1. extend JNLPSecurityManager from SecurityManager instead of AWTSecurityManager
2. remove method getAppContext() from JNLPSecurityManager_

more info:
http://openjdk.5641.n7.nabble.com/OpenJDK13-deprecation-issue-AWTSecurityManager-was-removed-in-13-tt367345.html#none

**Comment by bourgesl** [comment]
Hi,
Today I patched my icedtea-web 1.8 branch (up-to-date) with the assocated patch https://github.com/AdoptOpenJDK/IcedTea-Web/pull/438 to get rid of the AWTSecurityManager class use.

It makes ITW 1.8 work on OpenJDK 13 to 17, tested on 15, 16, 17 EA.

I wonder if this fix could be backported to the iced-tea-web 1.8 branch to make it available in the coming 1.8.x release (for most linux users) as 2.0.x is still not publicly released.

Thanks,
Laurent

**Comment by sclassen** [comment]
feel free to open a PR against the 1.8 branch

**Comment by bourgesl** [comment]
@sclassen see the pull request https://github.com/AdoptOpenJDK/IcedTea-Web/pull/792
It is the same patch as #438

**Comment by bourgesl** [comment]
Please consider integrating this trivial pull request to let work itw 1.8 with openjdk 13-17ea  ...
