### ISSUE TITLE
Can't run JNLP (gzip-problem?)

### ISSUE THREAD

**Issue by adlerweb** [AdoptOpenJDK/IcedTea-Web#487]
Hello,

I'm having trouble to run some JNLP-files served using a GZIP enabled web-server with IcedTea-Web >=1.8.1. As far as I can tell ZLIB is somehow failing to extract the JNLP. Using a browser the JNLP can be retrived (also using Content-Encoding: gzip) and looks fine. IcedTea-Web 1.8.0 works as expected.

The log below refers to an internal setup. I could locate a JNLP with the same problem at https://z3.tia.com/MHP-FTS/z3.jnlp. The proxy used doesn't make any difference.

Log:
```
Selecting proxy for: https://EXTERNALDOMAIN.com/test.jnlp
Selected proxies: [HTTP @ squid.INTERNALDOMAIN.local/1.2.3.4:1234]
Downloading https://EXTERNALDOMAIN.com/test.jnlp using https://EXTERNALDOMAIN.com/test.jnlp (encoding : gzip)
Downloading file: https://EXTERNALDOMAIN.com/test.jnlp into: C:\Users\adlerweb\.cache\icedtea-web\cache\0\https\EXTERNALDOMAIN.com\test.jnlp
isCached: remote:4707 cached:0
isCurrent:isCached false
Extracting gzip: https://EXTERNALDOMAIN.com/test.jnlp to https://EXTERNALDOMAIN.com/test.jnlp
java.io.EOFException: Unexpected end of ZLIB input stream
        at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
        at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at java.io.FilterInputStream.read(FilterInputStream.java:107)
        at net.sourceforge.jnlp.cache.ResourceDownloader.uncompressGzip(ResourceDownloader.java:488)
        at net.sourceforge.jnlp.cache.ResourceDownloader.downloadGZipFile(ResourceDownloader.java:405)
        at net.sourceforge.jnlp.cache.ResourceDownloader.downloadResource(ResourceDownloader.java:362)
        at net.sourceforge.jnlp.cache.ResourceDownloader.run(ResourceDownloader.java:118)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

netx: Lesefehler: Konnte die JNLP-Datei nicht lesen oder die Syntax analysieren. (java.lang.NullPointerException: name can't be null (name can't be null))
Disconnecting sun.net.www.protocol.https.DelegateHttpsURLConnection:https://EXTERNALDOMAIN.com/test.jnlp
net.sourceforge.jnlp.LaunchException: Fatal: Lesefehler: Konnte die JNLP-Datei nicht lesen oder die Syntax analysieren. Die Datei kann möglicherweise manuell heruntergeladen und als Fehlerbericht an das IcedTea-Web Team gesendet werden.
        at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)
        at net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)
        at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)
        at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:270)
        at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)
        at java.security.AccessController.doPrivileged(Native Method)
        at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:210)
Caused by: java.io.IOException: java.lang.NullPointerException: name can't be null
        at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:318)
        at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:231)
        at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)
        at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)
        at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)
        at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:453)
        ... 6 more
Caused by: java.lang.NullPointerException: name can't be null
        at java.io.FilePermission.init(FilePermission.java:205)
        at java.io.FilePermission.<init>(FilePermission.java:305)
        at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
        at java.io.FileInputStream.<init>(FileInputStream.java:127)
        at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:316)
        ... 11 more
```

**Comment by hendrikebbers** [comment]
Hi @adlerweb 
I just tested the JNLP that is linked in the description with the last version of OpenWebStart (https://openwebstart.com) that is based on IcedTea-Web (tag `icedtea-web-2.0.0-alpha5`). By doing so the application starts (I attached the login dialog). So with the given tag, the master branch of ITW or OpenWebStart the problem should be solved.
<img width="612" alt="login" src="https://user-images.githubusercontent.com/9443847/68390187-0840a380-0165-11ea-91e7-7bbcea25b255.png">
