### ISSUE TITLE
"Launch full settings" in User tab

### ISSUE THREAD

**Issue by gimmidallago** [AdoptOpenJDK/IcedTea-Web#517]
OpenWebStart_linux_0_5_1.deb installed.  Executing "javaws -viewer" from command line and pressing "Launch full settings" button - in User section - I get the following exception.

Exception in thread "AWT-EventQueue-0" java.lang.IllegalStateException: Duplicate title class net.adoptopenjdk.icedteaweb.client.controlpanel.panels.JVMPanel and class com.openwebstart.controlpanel.SimplifiedJvmPanel
	at net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel.lambda$createMainSettingsPanel$5(ControlPanel.java:206)
	at java.util.HashMap.merge(HashMap.java:1254)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:352)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel.createMainSettingsPanel(ControlPanel.java:205)
	at net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel.<init>(ControlPanel.java:92)
	at net.adoptopenjdk.icedteaweb.client.controlpanel.ControlPanel.lambda$main$9(ControlPanel.java:273)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Please guide to resolve this issue.

**Comment by hendrikebbers** [comment]
"javaws -viewer" is not supported in https://github.com/karakun/OpenWebStart and it is not planned to support this feature since OpenWebStart provides a settings executable to open the settings dialog.

**Comment by gimmidallago** [comment]
So, "viewer" option can be removed from the available ones?
Thanks

**Comment by sclassen** [comment]
This issue is not related to icedtea-web and has been addressed in OpenWebStart.
