### ISSUE TITLE
Could not start Webstart App since 1.0.0

### ISSUE THREAD

**Issue by SaschaJostock** [AdoptOpenJDK/IcedTea-Web#548]
Since OpenWebstart 1.0.0 cannot start my WebstartApp.
Faild with NoClassDefFound, with the earlier Version from OpenWebstart start
the app successful. 

![image](https://user-images.githubusercontent.com/6065642/70703699-e50f9380-1cd0-11ea-87b2-b4e8fd7e124c.png)

Console log
[console.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/3955179/console.log)

**Comment by hendrikebbers** [comment]
@SaschaJostock can you attach the JNLP file?

**Comment by SaschaJostock** [comment]
Here is the JNLP-File, as zip archiv



[PGopPresentationApp.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/3955798/PGopPresentationApp.zip)

**Comment by sclassen** [comment]
I find following stacktraces in log:
```
java.lang.ClassNotFoundException: org.apache.log4j.Logger
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.lambda$loadClass$9(JNLPClassLoader.java:1435)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader$$Lambda$148.000000001326C180.get(Unknown Source)
     at java.util.Optional.orElseThrow(Optional.java:290)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClass(JNLPClassLoader.java:1435)
     at java.lang.Class.getFieldsImpl(Native Method)
     at java.lang.Class.getFields(Class.java:1128)
     at com.ibm.tmn.webclient.design.foundation.measure.WcMeasurementProvider.addContainersForGaugesOfOwner(WcMeasurementProvider.java:49)
     at com.ibm.tmn.webclient.design.foundation.measure.WcMeasurementProvider.initialize(WcMeasurementProvider.java:77)
     at com.ibm.tmn.webclient.design.foundation.measure.WcMeasuredComponent.initialize(WcMeasuredComponent.java:35)
     at com.ibm.tmn.webclient.design.foundation.trace.WcTraceManager.initialize(WcTraceManager.java:106)
     at com.ibm.tmn.webclient.design.foundation.component.WcComponentManager.findComponent(WcComponentManager.java:137)
     at com.ibm.tmn.webclient.design.foundation.component.WcComponentManager.findComponent(WcComponentManager.java:154)
     at com.ibm.tmn.webclient.design.foundation.process.WcProcess.loadComponent(WcProcess.java:405)
     at com.ibm.tmn.webclient.design.foundation.process.WcProcess.initialize(WcProcess.java:243)
     at com.ibm.tmn.webclient.design.presentation.foundation.WcGuiProcess.initialize(WcGuiProcess.java:62)
     at com.ibm.tmn.webclient.design.presentation.foundation.WcWebStartGuiProcessStarter.startProcess(WcWebStartGuiProcessStarter.java:54)
     at com.ibm.tmn.webclient.design.presentation.foundation.WcWebStartGuiProcessStarter.main(WcWebStartGuiProcessStarter.java:208)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:411)
     at net.sourceforge.jnlp.Launcher.access$200(Launcher.java:69)
     at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:661)
```

and 

```
java.lang.NullPointerException
     at java.security.Permissions.getPermissionCollection(Permissions.java:240)
     at java.security.Permissions.add(Permissions.java:132)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.getPermissions(JNLPClassLoader.java:1106)
     at java.security.SecureClassLoader.getProtectionDomain(SecureClassLoader.java:206)
     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
     at java.net.URLClassLoader.defineClass(URLClassLoader.java:682)
     at java.net.URLClassLoader.access$400(URLClassLoader.java:89)
     at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1086)
     at java.security.AccessController.doPrivileged(AccessController.java:770)
     at java.net.URLClassLoader.findClass(URLClassLoader.java:589)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.access$1301(JNLPClassLoader.java:114)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.lambda$findClass$12(JNLPClassLoader.java:1580)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader$$Lambda$147.0000000010EE6540.run(Unknown Source)
     at java.security.AccessController.doPrivileged(AccessController.java:770)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.findClass(JNLPClassLoader.java:1579)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClassExt(JNLPClassLoader.java:1611)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClassFromInternalManifestClasspath(JNLPClassLoader.java:1465)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.lambda$loadClass$7(JNLPClassLoader.java:1428)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader$$Lambda$143.000000000FC4D2F0.call(Unknown Source)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader$ExceptionalSupplier.getResultOfCallOrNull(JNLPClassLoader.java:1391)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader$$Lambda$145.0000000012FBEF20.apply(Unknown Source)
     at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
     at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
     at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
     at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:514)
     at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:501)
     at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:487)
     at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
     at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:241)
     at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClass(JNLPClassLoader.java:1434)
     at java.lang.Class.getFieldsImpl(Native Method)
     at java.lang.Class.getFields(Class.java:1128)
     at com.ibm.tmn.webclient.design.foundation.measure.WcMeasurementProvider.addContainersForGaugesOfOwner(WcMeasurementProvider.java:49)
     at com.ibm.tmn.webclient.design.foundation.measure.WcMeasurementProvider.initialize(WcMeasurementProvider.java:77)
     at com.ibm.tmn.webclient.design.foundation.measure.WcMeasuredComponent.initialize(WcMeasuredComponent.java:35)
     at com.ibm.tmn.webclient.design.foundation.trace.WcTraceManager.initialize(WcTraceManager.java:106)
     at com.ibm.tmn.webclient.design.foundation.component.WcComponentManager.findComponent(WcComponentManager.java:137)
     at com.ibm.tmn.webclient.design.foundation.component.WcComponentManager.findComponent(WcComponentManager.java:154)
     at com.ibm.tmn.webclient.design.foundation.process.WcProcess.loadComponent(WcProcess.java:405)
     at com.ibm.tmn.webclient.design.foundation.process.WcProcess.initialize(WcProcess.java:243)
     at com.ibm.tmn.webclient.design.presentation.foundation.WcGuiProcess.initialize(WcGuiProcess.java:62)
     at com.ibm.tmn.webclient.design.presentation.foundation.WcWebStartGuiProcessStarter.startProcess(WcWebStartGuiProcessStarter.java:54)
     at com.ibm.tmn.webclient.design.presentation.foundation.WcWebStartGuiProcessStarter.main(WcWebStartGuiProcessStarter.java:208)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:411)
     at net.sourceforge.jnlp.Launcher.access$200(Launcher.java:69)
     at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:661)
```

**Comment by SaschaJostock** [comment]
Start and run the app with the same jnlp with Version 0.5.1 and 1.0.0 successful. 
I will discuss with the dev team from the app.

**Comment by sclassen** [comment]
We are currently reworking the loading of classes. We will also keep this ticket open to remind us that there is somthing to fix here
