### ISSUE TITLE
IBM BMC Remote Desktop JNLP does not launch due to trailing space in version tag

### ISSUE THREAD

**Issue by loeni-tech** [AdoptOpenJDK/IcedTea-Web#559]
Icedteaweb refuses to start ibm remote control jlnp with the error:

```
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: '1.6+ 1.5+ ' is not a valid version-string according to JSR-56, Appendix A.
	at net.sourceforge.jnlp.JNLPFile.parse(JNLPFile.java:887)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:291)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:273)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:258)
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:297)
	... 17 more
```

the relevant jlnp section is:
```
<resources>
    <j2se version="1.6+ 1.5+ " />
    <jar href="/designs/imm/aessrp/avctIBMViewer__V092815.jar" download="eager" main="true" />
</resources>
```

In my opinion, JSR-56, Appendix A is not crystal clear about trailing spaces. OracleJDK does accept this.
Would it be possible to make the Regex in AdoptOpenJDK/IcedTea-Web/blob/master/common/src/main/java/net/adoptopenjdk/icedteaweb/jnlp/version/JNLPVersionPatterns.java more tolerant about trailing spaces and thus enabling it to start IBM remote control?

**Comment by sclassen** [comment]
@hendrikebbers we can trim the string and remove leading and trailing whitespace
do you see any issue with doing so?

**Comment by hendrikebbers** [comment]
@sclassen sounds good

**Comment by hendrikebbers** [comment]
see https://github.com/AdoptOpenJDK/IcedTea-Web/pull/562
