### ISSUE TITLE
High CPU and memory usage when running application

### ISSUE THREAD

**Issue by dpolivaev** [AdoptOpenJDK/IcedTea-Web#568]
For debugging purposes I want to launch Java Web Start locally

```xml
<?xml version="1.0" encoding="utf-8"?><jnlp spec="1.0+" href="file:/D:/Temp/jnlp-test.jnlp" codebase="jnlp-test.jnlp_files/">
```
Unlike java web start delivered with Oracle Java 8 IcedTea produces an exception shown below. Some internal logic requires a host and it is not able to handle local file protocols.

It would be nice if handling local files could be supported.

I use the version packaged with open web start project available at https://openwebstart.com/ running under windows 10. However, it looks like the current code contains the same logic.

```
Could not determine codebase host for resource at file://D:/Temp/jnlp-test.jnlp_files/test.jar while generating URLPermissions
java.net.URISyntaxException: Expected scheme-specific part at index 5: file:
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.failExpecting(URI.java:2854)
	at java.net.URI$Parser.parse(URI.java:3057)
	at java.net.URI.<init>(URI.java:673)
	at net.adoptopenjdk.icedteaweb.jnlp.element.security.SecurityDesc.getHostWithSpecifiedPort(SecurityDesc.java:449)
	at net.adoptopenjdk.icedteaweb.jnlp.element.security.SecurityDesc.getHost(SecurityDesc.java:461)
	at net.adoptopenjdk.icedteaweb.jnlp.element.security.SecurityDesc.getUrlPermissions(SecurityDesc.java:413)
	at net.adoptopenjdk.icedteaweb.jnlp.element.security.SecurityDesc.getSandBoxPermissions(SecurityDesc.java:394)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getAccessControlContextForClassLoading(JNLPClassLoader.java:2082)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.findClass(JNLPClassLoader.java:1580)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClassExt(JNLPClassLoader.java:1611)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.lambda$loadClass$6(JNLPClassLoader.java:1427)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader$ExceptionalSupplier.getResultOfCallOrNull(JNLPClassLoader.java:1391)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClass(JNLPClassLoader.java:1434)
	at net.sourceforge.jnlp.Launcher.createApplet(Launcher.java:564)
	at net.sourceforge.jnlp.Launcher.launchApplet(Launcher.java:489)
	at net.sourceforge.jnlp.Launcher.access$300(Launcher.java:69)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:664)
```

**Comment by dpolivaev** [comment]
I found that 

```xml
<?xml version="1.0" encoding="utf-8"?><jnlp spec="1.0+" href="file:///D:/Temp/jnlp-test.jnlp" codebase="jnlp-test.jnlp_files/">
```

works fine with both Oracle Java and IcedTea. Probably you can close the issue

**Comment by dpolivaev** [comment]
Sorry, it starts but the exception traces are still in the log.
I am attaching the real  log file.
[itw-javantx-2020-01-20_19_30_16.55.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4087462/itw-javantx-2020-01-20_19_30_16.55.log)

**Comment by dpolivaev** [comment]
After the application launches, it has unusually high CPU consumption.
After I close the application window the javaws.exe process continues running with high CPU consumption.

I can submit the application if needed.

**Comment by sclassen** [comment]
Yes please can you provide the application for us to debug

**Comment by dpolivaev** [comment]
Here it is.
The application contains Freeplane version 1.7.12 Java applet,
the source code is available at https://github.com/freeplane/freeplane/tree/release-1.7.12

[jnlp-test.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4150516/jnlp-test.zip)

**Comment by Jamila891** [comment]
@dpolivaev does this problem still occure? We didn't have the time to look at this issue, but if it still doesn't work, we'll look at it in the hopefully near future.

**Comment by dpolivaev** [comment]
I need to check it. Which version do you recommend? Can I use openwebstart 1.2.1?

**Comment by sclassen** [comment]
Yes, 1.2.1 has the latest performance improvements

**Comment by dpolivaev** [comment]
I am sorry, I changed my computer and my OS, and now I use Linux Mint 20.04 which is similar to Ubuntu 20.04.
I can not launch the attached application at all.

Could you please try it with jnlp-test.zip attached to https://github.com/AdoptOpenJDK/IcedTea-Web/issues/568#issuecomment-581650552 ? You need to adapt the href attribute in the first line because the attached file points to my old location.

I can launch it using oracle javaws but it does not launch with openwebstart.

**Comment by janakmulani** [comment]
Hi

I tried your app mentioned above. 

Your app is an Applet. It works with Oracle javaws because Oracle javaws supports applets. OWS does not support applets.

To use OWS please consider migrate the app  away from JApplet.
