### ISSUE TITLE
Unexpected end of ZLIB input stream (jnlp launch on MS-Windows)

### ISSUE THREAD

**Issue by dealboy** [AdoptOpenJDK/IcedTea-Web#602]
Hi,

I am having a jnlp that I try to make it work with AdoptOpenJDK and IcedTea-Web

Running 👍 

> javaws https://myserver.development.int:443/webstart/myapp.jnlp 

I get the following error stack

```
net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file. You can try to download this file manually and send it as bug report to IcedTea-Web team.
     at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)
     at net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)
     at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)
     at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:270)
     at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)
     at java.security.AccessController.doPrivileged(Native Method)
     at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:210)
 Caused by: java.io.IOException: java.lang.NullPointerException: name can't be null
     at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:318)
     at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:231)
     at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)
     at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)
     at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)
     at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:476)
     ... 6 more
 Caused by: java.lang.NullPointerException: name can't be null
     at java.io.FilePermission.init(FilePermission.java:209)
     at java.io.FilePermission.<init>(FilePermission.java:310)
     at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
     at java.io.FileInputStream.<init>(FileInputStream.java:127)
     at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:316)     ... 11 more 
Removed sun.net.www.protocol.https.DelegateHttpsURLConnection:https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false
netx: Read Error: Could not read or parse the JNLP file. (java.lang.NullPointerException: name can't be null (name can't be null))
Disconnecting sun.net.www.protocol.https.DelegateHttpsURLConnection:https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false
java.io.EOFException: Unexpected end of ZLIB input stream
     at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
     at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
     at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
     at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
     at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
     at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
     at java.io.FilterInputStream.read(FilterInputStream.java:107)
     at net.sourceforge.jnlp.cache.ResourceDownloader.uncompressGzip(ResourceDownloader.java:488)
     at net.sourceforge.jnlp.cache.ResourceDownloader.downloadGZipFile(ResourceDownloader.java:405)
     at net.sourceforge.jnlp.cache.ResourceDownloader.downloadResource(ResourceDownloader.java:362)
     at net.sourceforge.jnlp.cache.ResourceDownloader.run(ResourceDownloader.java:118)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at java.lang.Thread.run(Thread.java:748) 

Extracting gzip: https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false to https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false
isCurrent:isCached false
isCached: remote:824 cached:0
Downloading file: https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false into: C:\Users\myuser\.cache\icedtea-web\cache\1\https\myserver.development.int\443\webstart\myapp.jnlp.memory_CUSTOM&memcustom_4096&_memcustomcustom_4096&cache_disk&skipsingle_false
Downloading https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false using https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false (encoding : gzip)
Selected proxies: [DIRECT]
Browser selected proxies: [DIRECT]
Browser proxy option "4" (Automatic) not supported yet.
Selecting proxy for: socket://myserver.development.int:443
Selected proxies: [DIRECT]
Browser selected proxies: [DIRECT]
Browser proxy option "4" (Automatic) not supported yet.
Selecting proxy for: https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false
done https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false
Adding sun.net.www.protocol.https.DelegateHttpsURLConnection:https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false
Connecting https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false
Removed sun.net.www.protocol.https.DelegateHttpsURLConnection:https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false
Disconnecting sun.net.www.protocol.https.DelegateHttpsURLConnection:https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false
isCached: remote:824 cached:0
isCurrent: https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false = false
isCurrent:isCached false
isCached: remote:824 cached:0
done https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false
Adding sun.net.www.protocol.https.DelegateHttpsURLConnection:https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false
Connecting https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false
best url for location=https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false state=PRECONNECT CONNECTING PREDOWNLOAD PROCESSING is https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false by HEAD
Removed sun.net.www.protocol.https.DelegateHttpsURLConnection:https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false
Disconnecting sun.net.www.protocol.https.DelegateHttpsURLConnection:https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false
Key : Content-Type ,Value : [application/x-java-jnlp-file;charset=UTF-8]
Key : Date ,Value : [Tue, 10 Mar 2020 09:02:31 GMT]
Key : Content-Length ,Value : [824]
Key : Last-Modified ,Value : [Tue, 10 Mar 2020 09:02:31 GMT]
Key : Connection ,Value : [close]
Key : Content-Disposition ,Value : [attachment; filename=myapp.jnlp]
Key : content-encoding ,Value : [gzip]
Key : Server ,Value : [Apache-Coyote/1.1]
Key : null ,Value : [HTTP/1.1 200 OK]
Selected proxies: [DIRECT]
Browser selected proxies: [DIRECT]
Browser proxy option "4" (Automatic) not supported yet.
Selecting proxy for: socket://myserver.development.int:443
Selected proxies: [DIRECT]
Browser selected proxies: [DIRECT]
Browser proxy option "4" (Automatic) not supported yet.
Selecting proxy for: https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false
done https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false
Adding sun.net.www.protocol.https.DelegateHttpsURLConnection:https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false
Connecting https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false
All possible urls for location=https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false state=PRECONNECT CONNECTING PREDOWNLOAD PROCESSING : [https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false, https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false]
Finding best URL for: https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false : DownloadOptions[use pack: false; use version: false]
UNIQUEKEY=1583830948002-1138983867-https://myserver.development.int/static/myapp.jnlp
good - your JRE - 1.8.0_242 - match requested JRE - 1.8+
Acceptable vendor tag found, contains: myapp Tech
Acceptable title tag found, contains: myapp Vendor
Jars not ready to provide attribute Application-Name
Description: myapp Vendor Application
Homepage: http://www.myapp.com
line: 3

line: 2 <jnlp spec="1.0+" codebase="https://myserver.development.int:443/webstart" href="https://myserver.development.int:443/webstart/myapp.jnlp?memory=CUSTOM&memcustom=4096&;memcustomcustom=4096&cache=disk&skipsingle=false" xmlns="http://www.w3.org/1999/xhtml"><information><title>myapp Vendor</title><vendor>myapp Tech</vendor><homepage href="http://www.myapp.com"></homepage><description>myapp Vendor Application</description><icon href="icon.jpg"></icon></information><resources><j2se version="1.8+" initial-heap-size="128m" max-heap-size="4096m" java-vm-args="-XX:+HeapDumpOnOutOfMemoryError -XX:SoftRefLRUPolicyMSPerMB=10 -XX:MaxPermSize=192m -Xss320k -XX:+DisableExplicitGC"></j2se><property name="sun.rmi.dgc.client.gcInterval" value="3600000"></property><property name="sun.rmi.dgc.server.gcInterval" value="3600000"></property><property name="java.protocol.handler.pkgs" value="com.myapp.protocols"></property><property name="java.net.preferIPv4Stack" value="true"></property><property name="sun.java2d.noddraw" value="true"></property><property name="net.sf.ehcache.skipUpdateCheck" value="true"></property><property name="sun.java2d.dpiaware" value="false"></property><jar href="ptwsbootstrap-3.13.4.3-xavier_patching.674464.25-signed.jar"></jar></resources><resources os="Windows" arch="x86"><jar href="nativelibswin32.jar" download="eager"></jar></resources><resources os="Windows" arch="x86_64"><jar href="nativelibswin64.jar" download="eager"></jar></resources><resources os="Windows" arch="amd64"><jar href="nativelibswin64.jar" download="eager"></jar></resources><resources os="Linux" arch="x86_64"></resources><resources os="Linux" arch="amd64"></resources><resources os="Windows" arch="x86"><nativelib href="nativelibswin32.jar" download="eager"></nativelib></resources><resources os="Windows" arch="x86_64"><nativelib href="nativelibswin64.jar" download="eager"></nativelib></resources><resources os="Windows" arch="amd64"><nativelib href="nativelibswin64.jar" download="eager"></nativelib></resources><resources os="Linux" arch="x86_64"></resources><resources os="Linux" arch="amd64"></resources><application-desc main-class="com.myapp.webstart.bootstrap.Bootstrap" java-vm-args="-XX:+HeapDumpOnOutOfMemoryError -XX:SoftRefLRUPolicyMSPerMB=10 -XX:MaxPermSize=192m -Xss320k -XX:+DisableExplicitGC"><argument>https://myserver.development.int:443/webstart/myapp.jnlp.properties?cache=disk&skipsingle=false</argument><argument>-locale=</argument></application-desc><security><all-permissions></all-permissions></security></jnlp>
<?xml version="1.0" standalone="yes"?>
Removed sun.net.www.protocol.https.DelegateHttpsURLConnection:https://myserver.development.int/static/myapp.jnlp
Disconnecting sun.net.www.protocol.https.DelegateHttpsURLConnection:https://myserver.development.int/static/myapp.jnlp
Using MalformedXMLParser
isCurrent: https://myserver.development.int/static/myapp.jnlp = true
isCurrent:lastModified cache:1527236100000 actual:1527236100000
isCurrent:isCached true
isCached: remote:2403 cached:2403
done https://myserver.development.int/static/myapp.jnlp
Adding sun.net.www.protocol.https.DelegateHttpsURLConnection:https://myserver.development.int/static/myapp.jnlp
Connecting https://myserver.development.int/static/myapp.jnlp
best url for location=https://myserver.development.int/static/myapp.jnlp state=PRECONNECT CONNECTING PREDOWNLOAD PROCESSING is https://myserver.development.int/static/myapp.jnlp by HEAD
Removed sun.net.www.protocol.https.DelegateHttpsURLConnection:https://myserver.development.int/static/myapp.jnlp
Disconnecting sun.net.www.protocol.https.DelegateHttpsURLConnection:https://myserver.development.int/static/myapp.jnlp
Key : Content-Type ,Value : [application/x-java-jnlp-file]
Key : Date ,Value : [Tue, 10 Mar 2020 09:02:26 GMT]
Key : Content-Length ,Value : [2403]
Key : Last-Modified ,Value : [Fri, 25 May 2018 08:15:00 GMT]
Key : Connection ,Value : [close]
Key : ETag ,Value : [W/"2403-1527236100000"]
Key : Server ,Value : [Apache-Coyote/1.1]
Key : null ,Value : [HTTP/1.1 200 OK]
Key : Accept-Ranges ,Value : [bytes]
Selected proxies: [DIRECT]
Browser selected proxies: [DIRECT]
Browser proxy option "4" (Automatic) not supported yet.
Selecting proxy for: socket://myserver.development.int:443
Selected proxies: [DIRECT]
Browser selected proxies: [DIRECT]
Browser proxy option "4" (Automatic) not supported yet.
Selecting proxy for: https://myserver.development.int/static/myapp.jnlp
done https://myserver.development.int/static/myapp.jnlp
Adding sun.net.www.protocol.https.DelegateHttpsURLConnection:https://myserver.development.int/static/myapp.jnlp
Connecting https://myserver.development.int/static/myapp.jnlp
All possible urls for location=https://myserver.development.int/static/myapp.jnlp state=PRECONNECT CONNECTING PREDOWNLOAD PROCESSING : [https://myserver.development.int/static/myapp.jnlp, https://myserver.development.int/static/myapp.jnlp]
Finding best URL for: https://myserver.development.int/static/myapp.jnlp : DownloadOptions[use pack: false; use version: false]
        result: null
call privileged method: getCodeBase
Warning, null basicService
JNLP file location: https://myserver.development.int/static/myapp.jnlp
Proceeding with jnlp
Read 112 entries from Firefox's preferences
Found preferences file: C:\Users\myuser\AppData\Roaming\Mozilla\Firefox\Profiles/92jdbzso.default\prefs.js
Using firefox's profiles file: C:\Users\myuser\AppData\Roaming\Mozilla\Firefox\profiles.ini
Starting security dialog thread
Forcing of offline set to: false
WARNING: key deployment.system.cachedir has no value, skipping
WARNING: key deployment.system.cachedir has no value, setting to default value
Loading User level properties from: file:/C:/Users/myuser/.config/icedtea-web/deployment.properties
Ico provider registered correctly.
cache: C:\Users\myuser\.cache\icedtea-web file exists:true
config: C:\Users\myuser\.config\icedtea-web file exists: true
System is already following XDG .cache and .config specifications
```

Any help or ideas would be appreciated!

thanks in advance
Yannis

**Comment by sclassen** [comment]
can you try your jnlp with https://openwebstart.com/

**Comment by dealboy** [comment]
> can you try your jnlp with https://openwebstart.com/

I just did, and I get an errror pop-up : 

> java.lang.IllegalStateException: could not find any suitable runtime
>     at com.openwebstart.launcher.OwsJvmLauncher.getLocalJavaRuntimeOrExit(OwsJvmLauncher.java:73)
>     at com.openwebstart.launcher.OwsJvmLauncher.launchExternal(OwsJvmLauncher.java:122)
>     at com.openwebstart.launcher.OwsJvmLauncher.launchExternal(OwsJvmLauncher.java:67)
>     at net.sourceforge.jnlp.Launcher.launchExternal(Launcher.java:284)
>     at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:365)
>     at net.sourceforge.jnlp.Launcher.access$200(Launcher.java:69)
>     at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:650)

 do I miss some configuration?

**Comment by sclassen** [comment]
it depends :wink: 
What is the Java version your application requires?

**Comment by dealboy** [comment]
hmmm, 
I forgot to mention that the app is for java 1.8 and I work with AdoptOpenJDK 1.8.0_242

**Comment by sclassen** [comment]
OK. then make sure that in your JNLP you have a `<java>` or `<j2se>` tag with an attribute `version="1.8+"`

Then OpenWebStart will automatically download a suitable JVM.
Alternatively you can open the program `itw-settings` which is located in the installation directory besides the `javaws` executable.
There you will find the configurations. In the tab for JVM-Manager you can configure which JVMs to use. You can also add already installed JVMs

**Comment by dealboy** [comment]
Great!
I added manually the entry with itw-settings (my VMs do not have internet access) and works fine! 
Thanks a lot @sclassen 

I have a couple of housekeeping questions, if you may answer: 
should I drop IcedTea-Web and use Openwebstart? 
will that be included in AdoptOpenJDK installer in the future (as there is IcedTea-Web) ?
and finally, is there a way to configure the local JREs without the itw-settings gui like a configuration file?

thanks again
Yannis

**Comment by sclassen** [comment]
Sure

OWS is based on ITW and uses it internally. But it is using a 2.0.0-alpha branch of ITW and not the 1.8 branch.
But OWS works orthogonal to ITW because it provides a JVM manager which will download appropriate JVMs as they are required. ITW on the other hand can only launch applications in the current JVM.
For this reason OWS will never be bundled with Adopt or any other JVM.

I do not have any information what Adopt's plans are for the future. If they will continue to supply a version with ITW bundled.
Also I have not sufficient information about when a first ITW 2.0.0 will be released. It is possible that this will not happen soon.

Last but not least:
There is currently no way to programmatically interact with the JVM Manager.
But it uses a very simple file which you could manipulate. `${userHome}/.cache/icedtea-web/jvm-cache/cache.json`
