### ISSUE TITLE
Exception in thread "AWT-EventQueue-1" java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by jagadeesanvol** [AdoptOpenJDK/IcedTea-Web#609]
I am trying to launch the swing application through jnlp. getting below errors.
Enviroments:
Wondows 10+icedtea-web-1.7.1-image+java-1.8.0-openjdk-1.8.0.212-3.b04.redhat.windows.x86_64
Note: If I launch the application directly from eclispe , it is NOT throwing any errors and application working properly

Exception in thread "AWT-EventQueue-1" java.lang.ExceptionInInitializerError
      at com.d.favorites.view.FavoriteStarView.onModelPropertyChange(FavoriteStarView.java:90)
        at com.projects.dc.util.controller.DefaultPropertyChangeController.propertyChange(DefaultPropertyChangeController.java:178)
        at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
        at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)

Caused by: java.lang.ClassNotFoundException: org.dozer.util.DefaultClassLoader
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.apache.commons.lang.ClassUtils.getClass(ClassUtils.java:757)
        at org.apache.commons.lang.ClassUtils.getClass(ClassUtils.java:822)
        at org.apache.commons.lang.ClassUtils.getClass(ClassUtils.java:805)
        at org.dozer.util.DefaultClassLoader.loadClass(DefaultClassLoader.java:36)

please help me on this.

**Comment by sclassen** [comment]
1.7 is not supported any more.
Can you try a 1.8 version or https://openwebstart.com

**Comment by jagadeesanvol** [comment]
Hello,
Thanks for your email.
I have used the java-1.8.0-openjdk-1.8.0.212-3.b04.redhat.windows.x86_64
version

**Comment by AndreasEhret** [comment]
@sclassen is talking about the IcedTea-Web version here (1.7.x) not the JDK version.

**Comment by bnd001** [comment]
I am having the same issue with IceedTea version 1.8.
Can somebody please help with this
