### ISSUE TITLE
Caused by: java.io.IOException: java.lang.NullPointerException: name can't be null

### ISSUE THREAD

**Issue by danieltoril** [AdoptOpenJDK/IcedTea-Web#610]
net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file. You can try to download this file manually and send it as bug report to IcedTea-Web team.
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)
	at net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)
	at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:270)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:310)
	at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:210)
Caused by: java.io.IOException: java.lang.NullPointerException: name can't be null
	at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:318)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:240)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:453)
	... 6 more
Caused by: java.lang.NullPointerException: name can't be null
	at java.base/java.io.FilePermission.init(FilePermission.java:321)
	at java.base/java.io.FilePermission.<init>(FilePermission.java:475)
	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:747)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:144)
	at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:316)
	... 11 more

[karat.jnlp.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4367649/karat.jnlp.txt)

**Comment by sclassen** [comment]
This exception happens when a jnlp file (main or extension) cannot be doenloaded. Can you please enable logging to file and debug logging.
You can then attach a log to this issue or check yourself what the problem is with downloading of the jnlp file

**Comment by danieltoril** [comment]
Hi, this is the log, I've attached de jnlp file with txt extension, can you see to find or try tu debug?. With Oracle JDK works fine. Thanks

**Comment by danieltoril** [comment]
[itw-javantx-2020-03-23_08_28_40.463.log](https://github.com/AdoptOpenJDK/IcedTea-Web/files/4367807/itw-javantx-2020-03-23_08_28_40.463.log)

**Comment by sclassen** [comment]
The log shows multiple exceptions:
```
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:307)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:285)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:180)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1180)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1091)
```
Please check the setup of your server
