### ISSUE TITLE
NPE during app launch

### ISSUE THREAD

**Issue by NikitaS1609** [AdoptOpenJDK/IcedTea-Web#697]
Hi All,

I am getting below exception while trying to launch my application using Iced Web tea - Zulu:

MESSAGE Exception launching the Eclipse Platform:
```
java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:460)
	at org.eclipse.equinox.launcher.WebStartMain.basicRun(WebStartMain.java:79)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1389)
	at org.eclipse.equinox.launcher.WebStartMain.main(WebStartMain.java:56)
	at com.nomura.dna.hub.securelauncher.WebStartMain.main(WebStartMain.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:576)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:945)
```

Can someone help me?

**Comment by sclassen** [comment]
The message suggest that the code is trying to insert `null` into a Hashtable.
The origin of this insert is in the class `org.eclipse.equinox.launcher.WebStartMain` which is not part of ITW.
You need to look in you application code to see what is going wrong

**Comment by NikitaS1609** [comment]
ok thank you for your reply!
