### ISSUE TITLE
Unexpected exception while launching icedtea.

### ISSUE THREAD

**Issue by tnais** [AdoptOpenJDK/IcedTea-Web#701]
When launching the same thing discussed in https://github.com/AdoptOpenJDK/IcedTea-Web/issues/699, another use, this time using Ubuntu 18.04 incurres in this  exception:

java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1349)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1324)
	at net.sourceforge.swing.SwingUtils.callOnAppContext(SwingUtils.java:149)
	at net.sourceforge.swing.SwingUtils.invokeAndWait(SwingUtils.java:161)
	at net.sourceforge.jnlp.security.SecurityDialog.initDialog(SecurityDialog.java:239)
	at net.sourceforge.jnlp.security.SecurityDialog.<init>(SecurityDialog.java:127)
	at net.sourceforge.jnlp.security.SecurityDialogMessageHandler.handleMessage(SecurityDialogMessageHandler.java:114)
	at net.sourceforge.jnlp.security.SecurityDialogMessageHandler.run(SecurityDialogMessageHandler.java:94)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at javax.swing.ImageIcon.<init>(ImageIcon.java:217)
	at net.sourceforge.jnlp.jdk89acesses.SunMiscLauncher.getSecureImageIcon(SunMiscLauncher.java:56)
	at net.sourceforge.jnlp.security.dialogs.CertWarningPane.getImageIcon(CertWarningPane.java:212)
	at net.sourceforge.jnlp.security.dialogs.CertWarningPane.setTextAndLabels(CertWarningPane.java:192)
	at net.sourceforge.jnlp.security.dialogs.CertWarningPane.addComponents(CertWarningPane.java:121)
	at net.sourceforge.jnlp.security.dialogs.CertWarningPane.<init>(CertWarningPane.java:114)
	at net.sourceforge.jnlp.security.SecurityDialog.getPanel(SecurityDialog.java:335)
	at net.sourceforge.jnlp.security.SecurityDialog.getPanel(SecurityDialog.java:329)
	at net.sourceforge.jnlp.security.SecurityDialog.getPanel(SecurityDialog.java:322)
	at net.sourceforge.jnlp.security.SecurityDialog.installPanel(SecurityDialog.java:370)
	at net.sourceforge.jnlp.security.SecurityDialog.access$000(SecurityDialog.java:80)
	at net.sourceforge.jnlp.security.SecurityDialog$1.run(SecurityDialog.java:242)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1349)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1324)
	at net.sourceforge.swing.SwingUtils.callOnAppContext(SwingUtils.java:149)
	at net.sourceforge.swing.SwingUtils.invokeAndWait(SwingUtils.java:161)
	at net.sourceforge.jnlp.security.dialogs.ViwableDialog.show(ViwableDialog.java:109)
	at net.sourceforge.jnlp.security.SecurityDialogMessageHandler.processMessageInGui(SecurityDialogMessageHandler.java:173)
	at net.sourceforge.jnlp.security.SecurityDialogMessageHandler.handleMessage(SecurityDialogMessageHandler.java:138)
	at net.sourceforge.jnlp.security.SecurityDialogMessageHandler.run(SecurityDialogMessageHandler.java:94)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.security.AccessControlException: access denied ("java.awt.AWTPermission" "watchMousePointer")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:886)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at net.sourceforge.jnlp.runtime.JNLPSecurityManager.checkPermission(JNLPSecurityManager.java:292)
	at java.awt.MouseInfo.getPointerInfo(MouseInfo.java:79)
	at net.sourceforge.jnlp.util.ScreenFinder.getCurrentScreenSizeWithoutBounds(ScreenFinder.java:60)
	at net.sourceforge.jnlp.util.ScreenFinder.centerWindowsToCurrentScreen(ScreenFinder.java:70)
	at net.sourceforge.jnlp.security.dialogs.ViwableDialog.centerDialog(ViwableDialog.java:195)
	at net.sourceforge.jnlp.security.dialogs.ViwableDialog.access$200(ViwableDialog.java:59)
	at net.sourceforge.jnlp.security.dialogs.ViwableDialog$9.run(ViwableDialog.java:202)
	at net.sourceforge.jnlp.security.dialogs.ViwableDialog.createJDialog(ViwableDialog.java:74)
	at net.sourceforge.jnlp.security.dialogs.ViwableDialog.access$100(ViwableDialog.java:59)
	at net.sourceforge.jnlp.security.dialogs.ViwableDialog$4.run(ViwableDialog.java:113)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.GNOME.Accessibility.AtkWrapper$6.dispatchEvent(AtkWrapper.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

The application starts then hangs.

The strange thing is that it is a script running smoothly since almost a year on my machine. Windows users got an installer, Mac user a zipped app and Linux user instructions :) and the instructions are based on my using of IcedTea and OpenJdk 8 on my corporate machine (again Ubuntu 18.04, but I slapped Gnome real hard) and later even on my own machine (Ubuntu 20, this one keeping Gnome because it's good at handling 4k screens).

Attachment contains logs in the first zip, environment variables and installed (installati) in extras.zip

[icedteaLog.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/5246796/icedteaLog.zip)
[extras.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/5246807/extras.zip)

**Comment by tnais** [comment]
Solved editing policies.
