### ISSUE TITLE
"netx: Read Error: Could not read or parse the JNLP file" when trying to start JNLP from web URL

### ISSUE THREAD

**Issue by RochaStratovan** [AdoptOpenJDK/IcedTea-Web#718]
Hello,

I am attempting to start a Jenkins slave agent using from a windows command console using the command
```
javaws http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp
```

and icedtea-web is failing with the message
```
C:\Users\Stratovan>javaws http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp

C:\Users\Stratovan>selected jre: C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\jre\
Unable to use Firefox's proxy settings. Using "DIRECT" as proxy type.
netx: Read Error: Could not read or parse the JNLP file. (java.lang.NullPointerException: name can't be null (name can't be null))
```

It also causes an Error dialog to appear

The [Details] content is
```
net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file. You can try to download this file manually and send it as bug report to IcedTea-Web team.
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)
	at net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)
	at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:270)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:210)
Caused by: java.io.IOException: java.lang.NullPointerException: name can't be null
	at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:318)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:231)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:453)
	... 6 more
Caused by: java.lang.NullPointerException: name can't be null
	at java.io.FilePermission.init(FilePermission.java:209)
	at java.io.FilePermission.<init>(FilePermission.java:310)
	at java.lang.SecurityManager.checkRead(SecurityManager.java:888)
	at java.io.FileInputStream.<init>(FileInputStream.java:127)
	at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:316)
	... 11 more
```

The [Java Console] content is
```

net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file. You can try to download this file manually and send it as bug report to IcedTea-Web team.     at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)     at net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)     at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)     at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:270)     at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)     at java.security.AccessController.doPrivileged(Native Method)     at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:210) Caused by: java.io.IOException: java.lang.NullPointerException: name can't be null     at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:318)     at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:231)     at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)     at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)     at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)     at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:453)     ... 6 more Caused by: java.lang.NullPointerException: name can't be null     at java.io.FilePermission.init(FilePermission.java:209)     at java.io.FilePermission.<init>(FilePermission.java:310)     at java.lang.SecurityManager.checkRead(SecurityManager.java:888)     at java.io.FileInputStream.<init>(FileInputStream.java:127)     at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:316)     ... 11 more 
netx: Read Error: Could not read or parse the JNLP file. (java.lang.NullPointerException: name can't be null (name can't be null))
Disconnecting sun.net.www.protocol.http.HttpURLConnection:http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp
java.io.EOFException: Unexpected end of ZLIB input stream     at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)     at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)     at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)     at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)     at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)     at java.io.BufferedInputStream.read(BufferedInputStream.java:345)     at java.io.FilterInputStream.read(FilterInputStream.java:107)     at net.sourceforge.jnlp.cache.ResourceDownloader.uncompressGzip(ResourceDownloader.java:488)     at net.sourceforge.jnlp.cache.ResourceDownloader.downloadGZipFile(ResourceDownloader.java:405)     at net.sourceforge.jnlp.cache.ResourceDownloader.downloadResource(ResourceDownloader.java:362)     at net.sourceforge.jnlp.cache.ResourceDownloader.run(ResourceDownloader.java:118)     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)     at java.lang.Thread.run(Thread.java:748) 
Extracting gzip: http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp to http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp
isCurrent:isCached false
Downloading file: http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp into: C:\Users\Stratovan\.cache\icedtea-web\cache\0\http\mozart.stratovan.com\8080\computer\JRR-TEST\slave-agent.jnlp
Downloading http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp using http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp (encoding : gzip)
Selected proxies: [DIRECT]
Browser selected proxies: [DIRECT]
Selecting proxy for: http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp
done http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp
Connecting http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp
Disconnecting sun.net.www.protocol.http.HttpURLConnection:http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp
isCurrent: http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp = false
isCurrent:isCached false
done http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp
Connecting http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp
best url for location=http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp state=PRECONNECT CONNECTING PREDOWNLOAD PROCESSING is http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp by HEAD
Disconnecting sun.net.www.protocol.http.HttpURLConnection:http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp
Key : Content-Type ,Value : [application/x-java-jnlp-file]
Key : Date ,Value : [Fri, 16 Oct 2020 23:50:43 GMT]
Key : Content-Length ,Value : [394]
Key : Content-Encoding ,Value : [gzip]
Key : X-Content-Type-Options ,Value : [nosniff]
Key : Server ,Value : [Jetty(9.4.30.v20200611)]
Key : null ,Value : [HTTP/1.1 200 OK]
Selected proxies: [DIRECT]
Browser selected proxies: [DIRECT]
Selecting proxy for: socket://mozart.stratovan.com:8080
Selected proxies: [DIRECT]
Browser selected proxies: [DIRECT]
Selecting proxy for: http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp
done http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp
Connecting http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp
All possible urls for location=http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp state=PRECONNECT CONNECTING PREDOWNLOAD PROCESSING : [http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp, http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp]
Finding best URL for: http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp : DownloadOptions[use pack: false; use version: false]
        result: null
Warning, null basicService
JNLP file location: http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp
Proceeding with jnlp
Unable to use Firefox's proxy settings. Using "DIRECT" as proxy type.
java.io.FileNotFoundException: C:\Users\Stratovan\AppData\Roaming\Mozilla\Firefox\profiles.ini     at net.sourceforge.jnlp.browser.FirefoxPreferencesFinder.find(FirefoxPreferencesFinder.java:84)     at net.sourceforge.jnlp.browser.BrowserAwareProxySelector.parseBrowserPreferences(BrowserAwareProxySelector.java:151)     at net.sourceforge.jnlp.browser.BrowserAwareProxySelector.initFromBrowserConfig(BrowserAwareProxySelector.java:114)     at net.sourceforge.jnlp.browser.BrowserAwareProxySelector.initialize(BrowserAwareProxySelector.java:101)     at net.sourceforge.jnlp.runtime.JNLPRuntime.initialize(JNLPRuntime.java:292)     at net.sourceforge.jnlp.runtime.Boot.init(Boot.java:349)     at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:58)     at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:270)     at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)     at java.security.AccessController.doPrivileged(Native Method)     at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:210) 
Starting security dialog thread
Forcing of offline set to: false
WARNING: key deployment.system.cachedir has no value, setting to default value
java.io.FileNotFoundException: C:\Users\Stratovan\.config\icedtea-web\deployment.properties (The system cannot find the file specified)     at java.io.FileInputStream.open0(Native Method)     at java.io.FileInputStream.open(FileInputStream.java:195)     at java.io.FileInputStream.<init>(FileInputStream.java:138)     at java.io.FileInputStream.<init>(FileInputStream.java:93)     at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)     at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)     at java.net.URL.openStream(URL.java:1068)     at net.sourceforge.jnlp.config.DeploymentConfiguration.loadComments(DeploymentConfiguration.java:928)     at net.sourceforge.jnlp.config.DeploymentConfiguration.load(DeploymentConfiguration.java:385)     at net.sourceforge.jnlp.config.DeploymentConfiguration.load(DeploymentConfiguration.java:347)     at net.sourceforge.jnlp.config.DeploymentConfiguration.load(DeploymentConfiguration.java:325)     at net.sourceforge.jnlp.runtime.JNLPRuntime$DeploymentConfigurationHolder.initConfiguration(JNLPRuntime.java:457)     at net.sourceforge.jnlp.runtime.JNLPRuntime$DeploymentConfigurationHolder.<clinit>(JNLPRuntime.java:452)     at net.sourceforge.jnlp.runtime.JNLPRuntime.getConfiguration(JNLPRuntime.java:487)     at net.sourceforge.jnlp.config.DirectoryValidator.<init>(DirectoryValidator.java:226)     at net.sourceforge.jnlp.config.DeploymentConfiguration.move14AndOlderFilesTo15Structure(DeploymentConfiguration.java:886)     at net.sourceforge.jnlp.config.DeploymentConfiguration.move14AndOlderFilesTo15StructureCatched(DeploymentConfiguration.java:786)     at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:121) 
No User level deployment.properties found.
java.io.FileNotFoundException: C:\Users\Stratovan\.config\icedtea-web\deployment.properties (The system cannot find the file specified)     at java.io.FileInputStream.open0(Native Method)     at java.io.FileInputStream.open(FileInputStream.java:195)     at java.io.FileInputStream.<init>(FileInputStream.java:138)     at java.io.FileInputStream.<init>(FileInputStream.java:93)     at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)     at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)     at java.net.URL.openStream(URL.java:1068)     at net.sourceforge.jnlp.config.DeploymentConfiguration.parsePropertiesFile(DeploymentConfiguration.java:711)     at net.sourceforge.jnlp.config.DeploymentConfiguration.findSystemConfigFile(DeploymentConfiguration.java:533)     at net.sourceforge.jnlp.config.DeploymentConfiguration.load(DeploymentConfiguration.java:345)     at net.sourceforge.jnlp.config.DeploymentConfiguration.load(DeploymentConfiguration.java:325)     at net.sourceforge.jnlp.runtime.JNLPRuntime$DeploymentConfigurationHolder.initConfiguration(JNLPRuntime.java:457)     at net.sourceforge.jnlp.runtime.JNLPRuntime$DeploymentConfigurationHolder.<clinit>(JNLPRuntime.java:452)     at net.sourceforge.jnlp.runtime.JNLPRuntime.getConfiguration(JNLPRuntime.java:487)     at net.sourceforge.jnlp.config.DirectoryValidator.<init>(DirectoryValidator.java:226)     at net.sourceforge.jnlp.config.DeploymentConfiguration.move14AndOlderFilesTo15Structure(DeploymentConfiguration.java:886)     at net.sourceforge.jnlp.config.DeploymentConfiguration.move14AndOlderFilesTo15StructureCatched(DeploymentConfiguration.java:786)     at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:121) 
Ico provider registered correctly.
cache: C:\Users\Stratovan\.cache\icedtea-web file exists:true
config: C:\Users\Stratovan\.config\icedtea-web file exists: true
System is already following XDG .cache and .config specifications
```

The following is [System Properties].
```
System Properties:

java.vendor: AdoptOpenJDK
deployment.user.security.trusted.certs: C:\Users\Stratovan\.config\icedtea-web\security\trusted.certs
sun.java.launcher: SUN_STANDARD
sun.management.compiler: HotSpot 64-Bit Tiered Compilers
os.name: Windows 10
sun.boot.class.path: C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\jre\lib\resources.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\jre\lib\rt.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\jre\lib\sunrsasign.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\jre\lib\jsse.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\jre\lib\jce.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\jre\lib\charsets.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\jre\lib\jfr.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\jre\classes;C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\share/icedtea-web\javaws.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\share/icedtea-web\plugin.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\share/icedtea-web\jsobject.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\win-deps-runtime\js.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\win-deps-runtime\tagsoup.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\win-deps-runtime\mslinks.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\jre\lib\ext\nashorn.jar;
sun.desktop: windows
java.vm.specification.vendor: Oracle Corporation
deployment.log.headers: false
deployment.system.security.cacerts: C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\jre\lib\security\cacerts
java.runtime.version: 1.8.0_265-b01
deployment.security.notinca.warning: true
deployment.launcher.rust.cp.add:
deployment.log.file.clientapp: true
user.name: Stratovan
deployment.security.askgrantdialog.notinca: true
deployment.log.stdstreams: true
deployment.user.security.trusted.clientauthcerts: C:\Users\Stratovan\.config\icedtea-web\security\trusted.clientcerts
user.language: en
sun.boot.library.path: C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\jre\bin
deployment.user.cachedir: C:\Users\Stratovan\.cache\icedtea-web\cache
deployment.security.jsse.hostmismatch.warning: true
deployment.javaws.update.timeout: 500
javawebstart.version: javaws-1.8.0_265
java.version: 1.8.0_265
user.timezone: America/Los_Angeles
sun.arch.data.model: 64
deployment.security.expired.warning: true
java.endorsed.dirs: C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\jre\lib\endorsed
deployment.security.sandbox.jnlp.enhanced: true
deployment.small.size.override.width: 800
deployment.log.file: false
sun.cpu.isalist: amd64
deployment.log: false
sun.jnu.encoding: Cp1252
file.encoding.pkg: sun.io
file.separator: \
java.specification.name: Java Platform API Specification
deployment.javaws.associations: 2
deployment.javaws.shortcut: ASK_IF_HINTED
java.class.version: 52.0
deployment.cache.jarcompression: 0
user.country: US
deployment.security.sandbox.awtwarningwindow: true
java.home: C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\jre
java.vm.info: mixed mode
os.version: 10.0
deployment.system.security.trusted.jssecerts: C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\jre\lib\security\trusted.jssecerts
path.separator: ;
deployment.user.security.trusted.cacerts: C:\Users\Stratovan\.config\icedtea-web\security\trusted.cacerts
java.vm.version: 25.265-b01
deployment.user.runningfile: C:\Users\STRATO~1\AppData\Local\Temp\Stratovan\netx\locks\netx_running
deployment.user.security.trusted.jssecacerts: C:\Users\Stratovan\.config\icedtea-web\security\trusted.jssecacerts
user.variant:
deployment.log.system: true
icedtea-web.bin.location: C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\bin\javaws.exe
sun.awt.enableExtraMouseButtons: true
java.awt.printerjob: sun.awt.windows.WPrinterJob
deployment.system.security.trusted.certs: C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\jre\lib\security\trusted.certs
sun.io.unicode.encoding: UnicodeLittle
awt.toolkit: sun.awt.windows.WToolkit
sun.stdout.encoding: cp437
user.script:
user.home: C:\Users\Stratovan
deployment.system.config.mandatory: false
java.specification.vendor: Oracle Corporation
deployment.small.size.override.height: 600
java.library.path: C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\jre\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\Stratovan\AppData\Local\Microsoft\WindowsApps;;.
java.vendor.url: http://java.oracle.com/
deployment.cache.max.size: -1
java.vm.vendor: AdoptOpenJDK
deployment.security.askgrantdialog.show: true
deployment.user.security.policy: file://C:\Users\Stratovan\.config\icedtea-web\security\java.policy
java.runtime.name: OpenJDK Runtime Environment
deployment.user.tmp: C:\Users\Stratovan\.cache\icedtea-web\tmp
sun.java.command: net.sourceforge.jnlp.runtime.Boot http://mozart.stratovan.com:8080/computer/JRR-TEST/slave-agent.jnlp
java.class.path: C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\jre\lib\rt.jar;C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\jre\lib\ext\jfxrt.jar;
deployment.launcher.rust.bootcp.remove:
java.vm.specification.name: Java Virtual Machine Specification
java.vm.specification.version: 1.8
sun.cpu.endian: little
sun.os.patch.level:
java.io.tmpdir: C:\Users\STRATO~1\AppData\Local\Temp\
deployment.proxy.type: 3
java.vendor.url.bug: http://bugreport.sun.com/bugreport/
deployment.user.locksdir: C:\Users\STRATO~1\AppData\Local\Temp\Stratovan\netx\locks
deployment.headless.ignore: false
deployment.user.pcachedir: C:\Users\Stratovan\.cache\icedtea-web\pcache
os.arch: amd64
java.awt.graphicsenv: sun.awt.Win32GraphicsEnvironment
java.ext.dirs: C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\jre\lib\ext;C:\WINDOWS\Sun\Java\lib\ext
deployment.small.size.treshold: 10
user.dir: C:\Users\Stratovan
deployment.security.itw.ignorecertissues: false
icedtea-web.bin.name: javaws.exe
deployment.system.security.trusted.clientautcerts: C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\jre\lib\security\trusted.clientcerts
deployment.launcher.rust.cp.remove:
line.separator:

java.vm.name: OpenJDK 64-Bit Server VM
deployment.javaws.autodownload: false
deployment.manifest.attributes.check: ALL
deployment.log.file.legacylog: false
deployment.https.noenforce: false
sun.stderr.encoding: cp437
file.encoding: Cp1252
deployment.user.security.trusted.jssecerts: C:\Users\Stratovan\.config\icedtea-web\security\trusted.jssecerts
deployment.javapi.cache.enabled: false
deployment.console.startup.mode: HIDE
deployment.user.logdir: C:\Users\Stratovan\.config\icedtea-web\log
java.specification.version: 1.8
deployment.proxy.same: false
deployment.system.security.jssecacerts: C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-hotspot\jre\lib\security\jssecacerts
deployment.jnlpclassloader.strict: true
```

This is a freshly created VM running Windows 10 Enterprise.

I just installed AdoptOpenJdk (OpenJDK8U-jdk_x64_windows_hotspot_8u265b01.msi)

Mozart is reachable from this VM:
```
C:\Users\Stratovan>ping mozart.stratovan.com

Pinging mozart.stratovan.com [192.168.100.118] with 32 bytes of data:
Reply from 192.168.100.118: bytes=32 time=1ms TTL=128
Reply from 192.168.100.118: bytes=32 time=1ms TTL=128
Reply from 192.168.100.118: bytes=32 time<1ms TTL=128
Reply from 192.168.100.118: bytes=32 time=1ms TTL=128

Ping statistics for 192.168.100.118:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 1ms, Average = 0ms

C:\Users\Stratovan>
```

And this VM is reachable by mozart
```
C:\Users\Stratovan>ping mozart.stratovan.com

Pinging mozart.stratovan.com [192.168.100.118] with 32 bytes of data:
Reply from 192.168.100.118: bytes=32 time=1ms TTL=128
Reply from 192.168.100.118: bytes=32 time=1ms TTL=128
Reply from 192.168.100.118: bytes=32 time<1ms TTL=128
Reply from 192.168.100.118: bytes=32 time=1ms TTL=128

Ping statistics for 192.168.100.118:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 1ms, Average = 0ms

C:\Users\Stratovan>
```

I can download the JNLP file using the given URL when I use a browser.

The JNLP files content is
```
<jnlp codebase="http://mozart.stratovan.com:8080/computer/JRR-TEST/" spec="1.0+"><information><title>Agent for JRR-TEST</title><vendor>Jenkins project</vendor><homepage href="https://jenkins-ci.org/"></homepage></information><security><all-permissions></all-permissions></security><resources><j2se version="1.8+"></j2se><jar href="http://mozart.stratovan.com:8080/jnlpJars/remoting.jar"></jar></resources><application-desc main-class="hudson.remoting.jnlp.Main"><argument>ab7d816d18a6e2bc2e1fd7755166ae1fee78da66fe7f5ebe1faa9cfc91598c5d</argument><argument>JRR-TEST</argument><argument>-workDir</argument><argument>C:\Jenkins</argument><argument>-internalDir</argument><argument>remoting</argument><argument>-url</argument><argument>http://mozart.stratovan.com:8080/</argument></application-desc></jnlp>
```

I can start the JNLP file when it's already downloaded, i.e. I can start it if I do
```
javaws c:\Users\Stratovan\Downloads\slave-agent.jnlp
```

**Comment by sclassen** [comment]
Most likely the underlying cause is 

Unexpected end of ZLIB input stream

**Comment by RochaStratovan** [comment]
@sclassen, thank you for the insights.

Is this a message for the developers for resolving the issue, or is this intended for me the user as something I can act upon? If for me, how can I act upon this?

Thank you for your help.

**Comment by sclassen** [comment]
Sorry I was on vacation, so the message was for anybody who could jump in.

From reading the logs it seams to be some kind of network or gzip issue.
Because the error appears during the download & extract of the JNLP file.

These kinds of errors are very hard to diagnose from the distance.
One thing you could try is to disable compression on the server hosting mozart.

You could also give OpenWebStart a try. It is based on icedtea-web but offers some additions and bug fixes.

**Comment by RochaStratovan** [comment]
Good morning. How would one disable the compression from the hosting Jenkins server?

Although, I guess in retrospect this may be moot. I had so much trouble with this I switched over to doing SSH agent starts instead of using iced-tea.

Thank you for your input.

**Comment by Jamila891** [comment]
@RochaStratovan can we close this issue?
