### ISSUE TITLE
IcedTea won't launch jnlp because of non-existent favicon.ico

### ISSUE THREAD

**Issue by catalyst1987** [AdoptOpenJDK/IcedTea-Web#732]
Hello,
    I have switched from the Oracle Java to OpenJDK and IcedTea on Windows 10, but am having an issue launching a jnlp that I tend to use that comes from IBM Support Assistant.  It would work with the Oracle Java, but I can't seem to open it with IcedTea.  It seems to look for a non-existent favicon.ico file and as a result HTTP 400 errors show up in the log and nothing ends up loading.  

```
Following exception: 'Server returned HTTP response code: 400 for URL: https://m3ve-utils.infor.com:10943\favicon.ico' should be harmless, but may help in finding root cause.
java.io.IOException: Server returned HTTP response code: 400 for URL: https://m3ve-utils.infor.com:10943\favicon.ico
	at sun.reflect.GeneratedConstructorAccessor25.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1950)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1945)
	at java.security.AccessController.doPrivileged(AccessController.java:734)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1514)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1488)
	at java.security.AccessController.doPrivileged(AccessController.java:942)
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:984)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1487)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at net.sourceforge.jnlp.util.HttpUtils.consumeAndCloseConnection(HttpUtils.java:67)
	at net.sourceforge.jnlp.util.HttpUtils.consumeAndCloseConnectionSilently(HttpUtils.java:53)
	at net.sourceforge.jnlp.cache.ResourceDownloader.getUrlResponseCodeWithRedirectonResult(ResourceDownloader.java:82)
	at net.sourceforge.jnlp.cache.ResourceDownloader.findBestUrl(ResourceDownloader.java:293)
	at net.sourceforge.jnlp.cache.ResourceDownloader.initializeOnlineResource(ResourceDownloader.java:132)
	at net.sourceforge.jnlp.cache.ResourceDownloader.initializeResource(ResourceDownloader.java:124)
	at net.sourceforge.jnlp.cache.ResourceDownloader.run(ResourceDownloader.java:113)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:823)
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://m3ve-utils.infor.com:10943\favicon.ico
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:92)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1490)
	at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1488)
	at java.security.AccessController.doPrivileged(AccessController.java:942)
	at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:984)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1487)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
	at net.sourceforge.jnlp.cache.ResourceDownloader.getUrlResponseCodeWithRedirectonResult(ResourceDownloader.java:78)
	... 7 more
```

```
java.net.MalformedURLException: For input string: "10943\favicon.ico"
	at java.net.URL.<init>(URL.java:645)
	at java.net.URL.<init>(URL.java:508)
	at java.net.URL.<init>(URL.java:457)
	at net.sourceforge.jnlp.util.UrlUtils.normalizeUrl(UrlUtils.java:132)
	at net.sourceforge.jnlp.util.UrlUtils.normalizeUrl(UrlUtils.java:145)
	at net.sourceforge.jnlp.util.UrlUtils.urlEquals(UrlUtils.java:316)
	at net.sourceforge.jnlp.cache.Resource.equals(Resource.java:457)
	at java.util.AbstractList.indexOf(AbstractList.java:185)
	at net.sourceforge.jnlp.cache.Resource.getResource(Resource.java:129)
	at net.sourceforge.jnlp.cache.ResourceTracker.addResource(ResourceTracker.java:151)
	at net.sourceforge.jnlp.cache.CacheUtil.getCachedResourceFile(CacheUtil.java:113)
	at net.sourceforge.jnlp.cache.CacheUtil.getCachedResourceURL(CacheUtil.java:90)
	at net.sourceforge.jnlp.util.XDesktopEntry.getFavIconUrl(XDesktopEntry.java:638)
	at net.sourceforge.jnlp.util.XDesktopEntry.cacheIcon(XDesktopEntry.java:470)
	at net.sourceforge.jnlp.util.XDesktopEntry.cacheAndGetIconLocation(XDesktopEntry.java:575)
	at net.sourceforge.jnlp.util.WindowsDesktopEntry.<init>(WindowsDesktopEntry.java:43)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at net.sourceforge.jnlp.runtime.ApplicationInstance.addMenuAndDesktopEntries(ApplicationInstance.java:164)
	at net.sourceforge.jnlp.runtime.ApplicationInstance.initialize(ApplicationInstance.java:148)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:532)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:945)
Caused by: java.lang.NumberFormatException: For input string: "10943\favicon.ico"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:222)
	at java.net.URL.<init>(URL.java:640)
	... 23 more
```

Is there a way for me to override this so it doesn't try to look for a favicon or do you suggest any other workarounds?  

Many Thanks.

**Comment by sclassen** [comment]
Can you please attache the jnlp to this issue. Thanks
