### ISSUE TITLE
ELFCLASS32 issue when launching Cisco WebEx

### ISSUE THREAD

**Issue by edent** [AdoptOpenJDK/IcedTea-Web#737]
I am trying to run Cisco's WebEx JNLP on 64bit Linux (Pop!_OS 20.10) using icedtea-web 1.8 (1.8).

Running `javaws cisco.jnlp` pops up a window asking if I trust the remote locations, it downloads a bunch of files, launches a window which stays blank.  In the terminal I see:

```bash
java.lang.UnsatisfiedLinkError: /home/user/.webex/T33_TC/libdbr.so: 
/home/user/.webex/T33_TC/libdbr.so: 
wrong ELF class: ELFCLASS32 (Possible cause: architecture word width mismatch)
```

Is this a problem with my install or with Cisco?

**Comment by edent** [comment]
Here's a more full stack trace:

```
INFO: Begin of log initialization: pathName=/home/user/.webex/T33_TC 1610714530312
###### try to load class DBR in MyCloassLoader2...
Jan 15, 2021 12:42:10 PM DBR <init>
INFO: DBR: Loading native DBR...
OpenJDK 64-Bit Server VM warning: You have loaded library /home/user/.webex/T33_TC/libdbr.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Jan 15, 2021 12:42:10 PM DBR loadNativeDBR
SEVERE: loadNativeDBR: XXX load native library failed
java.lang.UnsatisfiedLinkError: /home/user/.webex/T33_TC/libdbr.so: /home/user/.webex/T33_TC/libdbr.so: wrong ELF class: ELFCLASS32 (Possible cause: architecture word width mismatch)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2640)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at DBR.loadNativeDBR(DBR.java:31)
	at DBR.<init>(DBR.java:105)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at DB.reset(DB.java:182)
	at MySystem.InitSystem(MySystem.java:134)
	at JDownload.loadAndLaunchJC(JDownload.java:967)
	at JDownload.goNext(JDownload.java:778)
	at JDownload.access$200(JDownload.java:55)
	at JDownload$DownloadModel.run(JDownload.java:597)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)

###1 Runtime total memory: 262144000, free memory: 183499792
###2 Runtime total memory: 262144000, free memory: 183499792
###### try to load class DBR in MyCloassLoader2...
Jan 15, 2021 12:42:10 PM DBR <init>
INFO: DBR: Loading native DBR...
Jan 15, 2021 12:42:10 PM DBR loadNativeDBR
SEVERE: loadNativeDBR: XXX load native library failed
java.lang.UnsatisfiedLinkError: /home/user/.webex/T33_TC/libdbr.so: /home/user/.webex/T33_TC/libdbr.so: wrong ELF class: ELFCLASS32 (Possible cause: architecture word width mismatch)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2640)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at DBR.loadNativeDBR(DBR.java:31)
	at DBR.<init>(DBR.java:105)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at DB.reset(DB.java:182)
	at MySystem.InitSystem(MySystem.java:134)
	at JDownload.loadAndLaunchJC(JDownload.java:967)
	at JDownload.goNext(JDownload.java:778)
	at JDownload.access$200(JDownload.java:55)
	at JDownload$DownloadModel.run(JDownload.java:597)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)

###1 Runtime total memory: 262144000, free memory: 183304344
###2 Runtime total memory: 262144000, free memory: 183304344
###### try to load class DBR in MyCloassLoader2...
Jan 15, 2021 12:42:10 PM DBR <init>
INFO: DBR: Loading native DBR...
Jan 15, 2021 12:42:10 PM DBR loadNativeDBR
SEVERE: loadNativeDBR: XXX load native library failed
java.lang.UnsatisfiedLinkError: /home/user/.webex/T33_TC/libdbr.so: /home/user/.webex/T33_TC/libdbr.so: wrong ELF class: ELFCLASS32 (Possible cause: architecture word width mismatch)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2640)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at DBR.loadNativeDBR(DBR.java:31)
	at DBR.<init>(DBR.java:105)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at DB.reset(DB.java:182)
	at MySystem.InitSystem(MySystem.java:134)
	at JDownload.loadAndLaunchJC(JDownload.java:967)
	at JDownload.goNext(JDownload.java:778)
	at JDownload.access$200(JDownload.java:55)
	at JDownload$DownloadModel.run(JDownload.java:597)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)

Jan 15, 2021 12:42:10 PM utils.JCKit put
INFO: ### cache put key=JAPPLET_INST
	value=JDownload[panel0,0,0,800x461,invalid,layout=java.awt.BorderLayout,rootPane=javax.swing.JRootPane[,0,0,800x461,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
Jan 15, 2021 12:42:10 PM utils.JCKit put
INFO: ### cache put key=ServiceType
	value=TC
Jan 15, 2021 12:42:10 PM JDownload getParameter
INFO: JDownload
Jan 15, 2021 12:42:10 PM utils.JCKit put
INFO: ### cache put key=STRING_CONFID
	value=true
Jan 15, 2021 12:42:10 PM JDownload getParameter
INFO: JDownload
Jan 15, 2021 12:42:10 PM utils.JCKit put
INFO: ### cache put key=WMEOption
	value=1
Resource: atres
Resource: atres_en
Resource: atres_en_US
Resource: atres_en_GB
Exception in thread "Timer-0" java.lang.ExceptionInInitializerError
	at TCServiceManager.launch(TCServiceManager.java:422)
	at jmeetingclient.init(jmeetingclient.java:74)
	at JDownload.loadAndLaunchJC(JDownload.java:986)
	at JDownload.goNext(JDownload.java:778)
	at JDownload.access$200(JDownload.java:55)
	at JDownload$DownloadModel.run(JDownload.java:597)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
Caused by: java.util.MissingResourceException: Can't find bundle for base name atres, locale en_US
	at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1556)
	at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:932)
	at AtResLoader.<clinit>(AtResLoader.java:6)
	... 8 more
Caused by: java.lang.NullPointerException
	at java.base/java.lang.Class.isAssignableFrom(Native Method)
	at java.base/java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:3173)
	at java.base/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1994)
	at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1776)
	at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1728)
	at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1728)
	at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1662)
	... 12 more
Jan 15, 2021 12:44:38 PM JDownload destroy
INFO: destroy.
java.lang.Exception: destroy debug
	at JDownload.destroy(JDownload.java:1358)
	at JDownload$3.windowClosed(JDownload.java:879)
	at java.desktop/java.awt.AWTEventMulticaster.windowClosed(AWTEventMulticaster.java:367)
	at java.desktop/java.awt.Window.processWindowEvent(Window.java:2081)
	at java.desktop/javax.swing.JFrame.processWindowEvent(JFrame.java:298)
	at java.desktop/java.awt.Window.processEvent(Window.java:2037)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by sclassen** [comment]
This looks like there is an issue with bits and native libs:
https://stackoverflow.com/questions/6172105/wrong-elf-class-elfclass32

OpenWebStart will always use a 64 bit JVM if the operating system is 64bit

**Comment by edent** [comment]
Thanks. Is this something I can fix on my machine?

**Comment by sclassen** [comment]
sorry for the late reply.
If you can find a 64bit version of the libdbr and have that sitting in the libpath of the JRE that should do the trick.

Also there is currently a bug which you could exploid.
OpenWebStart does not detect the architecture of a JVM correctly and as a consequence all JVMs are detected as 64bit.
You can therefore install a 32-bit JVM on your computer and add it to the JVM manager (in the settings).
If you the disable all other JVMs and also disable the download of new JVMs your application will be started with that specific 32-bit JVM.
We will not fix this bug until we have a proper solution to specify if an application should be run with a 32 or a 64 bit JVM

**Comment by sclassen** [comment]
Open Web Start supports now a flag in the JNLP to enforce a 32bit JVM:

```
<java version="1.8*" require-32bit="true" ... />
```
