### ISSUE TITLE
Fatal: Read Error: Could not read or parse the JNLP file.

### ISSUE THREAD

**Issue by fredo-m** [AdoptOpenJDK/IcedTea-Web#768]
Hi,

A French public structure provides a portal for submitting responses to calls for tenders from municipalities. 

They provide a test page:
https://marches.megalis.bretagne.bzh/index.php?page=entreprise.DiagnosticPoste&callFrom=entreprise

The portal uses a jnlp script.

To use this portal, I have a virtual machine with an old Windows XP, an old firefox and the java plugin, because Java no longer works with Windows 10 and recent firefox.

On my Linux workstation, when I test this script, icedtea starts well but produces an error. I don't know if this is possible, but I would rather access this portal from my Linux workstation and IcedTea-Web than from a Windows XP virtual machine.

Regards.

The error messages are:

net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file. You can try to download this file manually and send it as bug report to IcedTea-Web team.
	at java.desktop/net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)
	at java.desktop/net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)
	at java.desktop/net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)
	at java.desktop/net.sourceforge.jnlp.runtime.Boot.run(Boot.java:270)
	at java.desktop/net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/net.sourceforge.jnlp.runtime.Boot.main(Boot.java:210)
Caused by: java.io.IOException: java.lang.NullPointerException: name can't be null
	at java.desktop/net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:319)
	at java.desktop/net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:241)
	at java.desktop/net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)
	at java.desktop/net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)
	at java.desktop/net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)
	at java.desktop/net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:453)
	... 6 more
Caused by: java.lang.NullPointerException: name can't be null
	at java.base/java.io.FilePermission.init(FilePermission.java:321)
	at java.base/java.io.FilePermission.<init>(FilePermission.java:488)
	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:661)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:146)
	at java.desktop/net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:317)
	... 11 more

The output of the java console:

net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file. You can try to download this file manually and send it as bug report to IcedTea-Web team.     at java.desktop/net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)     at java.desktop/net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)     at java.desktop/net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)     at java.desktop/net.sourceforge.jnlp.runtime.Boot.run(Boot.java:270)     at java.desktop/net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)     at java.base/java.security.AccessController.doPrivileged(Native Method)     at java.desktop/net.sourceforge.jnlp.runtime.Boot.main(Boot.java:210) Caused by: java.io.IOException: java.lang.NullPointerException: name can't be null     at java.desktop/net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:319)     at java.desktop/net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:241)     at java.desktop/net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)     at java.desktop/net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)     at java.desktop/net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)     at java.desktop/net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:453)     ... 6 more Caused by: java.lang.NullPointerException: name can't be null     at java.base/java.io.FilePermission.init(FilePermission.java:321)     at java.base/java.io.FilePermission.<init>(FilePermission.java:488)     at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:661)     at java.base/java.io.FileInputStream.<init>(FileInputStream.java:146)     at java.desktop/net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:317)     ... 11 more 
netx: Read Error: Could not read or parse the JNLP file. (java.lang.NullPointerException: name can't be null (name can't be null))
Removed sun.net.www.protocol.https.DelegateHttpsURLConnection:https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature
Disconnecting sun.net.www.protocol.https.DelegateHttpsURLConnection:https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature
java.io.EOFException: Unexpected end of ZLIB input stream     at java.base/java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:245)     at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)     at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:118)     at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)     at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)     at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)     at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)     at java.desktop/net.sourceforge.jnlp.cache.ResourceDownloader.uncompressGzip(ResourceDownloader.java:488)     at java.desktop/net.sourceforge.jnlp.cache.ResourceDownloader.downloadGZipFile(ResourceDownloader.java:405)     at java.desktop/net.sourceforge.jnlp.cache.ResourceDownloader.downloadResource(ResourceDownloader.java:362)     at java.desktop/net.sourceforge.jnlp.cache.ResourceDownloader.run(ResourceDownloader.java:118)     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)     at java.base/java.lang.Thread.run(Thread.java:834) 
Extracting gzip: https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature to https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature
isCurrent:isCached false
Downloading file: https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature into: /home/XXXX/.cache/icedtea-web/cache/0/https/marches.megalis.bretagne.bzh/crypto/signature/outilTest.serveurCryptoURLPublique_https_/marches.megalis.bretagne.bzh/crypto/signature
Downloading https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature using https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature (encoding : gzip)
Selected proxies: [DIRECT]
Browser selected proxies: [DIRECT]
Browser proxy option "4" (Automatic) not supported yet.
Selecting proxy for: https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature
done https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature
Adding sun.net.www.protocol.https.DelegateHttpsURLConnection:https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature
Connecting https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature
Removed sun.net.www.protocol.https.DelegateHttpsURLConnection:https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature
Disconnecting sun.net.www.protocol.https.DelegateHttpsURLConnection:https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature
isCurrent: https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature = false
isCurrent:isCached false
done https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature
Adding sun.net.www.protocol.https.DelegateHttpsURLConnection:https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature
Connecting https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature
best url for location=https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature state=PRECONNECT CONNECTING PREDOWNLOAD PROCESSING is https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature by HEAD
Removed sun.net.www.protocol.https.DelegateHttpsURLConnection:https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature
Disconnecting sun.net.www.protocol.https.DelegateHttpsURLConnection:https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature
Key : Content-Type ,Value : [application/x-java-jnlp-file;charset=ISO-8859-1]
Key : Content-Language ,Value : [fr-FR]
Key : Content-Length ,Value : [2091]
Key : Set-Cookie ,Value : [ROUTEPATH=.node3; path=/, JSESSIONID=66221D04122B1C53308F502211FBB82A;path=/signature/;HttpOnly]
Key : Content-Disposition ,Value : [attachment; filename="Outil de test de configuration.jnlp"]
Key : Access-Control-Allow-Credentials ,Value : [true]
Key : Strict-Transport-Security ,Value : [max-age=31536000; includeSubDomains]
Key : Date ,Value : [Fri, 19 Feb 2021 16:20:42 GMT]
Key : Connection ,Value : [Keep-Alive]
Key : Access-Control-Allow-Origin ,Value : [https://socle.megalis.bretagne.bzh]
Key : Server ,Value : [Apache TomEE]
Key : null ,Value : [HTTP/1.1 200]
Key : Keep-Alive ,Value : [timeout=5, max=1000]
Selected proxies: [DIRECT]
Browser selected proxies: [DIRECT]
Browser proxy option "4" (Automatic) not supported yet.
Selecting proxy for: socket://marches.megalis.bretagne.bzh:443
Selected proxies: [DIRECT]
Browser selected proxies: [DIRECT]
Browser proxy option "4" (Automatic) not supported yet.
Selecting proxy for: https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature
done https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature
Adding sun.net.www.protocol.https.DelegateHttpsURLConnection:https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature
Connecting https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature
All possible urls for location=https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature state=PRECONNECT CONNECTING PREDOWNLOAD PROCESSING : [https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature, https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature]
Finding best URL for: https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature : DownloadOptions[use pack: false; use version: false]
good - your JRE - 11.0.10 - match requested JRE - 1.8+
Acceptable vendor tag found, contains: Atexo
Acceptable title tag found, contains: Signature Electronique
Jars not ready to provide attribute Application-Name
Description: null
Homepage: null
line: 36

line: 35
line: 34 </jnlp>
line: 33    <update check="background"></update>
line: 32    </application-desc>
line: 31        <argument>https://marches.megalis.bretagne.bzh/crypto/signature/signatureXades</argument>
line: 30    <application-desc name="Signature" main-class="com.atexo.serveurCryptographique.jnlp.ApplicationCryptographieTest">
line: 29
line: 28    </security>
line: 27        <all-permissions></all-permissions>
line: 26    <security>
line: 25
line: 24    </resources>
line: 23         <jar href="https://marches.megalis.bretagne.bzh/crypto/signature/resources/dss-model.jar" main="false"></jar>       
line: 22        <jar href="https://marches.megalis.bretagne.bzh/crypto/signature/resources/bcpkix-jdk15on.jar" main="false"></jar> 
line: 21        <jar href="https://marches.megalis.bretagne.bzh/crypto/signature/resources/bcmail-jdk15on.jar" main="false"></jar>
line: 20        <jar href="https://marches.megalis.bretagne.bzh/crypto/signature/resources/bcprov-jdk15on.jar" main="false"></jar>
line: 19        <jar href="https://marches.megalis.bretagne.bzh/crypto/signature/resources/logback-core.jar" main="false"></jar>
line: 18        <jar href="https://marches.megalis.bretagne.bzh/crypto/signature/resources/logback-classic.jar" main="false"></jar>
line: 17        <jar href="https://marches.megalis.bretagne.bzh/crypto/signature/resources/jcl-over-slf4j.jar" main="false"></jar>
line: 16        <jar href="https://marches.megalis.bretagne.bzh/crypto/signature/resources/slf4j.jar" main="false"></jar>
line: 15        <jar href="https://marches.megalis.bretagne.bzh/crypto/signature/resources/cryptographie-lib.jar" main="false"></jar>
line: 14        <jar href="https://marches.megalis.bretagne.bzh/crypto/signature/resources/signature-client.jar" main="true"></jar>
line: 13        <j2se version="1.8+" initial-heap-size="64m" max-heap-size="1024m" java-vm-args="-XX:+IgnoreUnrecognizedVMOptions --add-modules=java.xml.bind"></j2se>
line: 12       
line: 11    <resources>
line: 10    </information>
line: 9
line: 8        <offline-allowed></offline-allowed>
line: 7        <vendor>Atexo</vendor>
line: 6        <title>Signature Electronique</title>
line: 5    <information>
line: 4 <jnlp spec="1.0+" href="https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature" xmlns="http://www.w3.org/1999/xhtml">
line: 3
line: 2
<?xml version="1.0" standalone="yes"?>
Using MalformedXMLParser
JNLP file location: /tmp/mozilla_XXXX0/Outil de test de configuration-2.jnlp
Proceeding with jnlp
Read 2786 entries from Firefox's preferences
Found preferences file: /home/XXXX/.mozilla/firefox/XXXX.default/prefs.js
Using firefox's profiles file: /home/XXXX/.mozilla/firefox/profiles.ini
Starting security dialog thread
Forcing of offline set to: false
OK: Directory /home/XXXX/.cache/icedtea-web/tmp did not exist but has been created
OK: Directory /home/XXXX/.cache/icedtea-web/pcache did not exist but has been created
OK: Directory /home/XXXX/.cache/icedtea-web/cache did not exist but has been created
WARNING: key deployment.system.cachedir has no value, setting to default value
java.io.FileNotFoundException: /home/XXXX/.config/icedtea-web/deployment.properties (Aucun fichier ou dossier de ce type)     at java.base/java.io.FileInputStream.open0(Native Method)     at java.base/java.io.FileInputStream.open(FileInputStream.java:219)     at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)     at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)     at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)     at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184)     at java.base/java.net.URL.openStream(URL.java:1140)     at java.desktop/net.sourceforge.jnlp.config.DeploymentConfiguration.loadComments(DeploymentConfiguration.java:928)     at java.desktop/net.sourceforge.jnlp.config.DeploymentConfiguration.load(DeploymentConfiguration.java:385)     at java.desktop/net.sourceforge.jnlp.config.DeploymentConfiguration.load(DeploymentConfiguration.java:347)     at java.desktop/net.sourceforge.jnlp.config.DeploymentConfiguration.load(DeploymentConfiguration.java:325)     at java.desktop/net.sourceforge.jnlp.runtime.JNLPRuntime$DeploymentConfigurationHolder.initConfiguration(JNLPRuntime.java:457)     at java.desktop/net.sourceforge.jnlp.runtime.JNLPRuntime$DeploymentConfigurationHolder.<clinit>(JNLPRuntime.java:452)     at java.desktop/net.sourceforge.jnlp.runtime.JNLPRuntime.getConfiguration(JNLPRuntime.java:487)     at java.desktop/net.sourceforge.jnlp.config.DirectoryValidator.<init>(DirectoryValidator.java:226)     at java.desktop/net.sourceforge.jnlp.config.DeploymentConfiguration.move14AndOlderFilesTo15Structure(DeploymentConfiguration.java:886)     at java.desktop/net.sourceforge.jnlp.config.DeploymentConfiguration.move14AndOlderFilesTo15StructureCatched(DeploymentConfiguration.java:786)     at java.desktop/net.sourceforge.jnlp.runtime.Boot.main(Boot.java:121) 
No User level deployment.properties found.
java.io.FileNotFoundException: /home/XXXX/.config/icedtea-web/deployment.properties (Aucun fichier ou dossier de ce type)     at java.base/java.io.FileInputStream.open0(Native Method)     at java.base/java.io.FileInputStream.open(FileInputStream.java:219)     at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)     at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)     at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)     at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:184)     at java.base/java.net.URL.openStream(URL.java:1140)     at java.desktop/net.sourceforge.jnlp.config.DeploymentConfiguration.parsePropertiesFile(DeploymentConfiguration.java:711)     at java.desktop/net.sourceforge.jnlp.config.DeploymentConfiguration.findSystemConfigFile(DeploymentConfiguration.java:533)     at java.desktop/net.sourceforge.jnlp.config.DeploymentConfiguration.load(DeploymentConfiguration.java:345)     at java.desktop/net.sourceforge.jnlp.config.DeploymentConfiguration.load(DeploymentConfiguration.java:325)     at java.desktop/net.sourceforge.jnlp.runtime.JNLPRuntime$DeploymentConfigurationHolder.initConfiguration(JNLPRuntime.java:457)     at java.desktop/net.sourceforge.jnlp.runtime.JNLPRuntime$DeploymentConfigurationHolder.<clinit>(JNLPRuntime.java:452)     at java.desktop/net.sourceforge.jnlp.runtime.JNLPRuntime.getConfiguration(JNLPRuntime.java:487)     at java.desktop/net.sourceforge.jnlp.config.DirectoryValidator.<init>(DirectoryValidator.java:226)     at java.desktop/net.sourceforge.jnlp.config.DeploymentConfiguration.move14AndOlderFilesTo15Structure(DeploymentConfiguration.java:886)     at java.desktop/net.sourceforge.jnlp.config.DeploymentConfiguration.move14AndOlderFilesTo15StructureCatched(DeploymentConfiguration.java:786)     at java.desktop/net.sourceforge.jnlp.runtime.Boot.main(Boot.java:121) 
Ico provider registered correctly.
cache: /home/XXXX/.cache/icedtea-web file exists:false
config: /home/XXXX/.config/icedtea-web file exists: true
System is already following XDG .cache and .config specifications

**Comment by sclassen** [comment]
I tried this with the newest release of OpenWebStart. And it works as long as you use a JVM which includes JavaFX
see https://github.com/karakun/OpenWebStart

**Comment by andreipiv** [comment]
how are the files served on the server -- are there any checks? Also try latest icedTea (see releases) 

https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature is failing to download

**Comment by fredo-m** [comment]
Le 07/04/2021 à 00:10, andreipiv a écrit :
> how are the files served on the server -- are there any checks? Also try 
> latest icedTea (see releases)

Thank you for your reply.

I do not manage the server, I am just a user of this service. I don't 
know how its handled the files on the server.


> https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature 
> is failing to download

On my PC the link works, I get the "Outil de test de configuration.jnlp" 
file which contains:

<?xml version="1.0" encoding="UTF-8"?>
<jnlp spec="1.0+" 
href="https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature">
     <information>
         <title>Signature Electronique</title>
         <vendor>Atexo</vendor>
         <offline-allowed/>

     </information>
     <resources>
         
         <j2se version="1.8+" initial-heap-size="64m" 
max-heap-size="1024m" java-vm-args="-XX:+IgnoreUnrecognizedVMOptions 
--add-modules=java.xml.bind" />
         <jar 
href="https://marches.megalis.bretagne.bzh/crypto/signature/resources/signature-client.jar" 
main="true"/>
         <jar 
href="https://marches.megalis.bretagne.bzh/crypto/signature/resources/cryptographie-lib.jar" 
main="false"/>
         <jar 
href="https://marches.megalis.bretagne.bzh/crypto/signature/resources/slf4j.jar" 
main="false"/>
         <jar 
href="https://marches.megalis.bretagne.bzh/crypto/signature/resources/jcl-over-slf4j.jar" 
main="false"/>
         <jar 
href="https://marches.megalis.bretagne.bzh/crypto/signature/resources/logback-classic.jar" 
main="false"/>
         <jar 
href="https://marches.megalis.bretagne.bzh/crypto/signature/resources/logback-core.jar" 
main="false"/>
         <jar 
href="https://marches.megalis.bretagne.bzh/crypto/signature/resources/bcprov-jdk15on.jar" 
main="false"/>
         <jar 
href="https://marches.megalis.bretagne.bzh/crypto/signature/resources/bcmail-jdk15on.jar" 
main="false"/>
         <jar 
href="https://marches.megalis.bretagne.bzh/crypto/signature/resources/bcpkix-jdk15on.jar" 
main="false"/>
		<jar 
href="https://marches.megalis.bretagne.bzh/crypto/signature/resources/dss-model.jar" 
main="false"/>
     </resources>

     <security>
         <all-permissions/>
     </security>

     <application-desc name="Signature" 
main-class="com.atexo.serveurCryptographique.jnlp.ApplicationCryptographieTest">
 
<argument>https://marches.megalis.bretagne.bzh/crypto/signature/signatureXades</argument>
     </application-desc>
     <update check="background"/>
</jnlp>



Regards.
-- 
==============================================
|              FRÉDÉRIC MASSOT               |
|     http://www.juliana-multimedia.com      |
|   ***@***.***   |
| +33.(0)2.97.54.77.94  +33.(0)6.67.19.95.69 |
===========================Debian=GNU/Linux===

**Comment by andreipiv** [comment]
java.io.EOFException: Unexpected end of ZLIB input stream 

this is the issue. https://github.com/AdoptOpenJDK/IcedTea-Web/issues/602 was a similar issue...

Looks like this is fixed in the version that OWS uses (different stream)

**Comment by douph1** [comment]
The source error "Unexpected end of ZLIB input stream" seems not have been fixed in ITW in #602 .. just a workaround : use OWS

I have the same error with icedtea-web 1.8.6 :
>Extracting gzip: https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?>serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature to >https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature
java.io.EOFException: Unexpected end of ZLIB input stream
        at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
        at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at java.io.FilterInputStream.read(FilterInputStream.java:107)
        at net.sourceforge.jnlp.cache.ResourceDownloader.uncompressGzip(ResourceDownloader.java:493)
        at net.sourceforge.jnlp.cache.ResourceDownloader.downloadGZipFile(ResourceDownloader.java:410)
        at net.sourceforge.jnlp.cache.ResourceDownloader.downloadResource(ResourceDownloader.java:367)
        at net.sourceforge.jnlp.cache.ResourceDownloader.run(ResourceDownloader.java:118)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)


For this failure : the gzip stream seems to be good : 
>curl -v -H "Accept-Encoding: gzip" https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature --output - | zcat

ok

>curl -v --compressed -H "Accept-Encoding: gzip" https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature

ok 

>curl -q -H "Accept-Encoding: gzip" https://marches.megalis.bretagne.bzh/crypto/signature/outilTest?serveurCryptoURLPublique=https://marches.megalis.bretagne.bzh/crypto/signature --output file.gz && gunzip -vt file.gz

ok

I think ITW want to decode it as a gzip stream wich is not as I don't see "Content-Encoding: gzip" in the response

>Key : Keep-Alive ,Value : [timeout=5, max=1000]
Key : null ,Value : [HTTP/1.1 200]
Key : Server ,Value : [Apache TomEE]
Key : Access-Control-Allow-Origin ,Value : [https://socle.megalis.bretagne.bzh]
Key : Connection ,Value : [Keep-Alive]
Key : Date ,Value : [Wed, 07 Apr 2021 12:39:31 GMT]
Key : Strict-Transport-Security ,Value : [max-age=31536000; includeSubDomains]
Key : Access-Control-Allow-Credentials ,Value : [true]
Key : Content-Disposition ,Value : [attachment; filename="Outil de test de configuration.jnlp"]
Key : Set-Cookie ,Value : [ROUTEPATH=.node2; path=/, JSESSIONID=0E0D4352F99AF19F7DC2FE41B8203201;path=/signature/;HttpOnly]
Key : Content-Length ,Value : [2091]
Key : Content-Language ,Value : [fr-FR]
Key : Content-Type ,Value : [application/x-java-jnlp-file;charset=ISO-8859-1]
