### ISSUE TITLE
Doesn't work on http://sweethome3d.com (InvocationTargetException)

### ISSUE THREAD

**Issue by AndreasEhret** [AdoptOpenJDK/IcedTea-Web#77]
This issue was imported from bugzilla with bugzilla2github
# Bugzilla Bug Referenze: [3552](https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3552)
Date: 2018-03-29 14:03:00 +0000
From: Alexandr Gavriliuc &lt;<gavriliuk>&gt;
To:   JiriVanek &lt;<jvanek>&gt;
CC:   unassigned, vincent.privat

Last updated: 2018-04-23 09:27:57 +0000

## Comment 16585
Date: 2018-03-29 14:03:26 +0000
From: Alexandr Gavriliuc &lt;<gavriliuk>&gt;

Created attachment 1675
                Screenshot

                Opening the page http://www.sweethome3d.com/ru/SweetHome3DOnline.jsp
                I twice press "Yes" for allowing app to run,
                but always receive the following error:

                Can't start applet
                Exception java.lang.reflect.InvocationTargetException

                and nothing more on the white background
            

> Attached file: error-on-sweethome3d.png (image/png, 114070 bytes)
> Description:   Screenshot

## Comment 16586
Date: 2018-03-29 14:19:12 +0000
From: JiriVanek &lt;<jvanek>&gt;

Plugin is dead. And it is browsers who are turning it down. Please run the application via javaws:
                http://www.sweethome3d.com/download.jsp -> Launch Sweet Home 3D with Java Web Start

                Or directly:

                javaws http://www.sweethome3d.com/SweetHome3D.jnlp

                Sweethome is one of the release criteria of javaws. Once you confirm it works, please close this bug.

                If you are running with jdk9 and higher, you may see other issues. But jdk9/10 was not yet fully
                accepted by many usptreams. Recommended jdk is jdk8. ITW runs also with othr jdks.. but...
            

## Comment 16645
Date: 2018-04-18 20:56:14 +0000
From: vincent.privat

On Windows 10 + ITW 1.8.pre + JDK8u172 I have the following error:

                Exception in thread "AWT-EventQueue-1" java.lang.ExceptionInInitializerError
                at com.eteks.sweethome3d.swing.HomePane.checkClipboardContainsHomeItemsOrFiles(Unknown Source)
                at com.eteks.sweethome3d.swing.HomePane.access$2800(Unknown Source)
                at com.eteks.sweethome3d.swing.HomePane$66.flavorsChanged(Unknown Source)
                at com.eteks.sweethome3d.swing.HomePane.addClipboardListener(Unknown Source)
                at com.eteks.sweethome3d.swing.HomePane.<init>(Unknown Source)
                at com.eteks.sweethome3d.swing.SwingViewFactory.createHomeView(Unknown Source)
                at com.eteks.sweethome3d.viewcontroller.HomeController.getView(Unknown Source)
                at com.eteks.sweethome3d.HomeFramePane.<init>(Unknown Source)
                at com.eteks.sweethome3d.HomeFrameController.getView(Unknown Source)
                at com.eteks.sweethome3d.HomeFrameController.displayView(Unknown Source)
                at com.eteks.sweethome3d.SweetHome3D$4.collectionChanged(Unknown Source)
                at com.eteks.sweethome3d.model.CollectionChangeSupport.fireCollectionChanged(Unknown Source)
                at com.eteks.sweethome3d.model.HomeApplication.addHome(Unknown Source)
                at com.eteks.sweethome3d.SweetHome3D.showDefaultHomeFrame(Unknown Source)
                at com.eteks.sweethome3d.SweetHome3D.start(Unknown Source)
                at com.eteks.sweethome3d.SweetHome3D$5.run(Unknown Source)
                at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
                at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
                at java.awt.EventQueue.access$500(EventQueue.java:97)
                at java.awt.EventQueue$3.run(EventQueue.java:709)
                at java.awt.EventQueue$3.run(EventQueue.java:703)
                at java.security.AccessController.doPrivileged(Native Method)
                at
                java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
                at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
                at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
                at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
                at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
                at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
                at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
                at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
                Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException:
                com/eteks/sweethome3d/swing/HomeTransferableList
                at com.eteks.sweethome3d.swing.HomeTransferableList.<clinit>(Unknown Source)
                ... 30 more
                Caused by: java.lang.ClassNotFoundException: com/eteks/sweethome3d/swing/HomeTransferableList
                at java.lang.Class.forName0(Native Method)
                at java.lang.Class.forName(Class.java:348)
                at java.awt.datatransfer.DataFlavor.tryToLoadClass(DataFlavor.java:163)
                at java.awt.datatransfer.DataFlavor.initialize(DataFlavor.java:537)
                at java.awt.datatransfer.DataFlavor.<init>(DataFlavor.java:501)
                ... 31 more
            

## Comment 16653
Date: 2018-04-23 09:27:57 +0000
From: JiriVanek &lt;<jvanek>&gt;

This is first time I see this exception. Will take some time to get to the machine with windows.

**Comment by lherschi** [comment]
The program works for me under windows with ITW 1.8.3, but only when I turn on the java console.
