### ISSUE TITLE
UTF-8 BOM encoded JNLP not working on Windows

### ISSUE THREAD

**Issue by andreipiv** [AdoptOpenJDK/IcedTea-Web#790]
There was a recent fix for UTF-8 JNLP files, but another issue remains:

If the JNLP is encoded with UTF-8 with BOM, it fails to parse (it seems we don't check for the BOM bytes 0xEF ,0xBB, 0xBF):

```
net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file. You can try to download this file manually and send it as bug report to IcedTea-Web team.
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)
	at net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)
	at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:274)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:214)
Caused by: net.sourceforge.jnlp.ParseException: MALFORMED MALFORMED; Invalid XML document syntax.
	at net.sourceforge.jnlp.XMLParser.getRootNode(XmlParser.java:118)
	at net.sourceforge.jnlp.MalformedXMLParser.getRootNode(MalformedXMLParser.java:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.sourceforge.jnlp.Parser.getRootNode(Parser.java:1380)
	at net.sourceforge.jnlp.JNLPFile.parse(JNLPFile.java:867)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:233)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:453)
	... 6 more
Caused by: net.sourceforge.nanoxml.XMLParseException: XML Parse Exception during parsing of a html element at line 3: Expected: /
	at net.sourceforge.nanoxml.XMLElement.expectedInput(XMLElement.java:1185)
	at net.sourceforge.nanoxml.XMLElement.scanElement(XMLElement.java:1038)
	at net.sourceforge.nanoxml.XMLElement.scanElement(XMLElement.java:1019)
	at net.sourceforge.nanoxml.XMLElement.parseFromReader(XMLElement.java:514)
	at net.sourceforge.nanoxml.XMLElement.parseFromReader(XMLElement.java:466)
	at net.sourcefo
```

How to reproduce:

1. take any JNLP file
2. Change Encoding to UTF-8 BOM (I used Notepad++)
3. JNLP should parse but it doesn't :(

**Comment by sclassen** [comment]
Which version of ITW/OWS are you using?

**Comment by andreipiv** [comment]
I was using 1.8.4 and then upgraded to 1.8.6

**Comment by sclassen** [comment]
The parser does not solely rely on the BOM but also on the encoding specified in the xml tag.
Can you attach the JNLP for further debugging

**Comment by andreipiv** [comment]
I don't have a public-facing server / JNLP, but I can provide one (it'll fail parsing but won't be able to update / download resources). I would suggest using a JNLP that you know works and change encoding to UTF-8 BOM:

![image](https://user-images.githubusercontent.com/45495450/115039746-b98d5200-9e9e-11eb-9896-0980f7c4f980.png)

**Comment by sclassen** [comment]
Yes I have understand that. But OWS is also looking at the first few lines in the JNLP to determine the encoding.
So in order to reproduce this I would need the content of the JNLP file. At least until `<jnlp`
