### ISSUE TITLE
Empty "Security Warning" dialog before application runs

### ISSUE THREAD

**Issue by aldonogueira** [AdoptOpenJDK/IcedTea-Web#793]
It seems that icedTea Web would show me a security warning right before the application opens, but then something went wrong and the window was empty. Actually, it's a really small window with just the title "Security Warning" and when you resize it, you see there is no content. I activated the logs and found this while the window was open:
```
Application title was not found in manifest. Check with application vendor
Acceptable title tag found, contains: pronav-client
java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1349)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1324)
	at net.sourceforge.swing.SwingUtils.callOnAppContext(SwingUtils.java:149)
	at net.sourceforge.swing.SwingUtils.invokeAndWait(SwingUtils.java:161)
	at net.sourceforge.jnlp.security.SecurityDialog.initDialog(SecurityDialog.java:239)
	at net.sourceforge.jnlp.security.SecurityDialog.<init>(SecurityDialog.java:127)
	at net.sourceforge.jnlp.security.SecurityDialogMessageHandler.handleMessage(SecurityDialogMessageHandler.java:114)
	at net.sourceforge.jnlp.security.SecurityDialogMessageHandler.run(SecurityDialogMessageHandler.java:94)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at net.sourceforge.jnlp.security.dialogs.AccessWarningPane.addComponents(AccessWarningPane.java:142)
	at net.sourceforge.jnlp.security.dialogs.AccessWarningPane.<init>(AccessWarningPane.java:111)
	at net.sourceforge.jnlp.security.SecurityDialog.getPanel(SecurityDialog.java:343)
	at net.sourceforge.jnlp.security.SecurityDialog.getPanel(SecurityDialog.java:329)
	at net.sourceforge.jnlp.security.SecurityDialog.getPanel(SecurityDialog.java:322)
	at net.sourceforge.jnlp.security.SecurityDialog.installPanel(SecurityDialog.java:370)
	at net.sourceforge.jnlp.security.SecurityDialog.access$000(SecurityDialog.java:80)
	at net.sourceforge.jnlp.security.SecurityDialog$1.run(SecurityDialog.java:242)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

initial value panel is null
Setting value:null
Returning value:null
```
I have found [the line where this nullpointer happens](https://github.com/AdoptOpenJDK/IcedTea-Web/blob/fed2f5b696618452c2432fa1879f31dc1eaef4ae/netx/net/sourceforge/jnlp/security/dialogs/AccessWarningPane.java#L142). It looks like the source location is null.  

After this little window is closed, the application opens normally, but it may be confusing for some users.  

The test was done with Windows 10 and AdoptOpenJDK 8u282b08 which installed IcedTeaWeb 1.8.4

**Comment by sclassen** [comment]
Is the application available for reproducing the issue?

**Comment by aldonogueira** [comment]
Unfortunately I can't provide the application, it's proprietary, but I found something. Comparing the JNLP file with others, I discovered there was an information missing, the homepage. Adding `<homepage href="index.html" />` to the file apparently solved the problem. That security warning window is shown properly. It asks the user if it's allowed to create shortcuts on the desktop.

So I guess you can reproduce the bug with something like this:
```xml
<?xml version="1.0" encoding="utf-8"?>

<jnlp spec="1.0+" codebase="http://...">
  <information>
    <title>app-title</title>
    <vendor>Vendor Name</vendor>
    <description>App description</description>
    <icon href="resources/images/app-icon-jnlp.jpg"/>
    <shortcut>
      <desktop/>
      <menu submenu="AppName"/>
    </shortcut>
  </information>
...
```
Notice there is no homepage above.

**Comment by sclassen** [comment]
We will give it a shot. But out of the box it kind of sounds arbitrary that this would be the cause.

**Comment by aldonogueira** [comment]
It seems consistent. I added the shortcut tag and removed the homepage from another JNLP, which didn't have this problem before. The same empty Security Warning appeared

**Comment by sclassen** [comment]
OK, we will give this combination a try and see if we can reproduce

**Comment by janakmulani** [comment]
@aldonogueira I tested with the following jnlp file. I did not get any "empty" security dialog. I do get a security dialog because `href` attribute is missing in the `jnlp` tag. But that is not "empty". 

```
<jnlp spec="1.0+" codebase="http://localhost:8080/jnlp">
    <information>
        <title>WebStartTest</title>
        <vendor>Karakun AG</vendor>
<!--        <homepage href="index.html" />-->
        <description>App description</description>
      
        <shortcut>
            <desktop/>
            <menu submenu="EmptyDlg"/>
        </shortcut>
    </information>

    <security>
        <all-permissions/>
    </security>
    <resources>
        <java version="1.8+" />
        <jar href="generated-jars/xyz.jar"/>
    </resources>
    <application-desc main-class="xyz.WebStartTest"/>
</jnlp> 
```

Is there something more to your jnlp?

**Comment by janakmulani** [comment]
@aldonogueira  Sorry I tested with OpenWebStart and it worked. Buti when I test with ITW 1.8.4 then I can reproduce your error. Which version of ITW are you using? We will have a look at this ITW bug. However, is it possible for you to start using OpenWebStart?

**Comment by aldonogueira** [comment]
The application we need to run is Java 8 so OpenWebStart is not the ideal. That's why we are using AdoptOpenJDK 8u282b08 and IcedTeaWeb 1.8.4 on Windows 10.  

I might test it with OpenWebStart though. I'll report here later

**Comment by janakmulani** [comment]
You can surely run Java 8 apps with OWS. Using the JVM Manager you can configure OWS to use AdoptOpenJDK 8u282b08 to run the app. Moreover OWS itself will use AdoptOpenJDK 8u282b08 from soon to be released version.

**Comment by aldonogueira** [comment]
I did the test specifying `j2se version="1.8"` in the JNLP file in a Windows 10 with just OpenWebStart and no Java installed. OpenWebStart downloads AdoptOpenJDK 8u282 and uses it to run the application. The problem with the empty dialog doesn't occur. In fact the dialog is a different one

**Comment by janakmulani** [comment]
@aldonogueira Can you please tell me which dialog is shown? Did the application run as expected?
