### ISSUE TITLE
Exception throw when trying to initialize com.sun.crypto.provider.DHKeyPairGenerator

### ISSUE THREAD

**Issue by AndreasEhret** [AdoptOpenJDK/IcedTea-Web#81]
This issue was imported from bugzilla with bugzilla2github
# Bugzilla Bug Referenze: [3660](https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3660)
Date: 2018-12-04 00:06:00 +0000
From: Chad Decker &lt;<cdecker>&gt;
To:   JiriVanek &lt;<jvanek>&gt;
CC:   unassigned

Last updated: 2018-12-27 08:29:42 +0000

## Comment 17109
Date: 2018-12-04 00:06:44 +0000
From: Chad Decker &lt;<cdecker>&gt;

Created attachment 1713
                Side by side, signed jar, source code, jnlp to local launch

                When an application is launched used IcedTeaWeb and the following line is called:

                DHKeyPairGenerator gen = new DHKeyPairGenerator();

                The following trace occurs in the IcedTeaWeb JNLP Class loader.

                - Jar is self signed
                - JNLP is launching locally (codebase = file:// YOUR_DOWNLOAD_PATH), but this isn't an issue, this is to
                just demo the issue.

                Error: No security instance for
                file:/C:/Program%20Files/Java/jdk1.8.0_191/jre/lib/ext/sunjce_provider.jar. The application may have
                trouble continuing
                Error: No security instance for
                file:/C:/Program%20Files/Java/jdk1.8.0_191/jre/lib/ext/sunjce_provider.jar. The application may have
                trouble continuing
                java.lang.NullPointerException: Code source security was null
                at net.sourceforge.jnlp.runtime.JNLPClassLoader.getPermissions(JNLPClass
                Loader.java:1156)
                at net.sourceforge.jnlp.runtime.JNLPPolicy.getPermissions(JNLPPolicy.jav
                a:88)
                at net.sourceforge.jnlp.runtime.JNLPPolicy.implies(JNLPPolicy.java:199)
                at java.security.ProtectionDomain.implies(ProtectionDomain.java:279)
                at java.security.AccessControlContext.checkPermission(AccessControlConte
                xt.java:450)
                at java.security.AccessController.checkPermission(AccessController.java:
                884)
                at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
                at net.sourceforge.jnlp.runtime.JNLPSecurityManager.checkPermission(JNLP
                SecurityManager.java:291)
                at java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:156
                4)
                at java.lang.ClassLoader$1.run(ClassLoader.java:502)
                at java.lang.ClassLoader$1.run(ClassLoader.java:500)
                at java.security.AccessController.doPrivileged(Native Method)
                at java.lang.ClassLoader.checkPackageAccess(ClassLoader.java:500)
                at com.sun.crypto.provider.DHKeyPairGenerator.<init>(DHKeyPairGenerator.
                java:71)
                at webstart.SelfSignedWebstartApp.generateDHKeyPair(SelfSignedWebstartAp
                p.java:41)
                at webstart.SelfSignedWebstartApp.access$100(SelfSignedWebstartApp.java:
            

> Attached file: Error loading sun crypto provider.rar (application/x-rar, 158039 bytes)
> Description:   Side by side, signed jar, source code, jnlp to local launch

## Comment 17110
Date: 2018-12-04 00:07:41 +0000
From: Chad Decker &lt;<cdecker>&gt;

Note: click on generateGHKeyPair within sample application to reproduce.

## Comment 17172
Date: 2018-12-27 08:29:42 +0000
From: JiriVanek &lt;<jvanek>&gt;

Was this regression against jdk lower then 191?

**Comment by VanDecker** [comment]
It came down to a Security Provider issue, when trying to use IcedTeaWeb in conjunction with an Oracle JRE, and then loading a class from a signed JAR.

One workaround is to use IcedTeaWeb with OpenJDK.

I've noticed that this issue is no longer happening in ITW-1.8, when launching javaws and the jnlp path from the command line.

**Comment by judovana** [comment]
thnak you for investigations
