### ISSUE TITLE
itw-javantx-*.log report class now found issue very often

### ISSUE THREAD

**Issue by veveeran** [AdoptOpenJDK/IcedTea-Web#828]
Hi,

I am using  icetea-web to launch the JNLP application.  With icetea-web  , its generated many logs, in that itw-javantx-*.log
keep reporting class not found issue very often. And the log  file up with below kind on class not found error.

java.lang.ClassNotFoundException: com.ibm.nettrader.sd.ep.properties.NettraderFXMM
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClassExt(JNLPClassLoader.java:1802)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClass(JNLPClassLoader.java:1602)

could see jar are added below permission;

Permission added: ("java.io.FilePermission" "C:\Users\VeenaVeeranna\.cache\icedtea-web\cache\57\....\jna-platform-4.4.0.jar" "read")

But from application side, there is not impact so such logs in the application.  Why we get this errors ? how to avoid this ?

**Comment by andreiacsantos** [comment]
I'm having the same issue when launching my application with icedtea-web. The application runs as expected, but there are a lot of "ClassNotFoundException" when trying to load the resources. All the Jars are in the JNLP.
Is there any way to avoid these debug error messages?

Thank you.
