### ISSUE TITLE
IcedTea + Factset Prime Terminal

### ISSUE THREAD

**Issue by chanof** [AdoptOpenJDK/IcedTea-Web#833]
Hello,
i'm trying to open Prime Terminal's slider2.jnlp on Win10, but I get the following log, while i can open others JNLP.
[slider2.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/7435323/slider2.zip)
AdoptOpenJDK 8.0.232.09(x64)

```
net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file. You can try to download this file manually and send it as bug report to IcedTea-Web team.
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)
	at net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)
	at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:270)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:210)
Caused by: net.sourceforge.jnlp.ParseException: Invalid XML document syntax.
	at net.sourceforge.jnlp.XMLParser.getRootNode(XmlParser.java:118)
	at net.sourceforge.jnlp.MalformedXMLParser.getRootNode(MalformedXMLParser.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.jnlp.Parser.getRootNode(Parser.java:1380)
	at net.sourceforge.jnlp.JNLPFile.parse(JNLPFile.java:866)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:233)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:453)
	... 6 more
Caused by: net.sourceforge.nanoxml.XMLParseException: XML Parse Exception during parsing of a html element at line 3: Expected: /
	at net.sourceforge.nanoxml.XMLElement.expectedInput(XMLElement.java:1184)
	at net.sourceforge.nanoxml.XMLElement.scanElement(XMLElement.java:1037)
	at net.sourceforge.nanoxml.XMLElement.scanElement(XMLElement.java:1018)
	at net.sourceforge.nanoxml.XMLElement.parseFromReader(XMLElement.java:514)
	at net.sourceforge.nanoxml.XMLElement.parseFromReader(XMLElement.java:466)
	at net.sourceforge.jnlp.XMLParser.getRootNode(XmlParser.java:114)
	... 18 more
```

May i ask for help?
Gian

**Comment by janakmulani** [comment]
It seems the Jnlp app requires JavaFX : `<jfx:javafx-runtime version="1+" />`

Please have a look at https://openwebstart.com/docs/FAQ.html#_how_to_run_openjfx_based_javafx_applications_with_openwebstar

**Comment by janakmulani** [comment]
@chanof  I could run the app with Java 8 which has Java FX. If you want to run with JRE > 8 the you need to specify OpenJfx jars in the Jnlp as described in the link above.
