### ISSUE TITLE
Cannot start any Dell Remote Console

### ISSUE THREAD

**Issue by imle** [AdoptOpenJDK/IcedTea-Web#847]
Cannot start any Dell Remote Console. I'm not sure how else to test this, but I've included the info in the console. I've tried this with java 8 and 11. Same issue with both.

Details
```
net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize application. The application has not been initialized, for more information execute javaws from the command line.
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:592)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:373)
	at net.sourceforge.jnlp.Launcher.access$200(Launcher.java:71)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:659)
Caused by: net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Unknown Main-Class. Could not determine the main class for this application.
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.initializeResources(JNLPClassLoader.java:747)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.<init>(JNLPClassLoader.java:350)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.createInstance(JNLPClassLoader.java:423)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:495)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getInstance(JNLPClassLoader.java:468)
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:584)
	... 3 more
```

Console
```
Closing DownloadServiceListener
System logger called with result of 0
System logger called with result of 0
System logger called with result of 0
System logger called with result of 0
System logger called with result of 0
System logger called with result of 0
System logger called with result of 0
System logger called with result of 0
System logger called with result of 0
System logger called with result of 0
System logger called with result of 0
System logger called with result of 0
System logger called with result of 0
System logger called with result of 0
System logger called with result of 0
System logger called with result of 0
Waiting for exception dialog to be closed
Launch exception
netx: Initialization Error: Could not initialize application. (Fatal: Initialization Error: Unknown Main-Class. Could not determine the main class for this application.)
System logger called with result of 0
Error flag set for resource 'https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar'. Can not return a local file for the resource
Activate native: https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar
Activate jar: https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar
Error flag set for resource 'https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar'. Can not return a local file for the resource
DownloadServiceListener will be disposed
Download done. Shutting down executor
DownloadServiceListener for Virtual Console Client will be created
Jars not ready to provide attribute Application-Name
checkForMain JAR https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar not found. Continuing.
Error flag set for resource 'https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar'. Can not return a local file for the resource
System logger called with result of 0
Activate native: https://10.0.120.10:443/software/avctKVMIOMac64.jar
Activate jar: file:/Users/ski/.cache/icedtea-web/cache/0/3/avctKVMIOMac64.jar
sun.misc.JarIndex not found - Running jdk9+ ?
DownloadServiceListener will be disposed
Download done. Shutting down executor
DownloadServiceListener for Virtual Console Client will be created
Jars not ready to provide attribute Application-Name
Error flag set for resource 'https://10.0.120.10:443/software/avctKVM.jar'. Can not return a local file for the resource
Activate native: https://10.0.120.10:443/software/avctKVM.jar
Activate jar: https://10.0.120.10:443/software/avctKVM.jar
Error flag set for resource 'https://10.0.120.10:443/software/avctKVM.jar'. Can not return a local file for the resource
DownloadServiceListener will be disposed
Download done. Shutting down executor
DownloadServiceListener for Virtual Console Client will be created
Jars not ready to provide attribute Application-Name
checkForMain JAR https://10.0.120.10:443/software/avctKVM.jar not found. Continuing.
Error flag set for resource 'https://10.0.120.10:443/software/avctKVM.jar'. Can not return a local file for the resource
checkForMain JAR https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar not found. Continuing.
Error flag set for resource 'https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar'. Can not return a local file for the resource
checkForMain JAR https://10.0.120.10:443/software/avctKVM.jar not found. Continuing.
Error flag set for resource 'https://10.0.120.10:443/software/avctKVM.jar'. Can not return a local file for the resource
App already has trusted publisher: true
CN=VeriSign Class 3 Public Primary Certification Authority - G5,OU=(c) 2006 VeriSign\, Inc. - For authorized use only,OU=VeriSign Trust Network,O=VeriSign\, Inc.,C=US found in cacerts (/Users/ski/.cache/icedtea-web/jvm-cache/adoptium_11.0.10/lib/security/cacerts)
Operating Keystore /Users/ski/.config/icedtea-web/security/trusted.cacerts
Loading Keystore /Users/ski/.config/icedtea-web/security/trusted.cacerts
Keystore file /Users/ski/.config/icedtea-web/security/trusted.cacerts exists.
Operating Keystore /Users/ski/.config/icedtea-web/security/trusted.jssecacerts
Loading Keystore /Users/ski/.config/icedtea-web/security/trusted.jssecacerts
Keystore file /Users/ski/.config/icedtea-web/security/trusted.jssecacerts exists.
Operating Keystore /Users/ski/.cache/icedtea-web/jvm-cache/adoptium_11.0.10/lib/security/cacerts
Loading Keystore /Users/ski/.cache/icedtea-web/jvm-cache/adoptium_11.0.10/lib/security/cacerts
Keystore file /Users/ski/.cache/icedtea-web/jvm-cache/adoptium_11.0.10/lib/security/cacerts exists.
Operating Keystore Unknown
Loading Keystore Unknown
Keystore file /Users/ski/.cache/icedtea-web/jvm-cache/adoptium_11.0.10/lib/security/jssecacerts does not exists.
CN=Dell Inc.,O=Dell Inc.,L=Round Rock,ST=Texas,C=US found in cacerts (/Users/ski/.config/icedtea-web/security/trusted.certs)
Operating Keystore /Users/ski/.config/icedtea-web/security/trusted.certs
Loading Keystore /Users/ski/.config/icedtea-web/security/trusted.certs
Keystore file /Users/ski/.config/icedtea-web/security/trusted.certs exists.
Operating Keystore /Users/ski/.config/icedtea-web/security/trusted.jssecerts
Loading Keystore /Users/ski/.config/icedtea-web/security/trusted.jssecerts
Keystore file /Users/ski/.config/icedtea-web/security/trusted.jssecerts exists.
Operating Keystore Unknown
Loading Keystore Unknown
Keystore file /Users/ski/.cache/icedtea-web/jvm-cache/adoptium_11.0.10/lib/security/trusted.certs does not exists.
Operating Keystore Unknown
Loading Keystore Unknown
Keystore file /Users/ski/.cache/icedtea-web/jvm-cache/adoptium_11.0.10/lib/security/trusted.jssecerts does not exists.
Error flag set for resource 'https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar'. Can not return a local file for the resource
Jar found at /Users/ski/.cache/icedtea-web/cache/0/3/avctKVMIOMac64.jar has been verified as SIGNED_NOT_OK
Operating Keystore /Users/ski/.config/icedtea-web/security/trusted.cacerts
Loading Keystore /Users/ski/.config/icedtea-web/security/trusted.cacerts
Keystore file /Users/ski/.config/icedtea-web/security/trusted.cacerts exists.
Operating Keystore /Users/ski/.config/icedtea-web/security/trusted.jssecacerts
Loading Keystore /Users/ski/.config/icedtea-web/security/trusted.jssecacerts
Keystore file /Users/ski/.config/icedtea-web/security/trusted.jssecacerts exists.
Operating Keystore /Users/ski/.cache/icedtea-web/jvm-cache/adoptium_11.0.10/lib/security/cacerts
Loading Keystore /Users/ski/.cache/icedtea-web/jvm-cache/adoptium_11.0.10/lib/security/cacerts
Keystore file /Users/ski/.cache/icedtea-web/jvm-cache/adoptium_11.0.10/lib/security/cacerts exists.
Operating Keystore Unknown
Loading Keystore Unknown
Keystore file /Users/ski/.cache/icedtea-web/jvm-cache/adoptium_11.0.10/lib/security/jssecacerts does not exists.
System logger called with result of 0
System logger called with result of 0
System logger called with result of 0
Error flag set for resource 'https://10.0.120.10:443/software/avctKVM.jar'. Can not return a local file for the resource
DownloadServiceListener will be disposed
Download done. Shutting down executor
could not download resource [l=https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar v=null s=I] from any of theses urls [https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar] caused byExecutionException: java.net.SocketTimeoutException: Read timed out caused by SocketTimeoutException: Read timed out caused by SocketTimeoutException: Read timed out
Exception while downloading resource [l=https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar v=null s=I] from https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar - message: Read timed out cause: java.net.SocketTimeoutException: Read timed out
System logger called with result of 0
System logger called with result of 0
System logger called with result of 0
could not download resource [l=https://10.0.120.10:443/software/avctKVM.jar v=null s=I] from any of theses urls [https://10.0.120.10:443/software/avctKVM.jar] caused byExecutionException: java.net.SocketTimeoutException: Read timed out caused by SocketTimeoutException: Read timed out caused by SocketTimeoutException: Read timed out
Exception while downloading resource [l=https://10.0.120.10:443/software/avctKVM.jar v=null s=I] from https://10.0.120.10:443/software/avctKVM.jar - message: Read timed out cause: java.net.SocketTimeoutException: Read timed out
Use cached version of resource [l=https://10.0.120.10:443/software/avctKVMIOMac64.jar v=null s=D] at /Users/ski/.cache/icedtea-web/cache/0/3/avctKVMIOMac64.jar
needsUpdate: https://10.0.120.10:443/software/avctKVMIOMac64.jar -> false
isUpToDate: CacheKey{location=https://10.0.120.10:443/software/avctKVMIOMac64.jar, version=null} = true
CacheKey{location=https://10.0.120.10:443/software/avctKVMIOMac64.jar, version=null}: lastModified cache:1582275671000 actual:1582275671000 -> isCurrent = true
CacheKey{location=https://10.0.120.10:443/software/avctKVMIOMac64.jar, version=null}: isCached true
Best url for [l=https://10.0.120.10:443/software/avctKVMIOMac64.jar v=null s=I] is https://10.0.120.10:443/software/avctKVMIOMac64.jar by HEAD
URL connection 'https://10.0.120.10:443/software/avctKVMIOMac64.jar' header fields: {Accept-Ranges=[bytes], null=[HTTP/1.1 200 OK], Strict-Transport-Security=[max-age=63072000], ETag=[1582301944], Connection=[Keep-Alive], Vary=[Accept-Encoding], Last-Modified=[Fri, 21 Feb 2020 09:01:11 GMT], Content-Length=[22109], Date=[Sat, 18 Dec 2021 06:10:42 GMT], Content-Type=[application/octet-stream]}
Using NO_PROXY
Will download in background: https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar
Found best URL for [l=https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar v=null s=I]: url:https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar; responseCode:200; location: null; version: null; lastModified: 1582275671000; contentLength: 935047;
Best url for [l=https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar v=null s=I] is https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar by HEAD
URL connection 'https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar' header fields: {Accept-Ranges=[bytes], null=[HTTP/1.1 200 OK], Strict-Transport-Security=[max-age=63072000], ETag=[1583214899], Connection=[Keep-Alive], Vary=[Accept-Encoding], Last-Modified=[Fri, 21 Feb 2020 09:01:11 GMT], Content-Length=[935047], Date=[Sat, 18 Dec 2021 06:10:42 GMT], Content-Type=[application/octet-stream]}
Using NO_PROXY
Will download in background: https://10.0.120.10:443/software/avctKVM.jar
Found best URL for [l=https://10.0.120.10:443/software/avctKVM.jar v=null s=I]: url:https://10.0.120.10:443/software/avctKVM.jar; responseCode:200; location: null; version: null; lastModified: 1582275671000; contentLength: 1418563;
Best url for [l=https://10.0.120.10:443/software/avctKVM.jar v=null s=I] is https://10.0.120.10:443/software/avctKVM.jar by HEAD
URL connection 'https://10.0.120.10:443/software/avctKVM.jar' header fields: {Accept-Ranges=[bytes], null=[HTTP/1.1 200 OK], Strict-Transport-Security=[max-age=63072000], ETag=[1583698414], Connection=[Keep-Alive], Vary=[Accept-Encoding], Last-Modified=[Fri, 21 Feb 2020 09:01:11 GMT], Content-Length=[1418563], Date=[Sat, 18 Dec 2021 06:10:42 GMT], Content-Type=[application/octet-stream]}
Using NO_PROXY
Using NO_PROXY
Using NO_PROXY
Candidate URLs for [l=https://10.0.120.10:443/software/avctKVMIOMac64.jar v=null s=I]: [https://10.0.120.10:443/software/avctKVMIOMac64.jar]
needsUpdateCheck: https://10.0.120.10:443/software/avctKVMIOMac64.jar -> true
Using NO_PROXY
Candidate URLs for [l=https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar v=null s=I]: [https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar]
isCached: CacheKey{location=https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar, version=null} = false
isCached: CacheKey{location=https://10.0.120.10:443/software/avctKVMIOMac64.jar, version=null} = true
Using NO_PROXY
DownloadServiceListener for Virtual Console Client will be created
Candidate URLs for [l=https://10.0.120.10:443/software/avctKVM.jar v=null s=I]: [https://10.0.120.10:443/software/avctKVM.jar]
Jars not ready to provide attribute Application-Name
isCached: CacheKey{location=https://10.0.120.10:443/software/avctKVM.jar, version=null} = false
Start processing resource: avctVMAPI_DLLMac64.jar
Prefetching resource avctVMAPI_DLLMac64.jar
Start processing resource: avctKVMIOMac64.jar
Create resource for 'https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar'
Prefetching resource avctKVMIOMac64.jar
Start processing resource: avctKVM.jar
Create resource for 'https://10.0.120.10:443/software/avctKVMIOMac64.jar'
Prefetching resource avctKVM.jar
Create resource for 'https://10.0.120.10:443/software/avctKVM.jar'
New classloader: file:/Users/ski/Downloads/viewer-4.jnlp
Download done. Shutting down executor
Use cached version of resource [l=https://10.0.120.10:443/images/logo.gif v=null s=D] at /Users/ski/.cache/icedtea-web/cache/0/2/logo.gif
needsUpdate: https://10.0.120.10:443/images/logo.gif -> false
isUpToDate: CacheKey{location=https://10.0.120.10:443/images/logo.gif, version=null} = true
CacheKey{location=https://10.0.120.10:443/images/logo.gif, version=null}: lastModified cache:1582275669000 actual:1582275669000 -> isCurrent = true
CacheKey{location=https://10.0.120.10:443/images/logo.gif, version=null}: isCached true
Best url for [l=https://10.0.120.10:443/images/logo.gif v=null s=I] is https://10.0.120.10:443/images/logo.gif by HEAD
URL connection 'https://10.0.120.10:443/images/logo.gif' header fields: {Accept-Ranges=[bytes], null=[HTTP/1.1 200 OK], Strict-Transport-Security=[max-age=63072000], ETag=[1582284284], Connection=[Keep-Alive], Content-Encoding=[gzip], Vary=[Accept-Encoding], Last-Modified=[Fri, 21 Feb 2020 09:01:09 GMT], Content-Length=[3720], Date=[Sat, 18 Dec 2021 06:10:41 GMT], Content-Type=[image/gif]}
Using NO_PROXY
Using NO_PROXY
Candidate URLs for [l=https://10.0.120.10:443/images/logo.gif v=null s=I]: [https://10.0.120.10:443/images/logo.gif]
needsUpdateCheck: https://10.0.120.10:443/images/logo.gif -> true
isCached: CacheKey{location=https://10.0.120.10:443/images/logo.gif, version=null} = true
Start processing resource: logo.gif
Prefetching resource logo.gif
Create resource for 'https://10.0.120.10:443/images/logo.gif'
result: null
Jars not ready to provide attribute Application-Name
Jars not ready to provide attribute Application-Name
Acquired shared lock on /var/folders/rn/td6ks1_56ds1dy__pzc79lkr0000gn/T/ski/netx/locks/netx_running to indicate javaws is running
good - your JRE - 11.0.10 - match requested JRE - 1.6+
Acceptable vendor tag found, contains: Dell Inc.
Jars not ready to provide attribute Application-Name
Description: null
Homepage: null
Using MalformedXMLParser
Download done. Shutting down executor
Resource is not cacheable: viewer-4.jnlp
Create resource for 'file:/Users/ski/Downloads/viewer-4.jnlp'
good - your JRE - 11.0.10 - match requested JRE - 1.6+
Acceptable vendor tag found, contains: Dell Inc.
Jars not ready to provide attribute Application-Name
Description: null
Homepage: null
Using MalformedXMLParser
Download done. Shutting down executor
Resource is not cacheable: viewer-4.jnlp
Create resource for 'file:/Users/ski/Downloads/viewer-4.jnlp'
JNLP file location: /Users/ski/Downloads/viewer-4.jnlp
Proceeding with jnlp
Direct proxy created
Selected ProxyProvider : NONE
Operating Keystore /Users/ski/.config/icedtea-web/security/trusted.clientcerts
Loading Keystore /Users/ski/.config/icedtea-web/security/trusted.clientcerts
Keystore file /Users/ski/.config/icedtea-web/security/trusted.clientcerts exists.
Operating Keystore Unknown
Loading Keystore Unknown
Keystore file /Users/ski/.cache/icedtea-web/jvm-cache/adoptium_11.0.10/lib/security/trusted.clientcerts does not exists.
Operating Keystore /Users/ski/.config/icedtea-web/security/trusted.cacerts
Loading Keystore /Users/ski/.config/icedtea-web/security/trusted.cacerts
Keystore file /Users/ski/.config/icedtea-web/security/trusted.cacerts exists.
Operating Keystore /Users/ski/.config/icedtea-web/security/trusted.jssecacerts
Loading Keystore /Users/ski/.config/icedtea-web/security/trusted.jssecacerts
Keystore file /Users/ski/.config/icedtea-web/security/trusted.jssecacerts exists.
Operating Keystore /Users/ski/.cache/icedtea-web/jvm-cache/adoptium_11.0.10/lib/security/cacerts
Loading Keystore /Users/ski/.cache/icedtea-web/jvm-cache/adoptium_11.0.10/lib/security/cacerts
Keystore file /Users/ski/.cache/icedtea-web/jvm-cache/adoptium_11.0.10/lib/security/cacerts exists.
Operating Keystore Unknown
Loading Keystore Unknown
Keystore file /Users/ski/.cache/icedtea-web/jvm-cache/adoptium_11.0.10/lib/security/jssecacerts does not exists.
Operating Keystore /Users/ski/.config/icedtea-web/security/trusted.certs
Loading Keystore /Users/ski/.config/icedtea-web/security/trusted.certs
Keystore file /Users/ski/.config/icedtea-web/security/trusted.certs exists.
Operating Keystore /Users/ski/.config/icedtea-web/security/trusted.jssecerts
Loading Keystore /Users/ski/.config/icedtea-web/security/trusted.jssecerts
Keystore file /Users/ski/.config/icedtea-web/security/trusted.jssecerts exists.
Operating Keystore Unknown
Loading Keystore Unknown
Keystore file /Users/ski/.cache/icedtea-web/jvm-cache/adoptium_11.0.10/lib/security/trusted.certs does not exists.
Operating Keystore Unknown
Loading Keystore Unknown
Keystore file /Users/ski/.cache/icedtea-web/jvm-cache/adoptium_11.0.10/lib/security/trusted.jssecerts does not exists.
Operating Keystore Unknown
Operating Keystore /Users/ski/.config/icedtea-web/security/trusted.clientcerts
Loading Keystore /Users/ski/.config/icedtea-web/security/trusted.clientcerts
Keystore file /Users/ski/.config/icedtea-web/security/trusted.clientcerts exists.
Starting security dialog thread
Loading USER level properties from: file:/Users/ski/.config/icedtea-web/deployment.properties
Ico provider registered correctly.
using com.openwebstart.extensionpoint.OwsExtensionPoint extension point
Java Runtime AdoptOpenJDK-11.0.10
OS: Mac OS X
OpenWebStartLauncher called with args: [-Xnofork, /Users/ski/Downloads/viewer-4.jnlp].
init logger factory to net.sourceforge.jnlp.util.logging.OutputControllerLoggerFactory@6073f712
```

**Comment by sclassen** [comment]
The Log shows the following:

could not download resource [l=https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar v=null s=I] from any of theses urls [https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar] caused byExecutionException: java.net.SocketTimeoutException: Read timed out caused by SocketTimeoutException: Read timed out caused by SocketTimeoutException: Read timed out Exception while downloading resource [l=https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar v=null s=I] from https://10.0.120.10:443/software/avctVMAPI_DLLMac64.jar - message: Read timed out cause: java.net.SocketTimeoutException: Read timed out System logger called with result of 0 System logger called with result of 0 System logger called with result of 0 could not download resource [l=https://10.0.120.10:443/software/avctKVM.jar v=null s=I] from any of theses urls [https://10.0.120.10:443/software/avctKVM.jar] caused byExecutionException: java.net.SocketTimeoutException: Read timed out caused by SocketTimeoutException: Read timed out caused by SocketTimeoutException: Read timed out Exception while downloading resource [l=https://10.0.120.10:443/software/avctKVM.jar v=null s=I] from https://10.0.120.10:443/software/avctKVM.jar - message: Read timed out cause: java.net.SocketTimeoutException: Read timed out 


Can you make sure https://10.0.120.10:443/software/avctKVM.jar is reachable from your machine without a proxy. If you need a proxy please configure it in the settings.



Am 18. Dezember 2021 02:17:12 MEZ schrieb Steven Imle ***@***.***>:

**Comment by imle** [comment]
It looks like all of the files listed are reachable from the machine I am performing the work on.

**Comment by imle** [comment]
I think the only thing that changed since I was able to connect before is that the dell machines are on a separate vlan. I don't know how that would stop Java from reaching them but allow everything else through.

**Comment by sclassen** [comment]
did you have success in launching the Dell Remote Console?
I once more went over the log but did not see anything special beside the socket timeout

**Comment by gpavinteractiv** [comment]
same issue here, any help?

**Comment by qiukeren** [comment]
interesting here it gets the :443/software/avctKVM.jar header (yes the network is ok before), but finally returns `SocketTimeoutException: Read timed out`.




```
DownloadServiceListener for Virtual Console Client will be created
isCached: CacheKey{location=https://192.168.2.204:443/software/avctKVM.jar, version=null} = false
Candidate URLs for [l=https://192.168.2.204:443/software/avctKVM.jar v=null s=I]: [https://192.168.2.204:443/software/avctKVM.jar]
PAC result for url 'https://192.168.2.204:443/software/avctKVM.jar' -> 'DIRECT'
PAC Proxies found for 'https://192.168.2.204:443/software/avctKVM.jar' : [DIRECT]

//HERE IT IS OK with THE CONNECTION

URL connection 'https://192.168.2.204:443/software/avctKVM.jar' header fields: {Accept-Ranges=[bytes], X-Frame-Options=[SAMEORIGIN], Keep-Alive=[timeout=60, max=198], null=[HTTP/1.1 200 OK], Strict-Transport-Security=[max-age=63072000], ETag=[1679110056], Connection=[Keep-Alive], Vary=[Accept-Encoding], Last-Modified=[Wed, 01 Mar 2023 16:05:12 GMT], Content-Length=[1418601], Date=[Thu, 11 May 2023 23:29:32 GMT], Content-Type=[application/octet-stream]}
Best url for [l=https://192.168.2.204:443/software/avctKVM.jar v=null s=I] is https://192.168.2.204:443/software/avctKVM.jar by HEAD
Found best URL for [l=https://192.168.2.204:443/software/avctKVM.jar v=null s=I]: url:https://192.168.2.204:443/software/avctKVM.jar; responseCode:200; location: null; version: null; lastModified: 1677686712000; contentLength: 1418601; 
Will download in background: https://192.168.2.204:443/software/avctKVM.jar
PAC result for url 'https://192.168.2.204:443/software/avctKVM.jar' -> 'DIRECT'
PAC Proxies found for 'https://192.168.2.204:443/software/avctKVM.jar' : [DIRECT]
Exception while downloading resource [l=https://192.168.2.204:443/software/avctKVM.jar v=null s=I] from https://192.168.2.204:443/software/avctKVM.jar - message: Read timed out cause: java.net.SocketTimeoutException: Read timed out 
could not download resource [l=https://192.168.2.204:443/software/avctKVM.jar v=null s=I] from any of theses urls [https://192.168.2.204:443/software/avctKVM.jar] caused byExecutionException: java.net.SocketTimeoutException: Read timed out caused by SocketTimeoutException: Read timed out caused by SocketTimeoutException: Read timed out
Download done. Shutting down executor
DownloadServiceListener will be disposed
Error flag set for resource 'https://192.168.2.204:443/software/avctKVM.jar'. Can not return a local file for the resource
Error flag set for resource 'https://192.168.2.204:443/software/avctKVM.jar'. Can not return a local file for the resource
checkForMain JAR https://192.168.2.204:443/software/avctKVM.jar not found. Continuing.
Error flag set for resource 'https://192.168.2.204:443/software/avctKVM.jar'. Can not return a local file for the resource
checkForMain JAR https://192.168.2.204:443/software/avctKVM.jar not found. Continuing.
Jars not ready to provide attribute Application-Name
DownloadServiceListener for Virtual Console Client will be created
Download done. Shutting down executor

```

**Comment by qiukeren** [comment]
> interesting here it gets the :443/software/avctKVM.jar header (yes the network is ok before), but finally returns `SocketTimeoutException: Read timed out`.
> 
> ```
> DownloadServiceListener for Virtual Console Client will be created
> isCached: CacheKey{location=https://192.168.2.204:443/software/avctKVM.jar, version=null} = false
> Candidate URLs for [l=https://192.168.2.204:443/software/avctKVM.jar v=null s=I]: [https://192.168.2.204:443/software/avctKVM.jar]
> PAC result for url 'https://192.168.2.204:443/software/avctKVM.jar' -> 'DIRECT'
> PAC Proxies found for 'https://192.168.2.204:443/software/avctKVM.jar' : [DIRECT]
> 
> //HERE IT IS OK with THE CONNECTION
> 
> URL connection 'https://192.168.2.204:443/software/avctKVM.jar' header fields: {Accept-Ranges=[bytes], X-Frame-Options=[SAMEORIGIN], Keep-Alive=[timeout=60, max=198], null=[HTTP/1.1 200 OK], Strict-Transport-Security=[max-age=63072000], ETag=[1679110056], Connection=[Keep-Alive], Vary=[Accept-Encoding], Last-Modified=[Wed, 01 Mar 2023 16:05:12 GMT], Content-Length=[1418601], Date=[Thu, 11 May 2023 23:29:32 GMT], Content-Type=[application/octet-stream]}
> Best url for [l=https://192.168.2.204:443/software/avctKVM.jar v=null s=I] is https://192.168.2.204:443/software/avctKVM.jar by HEAD
> Found best URL for [l=https://192.168.2.204:443/software/avctKVM.jar v=null s=I]: url:https://192.168.2.204:443/software/avctKVM.jar; responseCode:200; location: null; version: null; lastModified: 1677686712000; contentLength: 1418601; 
> Will download in background: https://192.168.2.204:443/software/avctKVM.jar
> PAC result for url 'https://192.168.2.204:443/software/avctKVM.jar' -> 'DIRECT'
> PAC Proxies found for 'https://192.168.2.204:443/software/avctKVM.jar' : [DIRECT]
> Exception while downloading resource [l=https://192.168.2.204:443/software/avctKVM.jar v=null s=I] from https://192.168.2.204:443/software/avctKVM.jar - message: Read timed out cause: java.net.SocketTimeoutException: Read timed out 
> could not download resource [l=https://192.168.2.204:443/software/avctKVM.jar v=null s=I] from any of theses urls [https://192.168.2.204:443/software/avctKVM.jar] caused byExecutionException: java.net.SocketTimeoutException: Read timed out caused by SocketTimeoutException: Read timed out caused by SocketTimeoutException: Read timed out
> Download done. Shutting down executor
> DownloadServiceListener will be disposed
> Error flag set for resource 'https://192.168.2.204:443/software/avctKVM.jar'. Can not return a local file for the resource
> Error flag set for resource 'https://192.168.2.204:443/software/avctKVM.jar'. Can not return a local file for the resource
> checkForMain JAR https://192.168.2.204:443/software/avctKVM.jar not found. Continuing.
> Error flag set for resource 'https://192.168.2.204:443/software/avctKVM.jar'. Can not return a local file for the resource
> checkForMain JAR https://192.168.2.204:443/software/avctKVM.jar not found. Continuing.
> Jars not ready to provide attribute Application-Name
> DownloadServiceListener for Virtual Console Client will be created
> Download done. Shutting down executor
> ```

seems just connected to wired connection can avoid this exception. (
