### ISSUE TITLE
Fatal: Read Error: Could not read or parse the JNLP file

### ISSUE THREAD

**Issue by darkbasic** [AdoptOpenJDK/IcedTea-Web#858]
I cannot run the following jnlp from Gentoo ppc64le with icedtea-3.21.0 and icedtea-web-1.8.8.

[CIR20_fx.jnlp.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/8073452/CIR20_fx.jnlp.zip)

```
System is already following XDG .cache and .config specifications
config: /home/niko/.config/icedtea-web file exists: true
cache: /home/niko/.cache/icedtea-web file exists:true
Ico provider registered correctly.
java.io.FileNotFoundException: /home/niko/.config/icedtea-web/deployment.properties (No such file or directory)
     at java.io.FileInputStream.open0(Native Method)
     at java.io.FileInputStream.open(FileInputStream.java:195)
     at java.io.FileInputStream.<init>(FileInputStream.java:138)
     at java.io.FileInputStream.<init>(FileInputStream.java:93)
     at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
     at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
     at java.net.URL.openStream(URL.java:1093)
     at net.sourceforge.jnlp.config.DeploymentConfiguration.parsePropertiesFile(DeploymentConfiguration.java:714)
     at net.sourceforge.jnlp.config.DeploymentConfiguration.findSystemConfigFile(DeploymentConfiguration.java:536)
     at net.sourceforge.jnlp.config.DeploymentConfiguration.load(DeploymentConfiguration.java:348)
     at net.sourceforge.jnlp.config.DeploymentConfiguration.load(DeploymentConfiguration.java:328)
     at net.sourceforge.jnlp.runtime.JNLPRuntime$DeploymentConfigurationHolder.initConfiguration(JNLPRuntime.java:458)
     at net.sourceforge.jnlp.runtime.JNLPRuntime$DeploymentConfigurationHolder.<clinit>(JNLPRuntime.java:453)
     at net.sourceforge.jnlp.runtime.JNLPRuntime.getConfiguration(JNLPRuntime.java:488)
     at net.sourceforge.jnlp.config.DirectoryValidator.<init>(DirectoryValidator.java:226)
     at net.sourceforge.jnlp.config.DeploymentConfiguration.move14AndOlderFilesTo15Structure(DeploymentConfiguration.java:889)
     at net.sourceforge.jnlp.config.DeploymentConfiguration.move14AndOlderFilesTo15StructureCatched(DeploymentConfiguration.java:789)
     at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:125) 
No User level deployment.properties found.
java.io.FileNotFoundException: /home/niko/.config/icedtea-web/deployment.properties (No such file or directory)
     at java.io.FileInputStream.open0(Native Method)
     at java.io.FileInputStream.open(FileInputStream.java:195)
     at java.io.FileInputStream.<init>(FileInputStream.java:138)
     at java.io.FileInputStream.<init>(FileInputStream.java:93)
     at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
     at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
     at java.net.URL.openStream(URL.java:1093)
     at net.sourceforge.jnlp.config.DeploymentConfiguration.loadComments(DeploymentConfiguration.java:931)
     at net.sourceforge.jnlp.config.DeploymentConfiguration.load(DeploymentConfiguration.java:388)
     at net.sourceforge.jnlp.config.DeploymentConfiguration.load(DeploymentConfiguration.java:350)
     at net.sourceforge.jnlp.config.DeploymentConfiguration.load(DeploymentConfiguration.java:328)
     at net.sourceforge.jnlp.runtime.JNLPRuntime$DeploymentConfigurationHolder.initConfiguration(JNLPRuntime.java:458)
     at net.sourceforge.jnlp.runtime.JNLPRuntime$DeploymentConfigurationHolder.<clinit>(JNLPRuntime.java:453)
     at net.sourceforge.jnlp.runtime.JNLPRuntime.getConfiguration(JNLPRuntime.java:488)
     at net.sourceforge.jnlp.config.DirectoryValidator.<init>(DirectoryValidator.java:226)
     at net.sourceforge.jnlp.config.DeploymentConfiguration.move14AndOlderFilesTo15Structure(DeploymentConfiguration.java:889)
     at net.sourceforge.jnlp.config.DeploymentConfiguration.move14AndOlderFilesTo15StructureCatched(DeploymentConfiguration.java:789)
     at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:125) 
WARNING: key deployment.system.cachedir has no value, setting to default value
Forcing of offline set to: false
Starting security dialog thread
Using firefox's profiles file: /home/niko/.mozilla/firefox/profiles.ini
Found preferences file: /home/niko/.mozilla/firefox/zl4x2das.default/prefs.js
java.io.FileNotFoundException: /home/niko/.mozilla/firefox/zl4x2das.default/prefs.js (No such file or directory)
     at java.io.FileInputStream.open0(Native Method)
     at java.io.FileInputStream.open(FileInputStream.java:195)
     at java.io.FileInputStream.<init>(FileInputStream.java:138)
     at java.io.FileReader.<init>(FileReader.java:72)
     at net.sourceforge.jnlp.browser.FirefoxPreferencesParser.parse(FirefoxPreferencesParser.java:90)
     at net.sourceforge.jnlp.browser.BrowserAwareProxySelector.parseBrowserPreferences(BrowserAwareProxySelector.java:153)
     at net.sourceforge.jnlp.browser.BrowserAwareProxySelector.initFromBrowserConfig(BrowserAwareProxySelector.java:114)
     at net.sourceforge.jnlp.browser.BrowserAwareProxySelector.initialize(BrowserAwareProxySelector.java:101)
     at net.sourceforge.jnlp.runtime.JNLPRuntime.initialize(JNLPRuntime.java:293)
     at net.sourceforge.jnlp.runtime.Boot.init(Boot.java:353)
     at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:58)
     at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:274)
     at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)
     at java.security.AccessController.doPrivileged(Native Method)
     at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:214) 
Unable to use Firefox's proxy settings. Using "DIRECT" as proxy type.
System logger called with result of 0
System logger called with result of 0
System logger called with result of 0
Proceeding with jnlp
JNLP file location: CIR20_fx.jnlp
java.lang.ClassNotFoundException: net/sourceforge/jnlp/MalformedXMLParser
     at java.lang.Class.forName0(Native Method)
     at java.lang.Class.forName(Class.java:264)
     at net.sourceforge.jnlp.Parser.getParserInstance(Parser.java:1405)
     at net.sourceforge.jnlp.Parser.getRootNode(Parser.java:1378)
     at net.sourceforge.jnlp.JNLPFile.parse(JNLPFile.java:867)
     at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:233)
     at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)
     at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)
     at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)
     at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:453)
     at net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)
     at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)
     at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:274)
     at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)
     at java.security.AccessController.doPrivileged(Native Method)
     at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:214) 
line: 1 <?xml version="1.0" encoding="UTF-8"?>
line: 2 <jnlp spec="1.0+" codebase="https://jws.agenziaentrate.it/jws/dichiarazioni/2020/" href="CIR20_fx.jnlp">
line: 3 <information>
line: 4  <title>Comunicazione Opzioni per interventi edilizi e superbonus</title>
line: 5  <icon href="logo.gif" kind="default" />
line: 6 
line: 7  <vendor>Agenzia delle Entrate</vendor>
line: 8  <homepage href="controlli2009Full.html" />
line: 9  <description>Comunicazione Opzioni per interventi edilizi e superbonus</description>
line: 10  <offline-allowed/>
line: 11  <shortcut online="true" install="true">
line: 12    <menu submenu="Unico On Line"/>
line: 13  </shortcut> 
line: 14 </information>
line: 15 <offline-allowed/>
line: 16 <security>
line: 17  <all-permissions/>
line: 18 </security>
line: 19 <update check="always" policy="always"/>
line: 20 <resources>
line: 21  <j2se version="1.8+"  href="http://java.sun.com/products/autodl/j2se" java-vm-args="--add-opens=java.desktop/java.awt=ALL-UNNAMED"/>
line: 22  <jar href="CIR20/CIR20fx.jar"/>
line: 23  <jar href="../AssistenzaCommonV6.jar"/>     
line: 24  <jar href="../AssistenzaFxV1.jar"/>     
line: 25  <jar href="../AssistenzaDicFxV1.jar"/>     
line: 26    <jar href="../JarExtractor.jar"/>
line: 27  <jar href="../TeLogging_1.0.0.jar"/>  -->
line: 28  <jar href="../ControlliCommonV1.jar"/>    
line: 29  <jar href="../TelemCommonV3-2.0.0.jar"/>    
line: 30  <jar href="../ComuniProvincia.jar"/>    
line: 31  <jar href="TelemCommonDic20.jar"/>    
line: 32  <jar href="ControlliCIR20.jar"/>
line: 33    <jar href="../../checkCF_PIVA.jar"/>
line: 34  <jar href="../../AnagCtrlCFPiva.jar"/>
line: 35  <jar href="../../iText-2.1.4.jar" />
line: 36  <jar href="../../Supporto.jar"/>
line: 37  <jar href="../../org.json.jar"/>
line: 38 </resources>
line: 39 <application-desc main-class="it.finanze.entrate.assistenzafx.application.MainCIR20">
line: 40 </application-desc>
line: 41 </jnlp>
netx: Read Error: Could not read or parse the JNLP file. (Broken Malformed parser. You may have missing tagsoup installation or your ITW was not built against it. Check your installation and/or consult distribution. Invalid XML document syntax. (XML Parse Exception during parsing of a jnlp element at line 27: Expected: <))
net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file. You can try to download this file manually and send it as bug report to IcedTea-Web team.
     at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)
     at net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)
     at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)
     at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:274)
     at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)
     at java.security.AccessController.doPrivileged(Native Method)
     at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:214)
 Caused by: net.sourceforge.jnlp.ParseException: Broken Malformed parser. You may have missing tagsoup installation or your ITW was not built against it. Check your installation and/or consult distribution. Invalid XML document syntax.
     at net.sourceforge.jnlp.XMLParser.getRootNode(XmlParser.java:118)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:498)
     at net.sourceforge.jnlp.Parser.getRootNode(Parser.java:1380)
     at net.sourceforge.jnlp.JNLPFile.parse(JNLPFile.java:867)
     at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:233)
     at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)
     at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)
     at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)
     at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:453)
     ... 6 more
 Caused by: net.sourceforge.nanoxml.XMLParseException: XML Parse Exception during parsing of a jnlp element at line 27: Expected: <
     at net.sourceforge.nanoxml.XMLElement.expectedInput(XMLElement.java:1185)
     at net.sourceforge.nanoxml.XMLElement.scanElement(XMLElement.java:1024)
     at net.sourceforge.nanoxml.XMLElement.scanElement(XMLElement.java:1019)
     at net.sourceforge.nanoxml.XMLElement.parseFromReader(XMLElement.java:514)
     at net.sourceforge.nanoxml.XMLElement.parseFromReader(XMLElement.java:466)
     at net.sourceforge.jnlp.XMLParser.getRootNode(XmlParser.java:114)
     ... 17 more 
```

**Comment by sclassen** [comment]
I took the liberty to format the log in your issue description.
Better formatted logs can be obtained when logging to files. The Java console is meant for directly viewing the logs as the application is running.
Bug reports are easier to answer with the logs from the files as they contain more information and are properly formatted.

Once this is done the error is very clear and easy to fix

```
XML Parse Exception during parsing of a jnlp element at line 27: Expected: <
```
and here the jnlp:

```
line: 26    <jar href="../JarExtractor.jar"/>
line: 27  <jar href="../TeLogging_1.0.0.jar"/>  -->
line: 28  <jar href="../ControlliCommonV1.jar"/>    
```

There seams to be a leftover from an XML comment in the file.

**Comment by darkbasic** [comment]
@sclassen thanks for formatting the log.
Unfortunately editing the file is not enough because I guess it automatically downloads a new version:
`<jnlp spec="1.0+" codebase="https://jws.agenziaentrate.it/jws/dichiarazioni/2020/" href="CIR20_fx.jnlp">`

How can I force it to use the local CIR20_fx.jnlp?

**Comment by sclassen** [comment]
remove the `href` attribute on line 2

**Comment by darkbasic** [comment]
Unfortunately it still doesn't work:

```
Class-Path attribute cleared for /home/niko/.cache/icedtea-web/cache/16/https/jws.agenziaentrate.it/jws/org.json.jar
java.lang.ClassNotFoundException: javafx.application.Application
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClassExt(JNLPClassLoader.java:1803)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClass(JNLPClassLoader.java:1603)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.access$1701(JNLPClassLoader.java:104)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader$5.run(JNLPClassLoader.java:1749)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader$5.run(JNLPClassLoader.java:1746)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.findClass(JNLPClassLoader.java:1745)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClassExt(JNLPClassLoader.java:1782)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClass(JNLPClassLoader.java:1582)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.access$1701(JNLPClassLoader.java:104)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader$5.run(JNLPClassLoader.java:1749)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader$5.run(JNLPClassLoader.java:1746)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.findClass(JNLPClassLoader.java:1745)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClassExt(JNLPClassLoader.java:1782)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClass(JNLPClassLoader.java:1582)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:556)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:946)

java.lang.NoClassDefFoundError: javafx/application/Application
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.access$1701(JNLPClassLoader.java:104)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader$5.run(JNLPClassLoader.java:1749)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader$5.run(JNLPClassLoader.java:1746)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.findClass(JNLPClassLoader.java:1745)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClassExt(JNLPClassLoader.java:1782)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClass(JNLPClassLoader.java:1582)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.access$1701(JNLPClassLoader.java:104)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader$5.run(JNLPClassLoader.java:1749)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader$5.run(JNLPClassLoader.java:1746)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.findClass(JNLPClassLoader.java:1745)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClassExt(JNLPClassLoader.java:1782)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClass(JNLPClassLoader.java:1582)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:556)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:946)
Caused by: java.lang.ClassNotFoundException: javafx.application.Application
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClass(JNLPClassLoader.java:1645)
	... 34 more

Exception in thread "Comunicazione Opzioni per interventi edilizi e superbonus" java.lang.RuntimeException: java.lang.NoClassDefFoundError: javafx/application/ApplicationSystem logger called with result of 0
```
[log.txt](https://github.com/AdoptOpenJDK/IcedTea-Web/files/8075198/log.txt)

**Comment by sclassen** [comment]
Since your JNP file does not contain the required jars for a JavaFX application you must make sure that OWS will select a JVM which includes the JavaFX libraries.
Or you add the JavaFX libs to the JNLP

https://openwebstart.com/docs/FAQ.html#_how_to_run_openjfx_based_javafx_applications_with_openwebstart

**Comment by darkbasic** [comment]
The problem is that the icedtea-8 JVM does not support javafx, while openjdk-11 (the only one where you can add the JavaFX libs to the JNLP according to your link) does not work with javaws:

```
$ javaws CIR20_fx.jnlp
selected jre: /etc/java-config-2/current-system-vm
Warning!, Fall back in resolve_jar to hardcoded paths: 
no
Warning!, Fall back in resolve_jar to hardcoded paths: 
/usr/bin/itw-modularjdk.args
Error: could not open `/usr/bin/itw-modularjdk.args'
```

Contrary to icedtea-8 it looks like openjdk-8 **can** be compiled with support for javafx, but it's masked for the ppc64le architecture in Gentoo. I've unmasked it, compiled openjdk-8 and tried to use it instead of icedtea-8: now it works. Thank you very much for your help.

**Comment by darkbasic** [comment]
If anyone stumbles upon this bug report, I've just discovered the new kid on the block: [OpenWebStart](https://bugs.gentoo.org/673050#c5).
It's a replacement that allows you to run Java Web Start (JWS) applications on latest Java (11+) which otherwise won't support it anymore. It's yet another alternative.
