### ISSUE TITLE
Error launching an application with IcedTeaWeb

### ISSUE THREAD

**Issue by atfield90** [AdoptOpenJDK/IcedTea-Web#864]
Hi everyone, 

i'm trying to launch an application not developed by me. IcedTeaWeb opens the application but then fails to launch it.
I've got no problem launching the application using Oracle Java.

Here's the log:

```
net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file. You can try to download this file manually and send it as bug report to IcedTea-Web team.
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)
	at net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)
	at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:280)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:220)
Caused by: net.sourceforge.jnlp.ParseException: Invalid XML document syntax.
	at net.sourceforge.jnlp.XMLParser.getRootNode(XmlParser.java:118)
	at net.sourceforge.jnlp.MalformedXMLParser.getRootNode(MalformedXMLParser.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.jnlp.Parser.getRootNode(Parser.java:1422)
	at net.sourceforge.jnlp.JNLPFile.parse(JNLPFile.java:867)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:233)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)
	at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)
	at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:453)
	... 6 more
Caused by: net.sourceforge.nanoxml.XMLParseException: XML Parse Exception during parsing of a jnlp element at line 28: Expected: <
	at net.sourceforge.nanoxml.XMLElement.expectedInput(XMLElement.java:1185)
	at net.sourceforge.nanoxml.XMLElement.scanElement(XMLElement.java:1024)
	at net.sourceforge.nanoxml.XMLElement.scanElement(XMLElement.java:1019)
	at net.sourceforge.nanoxml.XMLElement.parseFromReader(XMLElement.java:514)
	at net.sourceforge.nanoxml.XMLElement.parseFromReader(XMLElement.java:466)
	at net.sourceforge.jnlp.XMLParser.getRootNode(XmlParser.java:114)
	... 18 more

(details here: 

net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file. You can try to download this file manually and send it as bug report to IcedTea-Web team.     at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)     at net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)     at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)     at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:280)     at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)     at java.security.AccessController.doPrivileged(Native Method)     at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:220) Caused by: net.sourceforge.jnlp.ParseException: Invalid XML document syntax.     at net.sourceforge.jnlp.XMLParser.getRootNode(XmlParser.java:118)     at net.sourceforge.jnlp.MalformedXMLParser.getRootNode(MalformedXMLParser.java:79)     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)     at java.lang.reflect.Method.invoke(Method.java:498)     at net.sourceforge.jnlp.Parser.getRootNode(Parser.java:1422)     at net.sourceforge.jnlp.JNLPFile.parse(JNLPFile.java:867)     at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:233)     at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)     at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)     at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)     at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:453)     ... 6 more Caused by: net.sourceforge.nanoxml.XMLParseException: XML Parse Exception during parsing of a jnlp element at line 28: Expected: <     at net.sourceforge.nanoxml.XMLElement.expectedInput(XMLElement.java:1185)     at net.sourceforge.nanoxml.XMLElement.scanElement(XMLElement.java:1024)     at net.sourceforge.nanoxml.XMLElement.scanElement(XMLElement.java:1019)     at net.sourceforge.nanoxml.XMLElement.parseFromReader(XMLElement.java:514)     at net.sourceforge.nanoxml.XMLElement.parseFromReader(XMLElement.java:466)     at net.sourceforge.jnlp.XMLParser.getRootNode(XmlParser.java:114)     ... 18 more 
netx: Read Error: Could not read or parse the JNLP file. (Invalid XML document syntax. (XML Parse Exception during parsing of a jnlp element at line 28: Expected: <))
line: 43

line: 42 </jnlp>
line: 41 </application-desc>
line: 40 <application-desc main-class="it.finanze.entrate.assistenzafx.application.MainCIR20">
line: 39 </resources>
line: 38  <jar href="../../org.json.jar"></jar>
line: 37  <jar href="../../Supporto.jar"></jar>
line: 36  <jar href="../../iText-2.1.4.jar"></jar>
line: 35  <jar href="../../AnagCtrlCFPiva.jar"></jar>
line: 34    <jar href="../../checkCF_PIVA.jar"></jar>
line: 33  <jar href="ControlliCIR20.jar"></jar>
line: 32  <jar href="TelemCommonDic20.jar"></jar>    
line: 31  <jar href="../ComuniProvincia.jar"></jar>    
line: 30  <jar href="../TelemCommonV3-2.0.0.jar"></jar>    
line: 29  <jar href="../ControlliCommonV1.jar"></jar>    
line: 28  <jar href="../TeLogging_1.0.0.jar"></jar>  -->
line: 27    <jar href="../JarExtractor.jar"></jar>
line: 26  <jar href="../AssistenzaDicFxV1.jar"></jar>     
line: 25  <jar href="../AssistenzaFxV1.jar"></jar>     
line: 24  <jar href="../AssistenzaCommonV6.jar"></jar>     
line: 23  <jar href="CIR20/CIR20fx.jar"></jar>
line: 22  <j2se version="1.8+" href="http://java.sun.com/products/autodl/j2se" java-vm-args="--add-opens=java.desktop/java.awt=ALL-UNNAMED"></j2se>
line: 21 <resources>
line: 20 <update check="always" policy="always"></update>
line: 19 </security>
line: 18  <all-permissions></all-permissions>
line: 17 <security>
line: 16 <offline-allowed></offline-allowed>
line: 15 </information>
line: 14  </shortcut> 
line: 13    <menu submenu="Unico On Line"></menu>
line: 12  <shortcut online="true" install="true">
line: 11  <offline-allowed></offline-allowed>
line: 10  <description>Comunicazione Opzioni per interventi edilizi e superbonus</description>
line: 9  <homepage href="controlli2009Full.html"></homepage>
line: 8  <vendor>Agenzia delle Entrate</vendor>
line: 7 
line: 6  <icon href="logo.gif" kind="default"></icon>
line: 5  <title>Comunicazione Opzioni per interventi edilizi e superbonus</title>
line: 4 <information>
line: 3 <jnlp spec="1.0+" codebase="https://jws.agenziaentrate.it/jws/dichiarazioni/2020/" href="CIR20_fx.jnlp" xmlns="http://www.w3.org/1999/xhtml">
line: 2
<?xml version="1.0" standalone="yes"?>
Using MalformedXMLParser
JNLP file location: C:\Users\lnugnes001\Downloads\CIR20_fx (4).jnlp
Proceeding with jnlp
Unable to use Firefox's proxy settings. Using "DIRECT" as proxy type.
java.io.FileNotFoundException: C:\Users\lnugnes001\AppData\Roaming\Mozilla\Firefox\Profiles\ivelv0v1.default\prefs.js (The system cannot find the file specified)     at java.io.FileInputStream.open0(Native Method)     at java.io.FileInputStream.open(FileInputStream.java:195)     at java.io.FileInputStream.<init>(FileInputStream.java:138)     at java.io.FileReader.<init>(FileReader.java:72)     at net.sourceforge.jnlp.browser.FirefoxPreferencesParser.parse(FirefoxPreferencesParser.java:90)     at net.sourceforge.jnlp.browser.BrowserAwareProxySelector.parseBrowserPreferences(BrowserAwareProxySelector.java:153)     at net.sourceforge.jnlp.browser.BrowserAwareProxySelector.initFromBrowserConfig(BrowserAwareProxySelector.java:114)     at net.sourceforge.jnlp.browser.BrowserAwareProxySelector.initialize(BrowserAwareProxySelector.java:101)     at net.sourceforge.jnlp.runtime.JNLPRuntime.initialize(JNLPRuntime.java:293)     at net.sourceforge.jnlp.runtime.Boot.init(Boot.java:359)     at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:58)     at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:280)     at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)     at java.security.AccessController.doPrivileged(Native Method)     at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:220) 
Found preferences file: C:\Users\lnugnes001\AppData\Roaming\Mozilla\Firefox\Profiles/ivelv0v1.default\prefs.js
Using firefox's profiles file: C:\Users\lnugnes001\AppData\Roaming\Mozilla\Firefox\profiles.ini
Starting security dialog thread
Forcing of offline set to: false
WARNING: key deployment.system.cachedir has no value, setting to default value
Property "ows.install4j.propertyUpdate" is unknown.
Loading User level properties from: file:/C:/Users/lnugnes001/.config/icedtea-web/deployment.properties
Ico provider registered correctly.
cache: C:\Users\lnugnes001\.cache\icedtea-web file exists:true
config: C:\Users\lnugnes001\.config\icedtea-web file exists: true
System is already following XDG .cache and .config specifications
Using JRE version 1.8.0_322-b06 OpenJDK 64-Bit Server VM (Azul Systems, Inc.)
icedtea-web 1.8.8 (b2)
```

The application i'm trying to run is located here: https://jws.agenziaentrate.it/jws/dichiarazioni/2020/CIR20_fx.jnlp

Is anyone able to help understand why this happens?

Thanks,

Leonardo

**Comment by sclassen** [comment]
there is a broken comment string in your JNLP on line 28.

**Comment by atfield90** [comment]
thanks for the answer sclassen. 
unfortunately the JNLP is not developed by me, i'm just the end user.
Can something be done in IcedTea-Web to skip those kind of mistakes and run the application anyway?

Thanks again.

**Comment by sclassen** [comment]
Unfotunately no, implementing a generic solution which handles xml structural errors in a good enough fashion is very hard.

There is however a workaround:
- download the JNLP to your computer
- fix the broken line
- delete the `href` attribute in the `<jnlp>` tag on line 3

This modified JNLP will work because by removing the `href` you tell ITW to not download the JNLP from the server.
The downside is that you will not receive updates to the JNLP which are published on the server. But I assume that there will not be any updates or otherwise the xml error could be fixed
