### ISSUE TITLE
Can't launch .jnlp witch IcedTeaWeb

### ISSUE THREAD

**Issue by thikool825** [AdoptOpenJDK/IcedTea-Web#866]
Hello, 

currently I am trying to simply launch a .jnlp-File via IcedTeaWeb.
After a short period, i get the following error message:

at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)
at net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)
at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)
at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:274)
at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:214)
Caused by: java.io.IOException: java.lang.NullPointerException: name can't be null
at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:319)
at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:241)
at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)
at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)
at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)
at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:453)
... 6 more
Caused by: java.lang.NullPointerException: name can't be null
at java.base/java.io.FilePermission.init(FilePermission.java:323)
at java.base/java.io.FilePermission.<init>(FilePermission.java:490)
at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:756)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:146)
at net.sourceforge.jnlp.JNLPFile.openURL(JNLPFile.java:317)
... 11 more

I am behind a somewhat restrictive proxy/firewall, but have no idea if it is this what is causing my issue.
I have absolutly no Idea how to solve this issue and am thankful for any help I might get on this.

Thanks in advance!

Pascal

**Comment by janakmulani** [comment]
You can run the itweb-settings app to set the appropriate Network Proxy settings.
