### ISSUE TITLE
IcedTea-Web not interpreting javaws command line

### ISSUE THREAD

**Issue by atfield90** [AdoptOpenJDK/IcedTea-Web#872]
Hi Everyone,

i have a jnlp application which calls another jnlp application and tries to pass an argument using the -open command.
Basically the command used is:

javaws -open "C:\Users\lnugnes001\Desktop\PWCAABQ00000008_1398.dcmnoDcm" https://jws.agenziaentrate.it/jws/dichiarazioni/2020/ExecCIR20.jnlp

The -open "C:\Users\lnugnes001\Desktop\PWCAABQ00000008_1398.dcmnoDcm"  should be passed to https://jws.agenziaentrate.it/jws/dichiarazioni/2020/ExecCIR20.jnlp JNLP as stated in Oracle documentation:
https://docs.oracle.com/javase/7/docs/technotes/tools/share/javaws.html

What happens is that the command is not interpreted in the right way and the argument is not passed.

Here's the error log:

"failed to launch
net.sourceforge.jnlp.LaunchException: No local file 'C:\Program Files\IcedTeaWeb\WebStart\bin\-open' found and failed to create an URL from -open
        at net.sourceforge.jnlp.runtime.Boot.locationToUrl(Boot.java:392)
        at net.sourceforge.jnlp.runtime.Boot.launch(Boot.java:355)
        at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:335)
        at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:73)
        at java.security.AccessController.doPrivileged(Native Method)
        at net.sourceforge.jnlp.runtime.Boot.runMain(Boot.java:279)
        at net.sourceforge.jnlp.runtime.Boot.mainWithReturnCode(Boot.java:132)
        at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:114)
Caused by: java.net.MalformedURLException: no protocol: -open
        at java.net.URL.<init>(URL.java:611)
        at java.net.URL.<init>(URL.java:508)
        at net.sourceforge.jnlp.runtime.Boot.locationToUrl(Boot.java:386)
        ... 7 more"
        
       
Is there anyway we can fix this?
Can you point me in the right direction or fix the problem?

Thanks,

Leonardo

**Comment by sclassen** [comment]
IcedTeaWeb is offering the -arg command line argument which allows to pass arguments to the JNLP file.
