### ISSUE TITLE
FileNotFoundException: .mozilla/firefox/profiles.ini

### ISSUE THREAD

**Issue by adrbessy** [AdoptOpenJDK/IcedTea-Web#891]
Hello,

I use icedtea-web-1.8.8.linux.bin under linux environment,

In the bin directory, I execute 
`./itweb-settings`
Then in the JVM Settings, I set the JVM,
Then in the Network tab, I select Direct connection

Then in the bin directory, I execute 
`./javaws -verbose jnlp_file.jnlp`

Then I get this output :
```
...
java.io.FileNotFoundException: /home/user/.mozilla/firefox/profiles.ini
        at net.sourceforge.jnlp.browser.FirefoxPreferencesFinder.find(FirefoxPreferencesFinder.java:84)
        at net.sourceforge.jnlp.browser.BrowserAwareProxySelector.parseBrowserPreferences(BrowserAwareProxySelector.java:151)
        at net.sourceforge.jnlp.browser.BrowserAwareProxySelector.initFromBrowserConfig(BrowserAwareProxySelector.java:114)
        at net.sourceforge.jnlp.browser.BrowserAwareProxySelector.initialize(BrowserAwareProxySelector.java:101)
        at net.sourceforge.jnlp.runtime.JNLPRuntime.initialize(JNLPRuntime.java:293)
        at net.sourceforge.jnlp.runtime.Boot.init(Boot.java:353)
        at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:58)
        at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:274)
        at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)
        at java.security.AccessController.doPrivileged(Native Method)
        at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:214)
...
```

Do you know how I could configure IcedTea-Web to avoid it goes into mozilla config files ?
Thank you :)

**Comment by douglasawh** [comment]
Any update on this?

**Comment by adrbessy** [comment]
Yes, I resolved this by creating these both firefox config files :
/home/user/.mozilla/firefox/profiles.ini
/home/user/.mozilla/firefox/Profiles/qioxtndq.default/prefs.js
