### ISSUE TITLE
Could not read or parse the JNLP File

### ISSUE THREAD

**Issue by AEmCTS** [AdoptOpenJDK/IcedTea-Web#896]
`net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file. You can try to download this file manually and send it as bug report to IcedTea-Web team.     at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)     at net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)     at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)     at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:280)     at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)     at java.security.AccessController.doPrivileged(Native Method)     at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:220) Caused by: net.sourceforge.jnlp.ParseException: Invalid XML document syntax.     at net.sourceforge.jnlp.XMLParser.getRootNode(XmlParser.java:118)     at net.sourceforge.jnlp.MalformedXMLParser.getRootNode(MalformedXMLParser.java:79)     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)     at java.lang.reflect.Method.invoke(Method.java:498)     at net.sourceforge.jnlp.Parser.getRootNode(Parser.java:1422)     at net.sourceforge.jnlp.JNLPFile.parse(JNLPFile.java:867)     at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:233)     at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)     at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)     at net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)     at net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:453)     ... 6 more Caused by: net.sourceforge.nanoxml.XMLParseException: XML Parse Exception during parsing of a html element at line 3: Expected: /     at net.sourceforge.nanoxml.XMLElement.expectedInput(XMLElement.java:1185)     at net.sourceforge.nanoxml.XMLElement.scanElement(XMLElement.java:1038)     at net.sourceforge.nanoxml.XMLElement.scanElement(XMLElement.java:1019)     at net.sourceforge.nanoxml.XMLElement.parseFromReader(XMLElement.java:514)     at net.sourceforge.nanoxml.XMLElement.parseFromReader(XMLElement.java:466)     at net.sourceforge.jnlp.XMLParser.getRootNode(XmlParser.java:114)     ... 18 more`

When I try to launch the JNLP File with IcedTea-Web for our Callcenter-Software, I receive the above shown error message. Interessingly, this does not happen with OpenWebStart.

Java JRE used is "Azul Zulu JDK FX 8"

What bothers me is the fact, that IcedTea-Web is having issues with the jnlp file structure, where as OWS launches it perfectly.

I want to used IcedTea-Web, since OWS is not supporting Applets, which we use for another piece of software that is widely in use.

Greetings,
Alex
[start.zip](https://github.com/AdoptOpenJDK/IcedTea-Web/files/11167725/start.zip)

**Comment by TheScoubidou** [comment]
Hi,

I am facing a similar issue. It is working fine with OpenWebStart but Iced-Tea-Web 1.8.8 (Azul) raise this exception:

netx: Read Error: Could not read or parse the JNLP file. (MALFORMED MALFORMED; Invalid XML document syntax. (XML Parse Exception during parsing of a html element at line 2: Expected: /))

The log show that some random malformed HTML tag was "injected" in the JNLP (this is not in the original jnlp that we try to launch) . See line 2 in the log snippet below

---From itw-javantx  log ---

Using MalformedXMLParser
<?xml version="1.0" standalone="yes"?>
**line: 2 <html xmlns="http://www.w3.org/1999/xhtml"><body>&#239;&#187;&#191;**
line: 3 <jnlp spec="1.0+" codebase="http://server-dev1.local/eQCM/java" href="app.jnlp">
line: 4 	<information>
line: 5 		<title>APP 10.0.0.14</title>
line: 6 		<vendor>Acme</vendor>
------------------------

Thanks,
James

**Comment by TheScoubidou** [comment]
Update - 
In my case, the issue was that the jnlp was saved using "UTF-8-BOM". 
Saving the jnlp in UTF-8 without Byte Order Mark (BOM) fixed my issue.
