### ISSUE TITLE
Fatal: Initialization Error (unsigned jars?)

### ISSUE THREAD

**Issue by CocolinoFan** [AdoptOpenJDK/IcedTea-Web#915]
OS: Gentoo Linux x86_64
Kernel: 6.3.9-gentoo-dist
icedtea version: icedtea-web-1.8.8-r1::gentoo

Issues staring Dell's Remote Console. I think it might be related to the SSL certificate on the server (I am using the default one). The main takeaway from the error messages I took is the there wore some "jars" that needed to be signed?

After opening a .jnlp file to connect to the iDrac6 console: Fatal: Initialization Error: Could not initialize application. The application has not been initialized, for more information execute javaws for the command line.

Details:

net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize application. The application has not been initialized, for more information execute javaws from the command line.
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:823)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:531)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:946)
Caused by: net.sourceforge.jnlp.LaunchException: Fatal: Application Error: Cannot grant permissions to unsigned jars. Application requested security permissions, but jars are not signed.
	at net.sourceforge.jnlp.runtime.JNLPClassLoader$SecurityDelegateImpl.getClassLoaderSecurity(JNLPClassLoader.java:2488)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.setSecurity(JNLPClassLoader.java:384)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:807)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.<init>(JNLPClassLoader.java:337)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:420)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:494)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:467)
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:815)
	... 2 more

The beginning of the console:

System logger called with result of 0
System logger called with result of 0
System logger called with result of 0
System logger called with result of 0
System logger called with result of 0
System logger called with result of 0
System logger called with result of 0
System logger called with result of 0
System logger called with result of 0
net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize application. The application has not been initialized, for more information execute javaws from the command line.     
at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:823)     
at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:531)     
at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:946) 
Caused by: net.sourceforge.jnlp.LaunchException: Fatal: Application Error: Cannot grant permissions to unsigned jars. Application requested security permissions, but jars are not signed.
     at net.sourceforge.jnlp.runtime.JNLPClassLoader$SecurityDelegateImpl.getClassLoaderSecurity(JNLPClassLoader.java:2488)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.setSecurity(JNLPClassLoader.java:384)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:807)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.<init>(JNLPClassLoader.java:337)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:420)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:494)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:467)
     at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:815)     
... 2 more 
net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize application. The application has not been initialized, for more information execute javaws from the command line.
     at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:823)
     at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:531)
     at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:946) 
Caused by: net.sourceforge.jnlp.LaunchException: Fatal: Application Error: Cannot grant permissions to unsigned jars. Application requested security permissions, but jars are not signed.     
at net.sourceforge.jnlp.runtime.JNLPClassLoader$SecurityDelegateImpl.getClassLoaderSecurity(JNLPClassLoader.java:2488)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.setSecurity(JNLPClassLoader.java:384)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:807)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.<init>(JNLPClassLoader.java:337)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:420)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:494)
     at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:467)
     at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:815)
     ... 2 more 
netx: Initialization Error: Could not initialize application. (Fatal: Application Error: Cannot grant permissions to unsigned jars. Application requested security permissions, but jars are not signed.)
App already has trusted publisher: false
Jar found at /home/cocolino/.cache/icedtea-web/cache/2/https/192.168.0.120/443/software/avctVMLinux64.jarhas been verified as UNSIGNED
Jar found at /home/cocolino/.cache/icedtea-web/cache/3/https/192.168.0.120/443/software/avctKVMIOLinux64.jarhas been verified as UNSIGNED
Jar found at /home/cocolino/.cache/icedtea-web/cache/1/https/192.168.0.120/443/software/avctKVM.jarhas been verified as UNSIGNED
Removed sun.net.www.protocol.https.DelegateHttpsURLConnection:https://192.168.0.120:443/software/avctVMLinux64.jar
Disconnecting sun.net.www.protocol.https.DelegateHttpsURLConnection:https://192.168.0.120:443/software/avctVMLinux64.jar
isCurrent: https://192.168.0.120:443/software/avctVMLinux64.jar = true
isCurrent:lastModified cache:1545304473000 actual:1545304473000
isCurrent:isCached true
isCached: remote:135203 cached:135203
done https://192.168.0.120:443/software/avctVMLinux64.jar
Adding sun.net.www.protocol.https.DelegateHttpsURLConnection:https://192.168.0.120:443/software/avctVMLinux64.jar
Connecting https://192.168.0.120:443/software/avctVMLinux64.jar
Removed sun.net.www.protocol.https.DelegateHttpsURLConnection:https://192.168.0.120:443/software/avctKVMIOLinux64.jar
Disconnecting sun.net.www.protocol.https.DelegateHttpsURLConnection:https://192.168.0.120:443/software/avctKVMIOLinux64.jar
isCurrent: https://192.168.0.120:443/software/avctKVMIOLinux64.jar = true
isCurrent:lastModified cache:1545304473000 actual:1545304473000
isCurrent:isCached true
isCached: remote:983672 cached:983672
best url for location=https://192.168.0.120:443/software/avctVMLinux64.jar state=PRECONNECT CONNECTING PREDOWNLOAD PROCESSING is https://192.168.0.120:443/software/avctVMLinux64.jar by HEAD
done https://192.168.0.120:443/software/avctKVMIOLinux64.jar
Adding sun.net.www.protocol.https.DelegateHttpsURLConnection:https://192.168.0.120:443/software/avctKVMIOLinux64.jar
Connecting https://192.168.0.120:443/software/avctKVMIOLinux64.jar
Removed sun.net.www.protocol.https.DelegateHttpsURLConnection:https://192.168.0.120:443/software/avctVMLinux64.jar
best url for location=https://192.168.0.120:443/software/avctKVMIOLinux64.jar state=PRECONNECT CONNECTING PREDOWNLOAD PROCESSING is https://192.168.0.120:443/software/avctKVMIOLinux64.jar by HEAD

**Comment by CocolinoFan** [comment]
lol one year later I was looking for the same problem. Thank you for the answer past CocolinoFan.

I can confirm that this solution works on Ubuntu 24.04 as well. The files you need to edit are:
```
/etc/java-8-openjdk/security/java.security
/etc/java-21-openjdk/security/java.security
```
