### ISSUE TITLE
IcedTeaWeb support for openjdk 21+

### ISSUE THREAD

**Issue by bourgesl** [AdoptOpenJDK/IcedTea-Web#935]
Since jdk18 deprecated java SecurityManager methods, icedtea-web fails to start any jnlp app.

I propose to make icedtea-web work with latest jdk in degraded mode ie less-secure as missing security manager features will just say Yes (like full-privileges).

I will make this new BypassSecurityManagerSupport in my icedtea-web 1.8 fork as I want to make my own ( jdk21 LTS + icedtea-web 1.8.x ) bundle for my end-users.

PS: Hacking freedom is amazing !

Cheers,
Laurent

**Comment by AlBundy33** [comment]
JRE 21
```
Exception in thread "main" java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(Unknown Source)
	at net.sourceforge.jnlp.runtime.JNLPRuntime.initialize(JNLPRuntime.java:268)
	at net.sourceforge.jnlp.runtime.Boot.init(Boot.java:353)
	at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:58)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:274)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:214)

```

JRE 17
```
selected jre: C:\Program Files\Eclipse Adoptium\jre-17.0.18.8-hotspot
Unrecognized VM option 'MaxPermSize=256m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by janakmulani** [comment]
https://github.com/karakun/OpenWebStart works with Java 21/22. It passes -Djava.security.manager=allow to the JVM that is used to launch the Jnlp application.

**Comment by AlBundy33** [comment]
So ITW is dead in favor of OWS?

Just asking because I know some companies that are still using ITW (in most cases still with Java 8)

**Comment by judovana** [comment]
https://src.fedoraproject.org/rpms/icedtea-web/blob/rawhide/f/icedtea-web-1.8.8-java21-security-manager.patch

yes. It is dead. It do not work with jdk25 anyway
