### ISSUE TITLE
Appication does not start

### ISSUE THREAD

**Issue by gdm53** [AdoptOpenJDK/IcedTea-Web#939]
Dears,
I get following message as soon as I try to launch the file CPM24_ASD_fx.jnlp:
1) Fatal: Read Error: Could not read or parse the JNLP file YOU CAN TRY TO DOWNLOAD.........................
This is the message:
 net.sourceforge.jnlp.LaunchException: Fatal: Read Error: Could not read or parse the JNLP file. You can try to download this file manually and send it as bug report to IcedTea-Web team.
	at java.desktop/net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:489)
	at java.desktop/net.sourceforge.jnlp.Launcher.launch(Launcher.java:289)
	at java.desktop/net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:67)
	at java.desktop/net.sourceforge.jnlp.runtime.Boot.run(Boot.java:270)
	at java.desktop/net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/net.sourceforge.jnlp.runtime.Boot.main(Boot.java:210)
Caused by: net.sourceforge.jnlp.ParseException: MALFORMED MALFORMED; Invalid XML document syntax.
	at java.desktop/net.sourceforge.jnlp.XMLParser.getRootNode(XmlParser.java:118)
	at java.desktop/net.sourceforge.jnlp.MalformedXMLParser.getRootNode(MalformedXMLParser.java:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.desktop/net.sourceforge.jnlp.Parser.getRootNode(Parser.java:1380)
	at java.desktop/net.sourceforge.jnlp.JNLPFile.parse(JNLPFile.java:867)
	at java.desktop/net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:233)
	at java.desktop/net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:215)
	at java.desktop/net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:200)
	at java.desktop/net.sourceforge.jnlp.JNLPFile.<init>(JNLPFile.java:186)
	at java.desktop/net.sourceforge.jnlp.Launcher.fromUrl(Launcher.java:453)
	... 6 more
Caused by: net.sourceforge.nanoxml.XMLParseException: XML Parse Exception during parsing of a jnlp element at line 27: Expected: <
	at java.desktop/net.sourceforge.nanoxml.XMLElement.expectedInput(XMLElement.java:1184)
	at java.desktop/net.sourceforge.nanoxml.XMLElement.scanElement(XMLElement.java:1023)
	at java.desktop/net.sourceforge.nanoxml.XMLElement.scanElement(XMLElement.java:1018)
	at java.desktop/net.sourceforge.nanoxml.XMLElement.parseFromReader(XMLElement.java:514)
	at java.desktop/net.sourceforge.nanoxml.XMLElement.parseFromReader(XMLElement.java:466)
	at java.desktop/net.sourceforge.jnlp.XMLParser.getRootNode(XmlParser.java:114)
	... 18 more
Is there anyone willing to help and address me to a solution?
Thanks in advance
Gianni

PS: file CPM24_ASD_fx.jnlp: 

<?xml version="1.0" encoding="UTF-8"?>
<jnlp spec="1.0+" codebase="https://jws.agenziaentrate.it/jws/dichiarazioni/2024/" href="CPM24_ASD_fx.jnlp">
<information>
  <title>5 X 1000 ASD</title>
  <icon href="logo.gif" kind="default" />
  
  <vendor>Agenzia delle Entrate</vendor>
  <homepage href="controlli2009Full.html" />
  <description>5 X 1000 ASD</description>
  <offline-allowed/>
  <shortcut online="true" install="true"> 
    <menu submenu="Unico On Line"/>
  </shortcut>  
</information>
<offline-allowed/>
<security>
  <all-permissions/> 
</security>
<update check="always" policy="always"/>
<resources>
  <j2se version="1.8+"  href="http://java.sun.com/products/autodl/j2se" java-vm-args="--add-opens=java.desktop/java.awt=ALL-UNNAMED"/>
  <jar href="CPM24_ASD/CPM24fx.jar"/>
  <jar href="../AssistenzaFxV2.jar"/>       
  <jar href="../AssistenzaDicFxV2.jar"/>       
   <jar href="../JarExtractor.jar"/>
  <jar href="../TeLogging_1.0.0.jar"/>  -->
  <jar href="../ControlliCommonV1.jar"/>	
  <jar href="../TelemCommonV4.jar"/>	
  <jar href="../ComuniProvincia.jar"/>	
  <jar href="TelemCommonDic24.jar"/>	
  <jar href="ControlliCPM24.jar"/>
   <jar href="../../checkCF_PIVA.jar"/>
  <jar href="../../AnagCtrlCFPiva.jar"/>
  <jar href="../../UtilityStampaPDF.jar" />
  <jar href="../../pdf-manager-2.0.0.jar" />
  <jar href="../../openpdf-1.3.30.jar" />
  <jar href="../../Supporto.jar"/>
  <jar href="../../org.json.jar"/>
</resources>
<application-desc main-class="it.finanze.entrate.assistenzafx.application.MainCPM24">
</application-desc>
</jnlp>

**Comment by sclassen** [comment]
There is an invalid closing comment on line 26:  `<jar href="../TeLogging_1.0.0.jar"/>  -->`
