### ISSUE TITLE
Error - Fatal: Launch Error: Could not launch JNLP file. The application has not been initialized.

### ISSUE THREAD

**Issue by Hani-Arina** [AdoptOpenJDK/IcedTea-Web#951]
Hi IcedTea-Web Support Team,

One of the users for Rapid Response application is encountering an issue when attempting to open a Kinaxis Rapid Response JNLP file using javaws.exe. It will return a Fatal Read Error: "Could not launch JNLP file. The application has not been initialized."

OpenJDK: Eclipse Adoptium jdk-8.0.332.9-hotspot
IcedTeaWeb version: 1.8.8
OS: Microsoft Windows 11

I have attached the error message and the error log for your reference.
![IcedTeaWeb Error Message](https://github.com/AdoptOpenJDK/IcedTea-Web/assets/126647503/78958d5e-2e96-456f-8d73-3d30249a1395)
<img width="664" alt="image" src="https://github.com/AdoptOpenJDK/IcedTea-Web/assets/126647503/5bd5647e-1484-4b8a-ab89-83863ee2df78">

[[Error log]RapidResponse.txt](https://github.com/user-attachments/files/16011065/Error.log.RapidResponse.txt)

Troubleshooting that had been done from our side is:
1. Clear Java cache by purging them in the itweb-setting
2. Clear the temp and %temp% cache files
3. Clear history from browser
4. Deleting old JNLP files
5. Login using other browsers
6. Initialize JNLP file with javaws.exe
<img width="215" alt="image" src="https://github.com/AdoptOpenJDK/IcedTea-Web/assets/126647503/70f3999e-22b7-48fb-a2f4-18bd465c3975">

7. Reinstall Eclipse Adoptium and IcedTeaWeb

But the issue is not fixed. User is still unable to launch the application.
Please help to advise what can be done to fix this issue.

**Comment by sclassen** [comment]
The stacktrace contains `com.kinaxis` classes.
So the code is running the application and ITW has completed its work.

Maybe try to contact a developer from kinaxis and present them the following error message:

```
java.nio.file.AccessDeniedException: C:\Users\JP6200~1\AppData\Local\Temp
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.checkReadAccess(WindowsFileSystemProvider.java:338)
	at sun.nio.fs.WindowsFileSystemProvider.checkAccess(WindowsFileSystemProvider.java:362)
	at java.nio.file.Files.createDirectories(Files.java:746)
	at com.kinaxis.web.embeddedBrowser.ClientBridge.createCachePaths(ClientBridge.java:365)
```

**Comment by Hani-Arina** [comment]
Hi sclassen,

Would you know how to fix this?
![javaws browser](https://github.com/AdoptOpenJDK/IcedTea-Web/assets/126647503/f875ad12-efc8-4cdd-8974-73e6ae96743f)
