### ISSUE TITLE
AccessControlException: Access Denied - java.lang.reflect.ReflectPermission

### ISSUE THREAD

**Issue by WeierE1** [AdoptOpenJDK/IcedTea-Web#953]
Hi IcedTea-Web Support Team,

i get an AccessControlException: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks") when i start my application. In the JNLP file i set the security to all-permissions.

My JNLP Files looks like this

`<?xml version="1.0" encoding="utf-8"?>
<jnlp spec="1.0+">
  <information>
    <title>advise-mes</title>
    <vendor>HF-Mixing Group</vendor>
    <description>%project.description.long%</description>
    <description kind="short">%project.description.short%</description>
    <icon kind="shortcut" href="js/appIcon.png" width="64" height="64"/>
    <icon kind="splash" href="js/splashScreen.png"/>
    <shortcut online="true">
        <desktop/>
        <menu submenu="HF-Mixing Group"/>
    </shortcut>
    <offline-allowed/>
  </information>
  <security>
    <all-permissions/>
  </security>
  <resources>
    <j2se version="21*" vendor="Eclipse Adoptium" java-vm-args="-Xmx3g -Xms1g"/>
    .....
</resources>`

when running my application i got this error:
java.security.AccessControlException: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:488)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:1071)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:411)
	at net.sourceforge.jnlp.runtime.JNLPSecurityManager.checkPermission(JNLPSecurityManager.java:272)
	at java.base/java.lang.reflect.AccessibleObject.checkPermission(AccessibleObject.java:92)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:176)
	

can you please help me.

**Comment by WeierE1** [comment]
Hi IcedTea-Web Support Team,

I figured out the following: 
when the SecurityManager is enabled i get this AccessControlException: Access Denied also for other Permissions in the ForkJoinPool threads. If I disable the SecurityManager with -nosecurity everything works fine. Do you have an idea what has to be changed to make it work. I'm using openwebstart which is using Icedtew-Web

**Comment by andreiacsantos** [comment]
Hi Support Team,
I am having the same issue when using Java 17 from Oracle (it runs ok with Java 17 from Azul Zulu). Is there any way of adding the -nosecurity option to the itw-modularjdk.args or itweb-settings.exe? I cannot ask our clients to always run the application with the command line to use the -nosecurity option.

Thank you
