### ISSUE TITLE
OpenWebstart get stuck on certificate selection screen (multi-threading with event dispatch thread hack)

### ISSUE THREAD

**Issue by merkisoft** [AdoptOpenJDK/IcedTea-Web#962]
I was able to reproduce this with a self-issued certificate on localhost.

The problem exists when doing a backend call in a SwingUtilities.invokeLater at the same time as a background thread calls a the backend to the server with a broken certificate.

Result: the certificate dialog and the UI are completely frozen.

Now it's super easy to reproduce, see my comment:
https://github.com/karakun/OpenWebStart/issues/594#issuecomment-2498960727

I suspect that the locking does not work properly in this case, in the following section:
https://github.com/AdoptOpenJDK/IcedTea-Web/blob/d8414248348bc2b08cb5f97926decaa491a0dfa8/core/src/main/java/net/adoptopenjdk/icedteaweb/client/parts/dialogs/security/SecurityDialogs.java#L305

```         awt thread
            message.lock = null;    
...

            // background thread
            message.lock = new Semaphore(0);
            ...
            message.lock.acquire();
```
and most likely both call `JNLPRuntime.getSecurityDialogHandler().postMessage(message);`

btw this issue was first raised here: https://github.com/karakun/OpenWebStart/issues/594
but the broken code is in this repo (14 year old code ... :-))

**Comment by merkisoft** [comment]
i hooked up the debugger and found:

``` 
"AWT-EventQueue-1@4187" prio=6 tid=0x30 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for Kursverwaltung@4178 to release lock on <0x168a> (a net.sourceforge.jnlp.security.VariableX509TrustManager)
	  at net.sourceforge.jnlp.security.VariableX509TrustManager.checkTrustServer(VariableX509TrustManager.java:191)
	  at net.sourceforge.jnlp.security.VariableX509TrustManagerJDK7.checkTrustServer(VariableX509TrustManagerJDK7.java:104)
	  at net.sourceforge.jnlp.security.VariableX509TrustManagerJDK7.checkServerTrusted(VariableX509TrustManagerJDK7.java:70)
	  at sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)
	  at sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)
``` 


checkTrustServer is synchronized and blocking the AWT EventQueue-1
